### ISSUE TITLE
Ranking up issue

### ISSUE THREAD

**Issue by ccreep** [Staartvin/Autorank-2#201]
Hello i run a drug server and am having issues with the autorank plugin. I am using autorank to rank cops up i use the simpleconfig for ranking them up by time. The issue is were some of the ranks don't get the option to rankup ik its case sensitive but i have made them how they are suppose to be but there's still issues. I am using permissionsex as my permissions plugin If anyone can help i would be greatful.

Permissionsex file: http://pastebin.com/qsgCsZP3
Autorank simple config: http://pastebin.com/Cc0X9ium

**Comment by Staartvin** [comment]
Are you getting any errors in the server log or when you log in?

**Comment by ccreep** [comment]
No not at all

**Comment by Staartvin** [comment]
Hmm, I unfortunately can't really do anything if I have no logs. Could you post the server log of a run with Autorank?

**Comment by ccreep** [comment]
http://pastebin.com/yxHvQHEf my server log

**Comment by Staartvin** [comment]
That pastebin is private, I can't access it.

**Comment by ccreep** [comment]
changed it to public

**Comment by Staartvin** [comment]
Could you upload it again, if I click it, it goes nowhere.

**Comment by ccreep** [comment]
http://pastebin.com/aZSdcs3s

**Comment by Staartvin** [comment]
Autorank isn't even installed on your server. You should fix those other plugins as well. It seems a lot of them are having problems on your server.

**Comment by ccreep** [comment]
hm thats really strange since i can run the commands and theres files etc

**Comment by ccreep** [comment]
wow alot of plugin errors i recently cleared through alot of my plugins and updated to 1.8
