### ISSUE TITLE
Autorank not keeping players times

### ISSUE THREAD

**Issue by RetroNuke** [Staartvin/Autorank-2#203]
@Staartvin 

I'm using Spigot 1.8 and Autorank as well as many additional plugins. My problem lies where when I add time to a player, their time just stops.

I re-installed autorank.jar to get all new files, and then manually set the time for players that have ranked, but when I do that, their time no longer accumulates. It's frozen at the time they accumulated before I gave them time + the time I added. Please help?

**Comment by Staartvin** [comment]
So after you've changed the times (how did you do this? By hand? By command?), it stops updating the times?

**Comment by RetroNuke** [comment]
Yes, so.. I was having issues with signs, and I did a server wipe, forgetting to back up Autorank. Fortunately the server isn't open yet, but the few users I had poking around as test dummies, when I reinstalled Autorank, wanted their hour or so back.

As soon as I gave their hour back via "/ar add (name) 1h", Autorank stopped keeping track of time. It froze them at that 1 hour.

**Comment by RetroNuke** [comment]
I should also add that when the command was freezing them, I decided to add their time directly into the data file (I forget the actual file), but it kept track of each users time in minutes. I manually changed those by hand and restarted the server, but not even that worked.

**Comment by Staartvin** [comment]
Hmm. This is very weird. Can you turn on the debug mode, let Autorank run for a while (an hour) and post the pastebin here.
