### ISSUE TITLE
ar leaderboard exempt not working for some admins

### ISSUE THREAD

**Issue by Echen-kraul** [Staartvin/Autorank-2#208]
i posted this in the bukkit thread for this plugin and am again posting this here

"Ive had this continued issue with the leaderboard both on my server in 1.7.10 and again on 1.8.3.. Some of my admins and some owners show up on the leaderboard regardless of the perm - autorank.leaderboard.exempt existing in the rank. whats odd about this is not all are effected. some admins and some owners do not show up while others do and adding the perm directly to the players who do show up do nothing to take them off. My admins are all in one group called admin, all but one do not show up on the leader board. 1 owner out of 3, all in the group owner, also shows up on the leaderboard despite the fact that he has always had the owner rank and always had this perm. in 1.7.10 it was the same thing, only more were on the list than are now."

I would like to add that as much as this does not make any sense it certainly is occuring. is there a way maybe to purge the leader board and force it to recheck perms and times? does it do this automaticly upon restarting the server or does it pull this info from a cache to begin with? I just dont understand how 2 people can have the same perms and ranks and one show up on the leaderboard and the other does not. Im completely clueless as to how to fix this and as i stated above ive even added the perm directly to the player that shows up on the list and yet they still show up on the leaderboard. other than this issue and  a minor bug i can live with ive had little to no problems with this plugin.... i would just like to get ALL of my admins and the owners off of /ar leaderboard.

**Comment by Staartvin** [comment]
Hmm, it's probably happening due to players being offline. Autorank is having troubles getting play time of players that are offline and might show players that have the exempt permission on the leaderboard. There is not really anything you can do about this, I've tried some things, but none of them seem to work unfortunately.

**Comment by Echen-kraul** [comment]
uhm.... yea.... that would kinda make sense i guess ... now that im thinking about it ... generally the ones on the leaderboard are offline at that time. How does it pull data to run the leaderboard? i mean how often does it run a check to update it?

what if, and im not to sure how much work this would be, but what if there was a table in the mysql that tracked perms of this nature and when running a check would compare time in game to who has been "flaged" as having the exempt perm. and if that perm was taken away, the next time Ar checked things, the table would be updated and that player would then be displayed on the board.... and vise versa.

**Comment by Staartvin** [comment]
I could try implement something but it'll take some time to develop.

**Comment by Staartvin** [comment]
Could you try this version and see if it does any good? http://62.131.38.74:8080/job/Autorank/368/

**Comment by Echen-kraul** [comment]
i tested it out.... what exactly should i have been looking for because it seemed to be basicly the same.

on a test server i loaded this and replaced the existing folder with the new one and set up mysql. i had me and a admin/team member log in and we waited till the freshly created table was generated with both of us in it. we then logged out and restarted the server and only i logged back in. at log in both of us were on the leader board. i waited for another 10 minutes or so and checked again and i was no longer on the leader board but he still was. 

I didnt notice any new tables or colums in mysql and didnt notice anything different in the configs. 

it seemed to function properly otherwise though.

**Comment by Echen-kraul** [comment]
oh wait i jsut noticed that this versions changes were for itemFound.getAmount()

i didnt check that but i can when i get a chance to.

**Comment by Echen-kraul** [comment]
also.... im not using a stats plugin atm is there one that you recomend?

**Comment by Staartvin** [comment]
Stats (by Lolmewn) is a pretty good stats plugin to use. I'm not really sure on what you are testing right now. Could you test dev build 368?

**Comment by Echen-kraul** [comment]
I did. It was no different.... i was only remarking that what was changed in that build didnt have much to do with AR Leaderboard. it still acts the same way though. people no online still show up on the leaderboard even with the permission exempt

**Comment by Staartvin** [comment]
Okay, so try 369, I changed leaderboard code around.
