### ISSUE TITLE
Plugin does not work.

### ISSUE THREAD

**Issue by Roadhog360** [Staartvin/Autorank-2#212]
Version: Autorank v2.4.2 Beta
Server Version: MCPC+ 1.5.2
Server Mods: FTB Unleashed
Vault is installed. Please help.

**Comment by Staartvin** [comment]
Does it give any errors?

**Comment by Roadhog360** [comment]
Forgot this ticket even existed until I got a notif that you closed it. Sorry. Server's down now, but I'll let you know if I have any more issues with it if I need it again.
Just wondering; would this work for prison ranks? Like pay to rankup?

**Comment by Staartvin** [comment]
Autorank can be customized to be used on prison servers, yes.
