### ISSUE TITLE
AutoRank Error Message

### ISSUE THREAD

**Issue by Hardcore0uch** [Staartvin/Autorank-2#214]
Hi guys I keep getting this message and I dont know what I did wrong or where to look at. Any help would be amazing

ERROR Vault didn't tell what permissions plugin is being used! Autorank's leaderboard might not work properly!

**Comment by Staartvin** [comment]
Could you update to the latest dev build?

**Comment by Hardcore0uch** [comment]
Hi there, 

Sorry to bother you. 

My players are unable to rank up after I've made some additional ranks.

It is saying "user" has played for 1 day 14 hours 45 minutes and is in Newbie. Requirements to be ranked up: none (last rank up group).

This is my paste bin for Autorank ranks http://pastebin.com/b6t2WGi0

And this is my paste bin for permissionsex http://pastebin.com/gENuxtZJ

**Comment by Hardcore0uch** [comment]
This is still an update of my configs and permissions

Autorank config http://pastebin.com/rg2AeaZh

Permissionsex http://pastebin.com/DTkwnCGk
