### ISSUE TITLE
Add /ar gadd.

### ISSUE THREAD

**Issue by rickygwapo** [Staartvin/Autorank-2#220]
hi, i have an issue on having players the right time for global rank as for my voting, i give players bonus play time whenever they vote which is a /ar add command but it only adds it on the /ar check and not the /ar gcheck. what i mean is that it doesn't add it on the global ranking but it only adds it on that local server which is the problem. I need the auto rank to add time on the Global ranking time and not just on the local play time

**Comment by Staartvin** [comment]
You can currently not change global time with a command, only by hand. This feature will be implemented soon.

**Comment by rickygwapo** [comment]
ok thank you, if you ever have this added really soon. i will be donating on this plugin. :)

**Comment by rickygwapo** [comment]
still waiting for this update :(

**Comment by Staartvin** [comment]
I'm very busy for the next couple of weeks, I'm sorry for that!

**Comment by rickygwapo** [comment]
so still nothing huh

**Comment by Staartvin** [comment]
Just finished exams, will be coming soon!

**Comment by Staartvin** [comment]
I've added the new features you wanted. These are available in the 381 dev build.

**Comment by aximilation** [comment]
Way to go @Staartvin , I've been doing this via SQL so far, though I was having some sync issues. Are there any potential race conditions arising from adding global time, possibly while a player is logged into another server? I'll try the dev build out soon.

**Comment by Staartvin** [comment]
No, there should be no issues with adding global time to a player. He or she should never be on two servers together though.
