### ISSUE TITLE
Achievement

### ISSUE THREAD

**Issue by Nidalia** [Staartvin/Autorank-2#261]
Hi, i would like to know if it's possible to link Advanced achievements with Autorank  

http://dev.bukkit.org/bukkit-plugins/advanced-achievements/

Kinds regards
Avaloon

**Comment by Staartvin** [comment]
It's not possible yet, but I can look into it.

**Comment by Nidalia** [comment]
Thank's :)

**Comment by Staartvin** [comment]
AdvancedAchievements is now supported by Autorank.
