### ISSUE TITLE
Autorank not showing up in console or on server?

### ISSUE THREAD

**Issue by DSLady** [Staartvin/Autorank-2#264]
I have the autorank plugin installed and it's not working in game on the server. I tried checking the console for errors and there's nothing. I did a search for autorank and nothing came up, it's not booting up with the server. I have read the FAQ, but maybe I'm missing something obvious!?

**Comment by Staartvin** [comment]
What is not working, do you have any error logs? Please provide any quantified info you have.

**Comment by DSLady** [comment]
When my server restarts, the console logs all the plugins as being enabled. Autorank does not show up as one of these or anywhere in the console, so there are no error logs or anything else.
When I'm on the server, autorank doesn't appear in the /help command or rank up any players, new or previous. 
I have just uninstalled the plugin and am begining a reinstall to see if that changes anything.

**Comment by DSLady** [comment]
Have just had an error message stating '02.10 07:48:18 [Server] ERROR Disabling Autorank: Vault was not found' 

This came before it.
02.10 07:53:59 [Server] INFO Autorank 3.6 has been disabled!
02.10 07:53:59 [Server] INFO Disabling Autorank v3.6
02.10 07:53:59 [Server] ERROR Disabling Autorank: Vault was not found
02.10 07:53:56 [Server] Startup Done (5.301s)! For help, type "help" or "?"
02.10 07:53:56 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
02.10 07:53:56 [Server] INFO Autorank 3.6 has been enabled!
02.10 07:53:56 [Server] INFO Using timings of: autorank
02.10 07:53:56 [Server] INFO Language file loaded (lang.yml)
02.10 07:53:56 [Server] INFO Data file loaded
02.10 07:53:56 [Server] INFO Interval check every 5 minutes.
02.10 07:53:56 [Server] INFO Loaded libraries and dependencies
02.10 07:53:56 [Server] INFO No stats plugin found! Most requirements cannot be used!
02.10 07:53:56 [Server] INFO Loaded playerdata.
02.10 07:53:56 [Server] INFO Loaded stored uuids.
02.10 07:53:56 [Server] INFO Backup data file loaded (backup-data.yml)
02.10 07:53:56 [Server] INFO Settings config file loaded
02.10 07:53:56 [Server] WARN ... 15 more
02.10 07:53:56 [Server] WARN at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
02.10 07:53:56 [Server] WARN at org.yaml.snakeyaml.Yaml.load(Yaml.java:369)
02.10 07:53:56 [Server] WARN at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
02.10 07:53:56 [Server] WARN at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
02.10 07:53:56 [Server] WARN at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
02.10 07:53:56 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
02.10 07:53:56 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
02.10 07:53:56 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229)
02.10 07:53:56 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
02.10 07:53:56 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229)
02.10 07:53:56 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
02.10 07:53:56 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229)
02.10 07:53:56 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
02.10 07:53:56 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224)
02.10 07:53:56 [Server] WARN at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
02.10 07:53:56 [Server] WARN at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
02.10 07:53:56 [Server] WARN at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570)
02.10 07:53:56 [Server] INFO ^
02.10 07:53:56 [Server] INFO ... just been promoted to Corporal!'; give &p 320 32; give &p 91 1;  ... 
02.10 07:53:56 [Server] INFO in 'string', line 17, column 101:
02.10 07:53:56 [Server] INFO expected <block end>, but found Scalar
02.10 07:53:56 [Server] INFO ^
02.10 07:53:56 [Server] INFO rank change: Private;Corporal
02.10 07:53:56 [Server] INFO in 'string', line 16, column 13:
02.10 07:53:56 [Server] WARN Caused by: while parsing a block mapping
02.10 07:53:56 [Server] WARN at java.lang.Thread.run(Unknown Source)
02.10 07:53:56 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:504)
02.10 07:53:56 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:235)
02.10 07:53:56 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:325)
02.10 07:53:56 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:370)
02.10 07:53:56 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:406)
02.10 07:53:56 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:314)
02.10 07:53:56 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:342)
02.10 07:53:56 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
02.10 07:53:56 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
02.10 07:53:56 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
02.10 07:53:56 [Server] WARN at me.armar.plugins.autorank.Autorank.onEnable(Autorank.java:203)
02.10 07:53:56 [Server] WARN at me.armar.plugins.autorank.data.SimpleYamlConfiguration.<init>(SimpleYamlConfiguration.java:55)
02.10 07:53:56 [Server] WARN at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169)
02.10 07:53:56 [Server] WARN at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226)
02.10 07:53:56 [Server] WARN at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57)
02.10 07:53:56 [Server] INFO ^
02.10 07:53:56 [Server] INFO ... just been promoted to Corporal!'; give &p 320 32; give &p 91 1;  ... 
02.10 07:53:56 [Server] INFO in 'string', line 17, column 101:
02.10 07:53:56 [Server] INFO expected <block end>, but found Scalar
02.10 07:53:56 [Server] INFO ^
02.10 07:53:56 [Server] INFO rank change: Private;Corporal
02.10 07:53:56 [Server] INFO in 'string', line 16, column 13:
02.10 07:53:56 [Server] WARN org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
02.10 07:53:56 [Server] INFO Simple config file loaded
02.10 07:53:56 [Server] INFO Enabling Autorank v3.6

**Comment by Staartvin** [comment]
It seems your Autorank Advanced config is not loading properly. Could you provide the config?

**Comment by DSLady** [comment]
I believe it to be this 
http://pastebin.com/rQbHEDqX
Thank you!

**Comment by Staartvin** [comment]
You have a ' after Corporal! in the command result of the Private rank as well as the corporal rank (sergeant!')

**Comment by DSLady** [comment]
This is the new config file http://pastebin.com/x0Jc5WcS and these are the errors showing up http://pastebin.com/ZfrKQ22p
Vault is installed and running, it's saying no stats plugin found but mcmmo is installed and running fine in game...

**Comment by Staartvin** [comment]
This is a more subtle error, but there is still something wrong with the format of the config. Your Captain, Major, Colonel and General have one space less in front of them than the other ones. You should add a space in front of all of them.

Use this to validate your YAML: http://www.yamllint.com/
