### ISSUE TITLE
QUESTION - Blocks Placed count showing on /AR CHECK

### ISSUE THREAD

**Issue by Jawakotb** [Staartvin/Autorank-2#267]
Hello!
  I have recently implemented 'blocks placed' on my autorank plugin, but some of my visitors are requesting that they can see how many 'blocks are needed to be placed' when they do /AR CHECK.  Is this possible currently via IG, or can I manually check in a config file or if this doesn't exist now, could it be reviewed for possibly being added in a future release?

Thanks!

**Comment by Staartvin** [comment]
What do they see when they do /ar check?

If you configured the blocks placed requirement properly, it should be shown on the /ar check command.

**Comment by Jawakotb** [comment]
Thanks for the reply Staartvin!

Config for a single rank (all others share same options, just different values) looks like this:
  (Note that this is the start rank for this WORLD, as I have another set of ranks configured for another world via AutoRank.)

    SkyDweller:
        requirements:
            time:
                value: 12h
            blocks placed:
                value: 500
            world:
                value: ASkyBlock
        results:
            rank change: SkyDweller;CloudHopper;ASkyBlock
            command: 'say &p has just been promoted to CloudHopper!; eco give &p 500; tell &p You have just earned $500.00!'
            message: 'Congratulations, you are now a SkyBlock CloudHopper!'

Here is what a non-staffer sees when performing /AR CHECK:

  >> Picture <<  http://i.imgur.com/L3leYJr.png     >> Picture << 

As you can see, the /AR CHECK shows I do need 500 blocks, but it doesn't show how many more I need to place inorder to complete requirement #2.  This is what my players are asking to see, if that is possible that is.

Again, thank you for reviewing my question.

**Comment by Staartvin** [comment]
Ah, I understand! Players can use /ar track # to see their progress towards a requirement. In your example, the blocks placed requirement is shown as number 2, so you would do /ar track 2. This would show their progress. Don't forget to give them the autorank.track permission!

**Comment by Jawakotb** [comment]
Thanks for the update Staartvin!   It appears I have lots to learn about AutoRank.  Thanks for the quick guide!

**Comment by Jawakotb** [comment]
One more concern now Staartvin...since it appears I am a noob at this.

My players are now able to type /ar track #, but it appears the blocks placed are not incrementing.  (All players so 0/500)  This leads me to believe I do not have ALL blocks listed as a valid item to count.  

Here is my config on this again:

        blocks placed:
            value: 500

How do I specify ANY or ALL blocks placed are to be counted?

Thanks!

**Comment by Staartvin** [comment]
You don't specify any block ID or data value, therefore any block will count. Do you have Stats enabled?

**Comment by Jawakotb** [comment]
I am sorry to ask this, but what exactly do you mean by Stats enabled?  (Runs to look at config files...)

**Comment by Jawakotb** [comment]
AH!   I JUST now saw the "https://github.com/Armarr/Autorank-2/wiki/Requirements-&-Results" page is SCROLLABLE and it stats that the item I wish to track REQUIRES the STATS plugin.

Thanks for the help Staartvin

**Comment by Staartvin** [comment]
Yeah, it's a little odd, but that's due to Github's design :(

**Comment by Jawakotb** [comment]
Thanks again Staatvin!   I will do that which I must now that I am armed with the right info!
