### ISSUE TITLE
Internal error when using /ar check

### ISSUE THREAD

**Issue by ryanguy426** [Staartvin/Autorank-2#293]
Absolutely no clue what's even happening here. First it worked just fine (automatically ranked a couple people without question), then suddenly internal errors after a restart. Nothing was changed between the time before, and after the restart.

Pastebin link to error: http://pastebin.com/tpgnWed6
Permissions plugin: bPermissions 2.12
Server version: PaperSpigot 1.8.8 (latest 1.8 build)
Java version: Java 8

**Comment by Staartvin** [comment]
What version of Autorank are you running?
