### ISSUE TITLE
Autorank Spamming with a message

### ISSUE THREAD

**Issue by MomaCods** [Staartvin/Autorank-2#297]
Every few minutes AR says A new day has arrived! All daily times have been reset! Why is this happening ?? and so frequently... i have never encountered this issue before

![screen shot 03-07-16 at 10 57 am](https://cloud.githubusercontent.com/assets/17677132/13574781/a6e33ddc-e453-11e5-8493-108bf11fc78b.PNG)

**Comment by MomaCods** [comment]
why was this closed? No one answered ?

**Comment by Staartvin** [comment]
Could you update to the latest dev build and see if the problem persists?
