### ISSUE TITLE
Question about making new requirement to autorank

### ISSUE THREAD

**Issue by c1kaaacsgo** [Staartvin/Autorank-2#302]
Hello staartvin !
Im interested in your plugin autorank.
Is there any way (in SuperAdvancedConfig) when player killes total 10 players on server he ranks up, but only if he have 1h played.
I created this : ranks:
    rank1:
        requirements:
            time:
                value: 1h
        results:
            rank change: rank1;rank2
            command: 'say &p is now Rank 2 !'
            message: 'Congratulations, you are now Rank 2 !'
But i dont know how to make when he killes total 10 players he got ranked up.
Please respond me via email : ebill.ivanovic@gmail.com thanks :)

**Comment by Staartvin** [comment]
Yes, this is possible! You will need a **players killed** requirement and a **time** requirement!
