### ISSUE TITLE
Getting achievements as another requirement to rank up

### ISSUE THREAD

**Issue by e3valdas** [Staartvin/Autorank-2#303]
Hello. If you would add achievements as a requirement to rank up, this plugin would fit my server perfectly. Some examples:

You need to HAVE achievements: [Taking Inventory and Getting Wood] so you could rank up to Survivor.

You need to HAVE achievements: [DIAMONDS! and Bake Bread] so you could rank up to Good Boy.

**Comment by Staartvin** [comment]
I'll work on that. Good suggestion!
