### ISSUE TITLE
Ranks and permissions

### ISSUE THREAD

**Issue by e3valdas** [Staartvin/Autorank-2#306]
Right now you can do something like this:
Regular player: nick
Player with rank: [Survivor]nick
Player with permission: [VIP]nick

However, you can't do something like this:
Player with rank and permission: [Survivor][VIP]nick or [VIP][Survivor]nick

Basically, I would like to have ranks not connected to permissions. Ranks would be just a decorative/informative thing about how cool you are, however, it wouldn't grant you anything else.

**Comment by Staartvin** [comment]
You can do this by downloading a custom prefix or suffix plugin and let Autorank update the current prefix or suffix with a new message. So for example, when a player meets all the requirements for a certain group, Autorank would perform a command like _/suffix <player> add [VIP]_. I have a public plugin called [SimpleSuffix](https://www.spigotmc.org/resources/simplesuffix.11055/) which would probably let you do this!
