### ISSUE TITLE
Updated to latest Autorank, no Error reason "has item"

### ISSUE THREAD

**Issue by mellowism** [Staartvin/Autorank-2#308]
Hi, 

Just updated and the console is spammed with this: http://pastebin.com/kA0BpBHg

So it seems to work when it comes to the last message but don't know yet if the has item requirement works or not.

config: http://pastebin.com/TUVLVKKS

Thanks and hope you did well on exams ;)

**Comment by Staartvin** [comment]
You want it so that a player only needs 1 golden shovel, right?

**Comment by mellowism** [comment]
I sendt you a pm on spigot. Never received an e-mail when you replied to this post so didn't see it until now :(

But yes, I want it so the player only needs one shovel. Do I on 3.7.3 need to put the amount as well?

**Comment by Staartvin** [comment]
If you download the latest dev build, you don't have to specify the amount.

**Comment by mellowism** [comment]
Thanks. :) Will do that tonight :)
