### ISSUE TITLE
Autorank no stats plugin found.

### ISSUE THREAD

**Issue by LoopyTown123** [Staartvin/Autorank-2#309]
My server console said "No stats plugin found! Most requirements cannot be used!"
http://pastebin.com/cqUXgcDk

It will let me do /ar check and I can see that I require 50.0 for money, but when I type /ar check and have enough money it acts as though I do not have enough money. And it doesn't count how long I've been on my server.

**Comment by Staartvin** [comment]
Can you show me your config? Also, could you provide a picture of what happens when you type /ar check?
