### ISSUE TITLE
"has item" no longer works

### ISSUE THREAD

**Issue by GanimanSwift** [Staartvin/Autorank-2#311]
With the last update to this plugin, the "has item" requirement no longer works.  I get this in the console:

[Autorank] Could not setup requirement 'has item'! It's invalid: check the wiki for documentation.

Using the same configs as the previous version.  I see no update in the documentation around this.  Maybe I missed it?  Please help.

**Comment by Soz3r** [comment]
This might help you

https://github.com/Armarr/Autorank-2/issues/308

**Comment by Staartvin** [comment]
Try the latest dev build, it should be fixed.
