### ISSUE TITLE
Craft Scheduler Error

### ISSUE THREAD

**Issue by CubeFool** [Staartvin/Autorank-2#312]
Thanks for updating for 1.9. You have a very useful plugin here. 

Three small issues
1) I get a minor craft scheduler thread error, which is not entirely new. I've been getting those with the previous versions, but it seemed to work out ok. 
2) With the 3.7.3 update I get an error for "has item." Has that been removed as a feature?
3) My minecraft console now tells me that version 3.7.2 is now available for download. I imagine I can turn off checking for updates in the config to get rid of this for now?

http://pastebin.com/s6SX6Ce3

Thanks for a great plugin.

**Comment by CubeFool** [comment]
Same issue, different server, latest 1.9.2 spigot build
http://pastebin.com/Qr69enX4

Issue on the server from the original post, server jar updated to latest 1.9.2 Spigot build
http://pastebin.com/nBTCDh9J

**Comment by Staartvin** [comment]
It seems Stats is not working properly. Autorank thinks Stats is enabled, but Stats does not work properly, also giving Autorank errors. If you fix Stats, Autorank will not complain anymore.
