### ISSUE TITLE
AutoSaveWorld conflict ?

### ISSUE THREAD

**Issue by Alibabaand40voleur** [Staartvin/Autorank-2#314]
Why i have error with AutoSaveWorld when i log AutoRank ?
http://pastebin.com/BWgipdAG

**Comment by Staartvin** [comment]
I don't see any errors!

**Comment by philip-ulrich** [comment]
It looks like AutoSaveWorld is complaining about AutoRank connecting to MySQL. It looks like that plugin (http://dev.bukkit.org/bukkit-plugins/autosaveworld/) has configurable warning messages. Does it look for plugins making outgoing connections or something?
