### ISSUE TITLE
A couple issues with Autorank

### ISSUE THREAD

**Issue by foreveralone1111** [Staartvin/Autorank-2#316]
First issue seems to be with a group rank change requirement. Probably missed something but..

> 25.04 03:05:43 [Server] INFO [Vault] Checking for Updates ... 
> 25.04 03:05:44 [Server] INFO [Vault] No new version available
> 25.04 03:05:48 [Server] WARN Exception in thread "Craft Scheduler Thread - 0" 
> 25.04 03:05:48 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Autorank v3.7.3 generated an exception while executing task 16
> 25.04 03:05:48 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
> 25.04 03:05:48 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 25.04 03:05:48 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 25.04 03:05:48 [Server] INFO at java.lang.Thread.run(Thread.java:745)
> 25.04 03:05:48 [Server] INFO **Caused by: java.lang.IllegalArgumentException: Requirement 'rank change' of group 'Member' is unknown!**
> 25.04 03:05:48 [Server] INFO at me.armar.plugins.autorank.rankbuilder.ChangeGroupBuilder.initAdvancedConfig(ChangeGroupBuilder.java:204)
> 25.04 03:05:48 [Server] INFO at me.armar.plugins.autorank.rankbuilder.ChangeGroupBuilder.initialiseChangeGroups(ChangeGroupBuilder.java:52)
> 25.04 03:05:48 [Server] INFO at me.armar.plugins.autorank.rankbuilder.ChangeGroupManager.initialiseFromConfigs(ChangeGroupManager.java:47)
> 25.04 03:05:48 [Server] INFO at me.armar.plugins.autorank.Autorank$1.run(Autorank.java:352)
> 25.04 03:05:48 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
> 25.04 03:05:48 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
> 25.04 03:05:48 [Server] INFO ... 3 more

Here's my config file: 
[http://pastebin.com/gaWbYE8n]

Second is an error that happens with the /ar commands. The /ar commands work fine for a couple mins, then something goes wrong with:

> 25.04 03:08:39 [Server] ERROR null
> 25.04 03:08:39 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'ar' in plugin Autorank v3.7.3
> 25.04 03:08:39 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-BT52_04_24.jar:git-Spigot-e6f93f4-7a6b143]
> 25.04 03:08:39 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-BT52_04_24.jar:git-Spigot-e6f93f4-7a6b143]
> 25.04 03:08:39 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-BT52_04_24.jar:git-Spigot-e6f93f4-7a6b143]
> 25.04 03:08:39 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot-BT52_04_24.jar:git-Spigot-e6f93f4-7a6b143]
> 25.04 03:08:39 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot-BT52_04_24.jar:git-Spigot-e6f93f4-7a6b143]
> 25.04 03:08:39 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-BT52_04_24.jar:git-Spigot-e6f93f4-7a6b143]
> 25.04 03:08:39 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-BT52_04_24.jar:git-Spigot-e6f93f4-7a6b143]
> 25.04 03:08:39 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-BT52_04_24.jar:git-Spigot-e6f93f4-7a6b143]
> 25.04 03:08:39 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
> 25.04 03:08:39 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
> 25.04 03:08:39 [Server] INFO at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-BT52_04_24.jar:git-Spigot-e6f93f4-7a6b143]
> 25.04 03:08:39 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-BT52_04_24.jar:git-Spigot-e6f93f4-7a6b143]
> 25.04 03:08:39 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-BT52_04_24.jar:git-Spigot-e6f93f4-7a6b143]
> 25.04 03:08:39 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-BT52_04_24.jar:git-Spigot-e6f93f4-7a6b143]
> 25.04 03:08:39 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-BT52_04_24.jar:git-Spigot-e6f93f4-7a6b143]
> 25.04 03:08:39 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
> 25.04 03:08:39 [Server] INFO **Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType.MOBS**
> 25.04 03:08:39 [Server] INFO at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_77]
> 25.04 03:08:39 [Server] INFO at org.bukkit.entity.EntityType.valueOf(EntityType.java:1) ~[spigot-BT52_04_24.jar:git-Spigot-e6f93f4-7a6b143]
> 25.04 03:08:39 [Server] INFO at me.armar.plugins.autorank.playerchecker.requirement.MobKillsRequirement.getDescription(MobKillsRequirement.java:37) ~[?:?]
> 25.04 03:08:39 [Server] INFO at me.armar.plugins.autorank.rankbuilder.holders.RequirementsHolder.getDescription(RequirementsHolder.java:153) ~[?:?]
> 25.04 03:08:39 [Server] INFO at me.armar.plugins.autorank.playerchecker.PlayerChecker.getRequirementsInStringList(PlayerChecker.java:172) ~[?:?]
> 25.04 03:08:39 [Server] INFO at me.armar.plugins.autorank.commands.CheckCommand.check(CheckCommand.java:238) ~[?:?]
> 25.04 03:08:39 [Server] INFO at me.armar.plugins.autorank.commands.CheckCommand.onCommand(CheckCommand.java:294) ~[?:?]
> 25.04 03:08:39 [Server] INFO at me.armar.plugins.autorank.commands.manager.CommandsManager.onCommand(CommandsManager.java:159) ~[?:?]
> 25.04 03:08:39 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-BT52_04_24.jar:git-Spigot-e6f93f4-7a6b143]
> 25.04 03:08:39 [Server] INFO ... 15 more

Help on this is, of course, appreciated.

**Comment by Staartvin** [comment]
The first issue is caused by the fact that you don't have 'results'  for the Member group. The rank change, command and message are all in the requirements part, but they should be in the results part. (look at your other groups, those are configured correctly)

**Comment by Staartvin** [comment]
The second issue I'm still investigating on.

**Comment by Staartvin** [comment]
I found the issue and will fix it. Expect a new dev build for you soon!

**Comment by Staartvin** [comment]
Could you use dev build 521? http://62.131.38.74:8080/job/Autorank/521/

**Comment by foreveralone1111** [comment]
Ah haha, figured I missed something. 

Dev build did not solve the issue.

**Comment by Staartvin** [comment]
Hmm, it did not? Is it still showing the same error?

**Comment by foreveralone1111** [comment]
Yeah, exact same error log in console.
