### ISSUE TITLE
No rankup found for first rank upgrade.

### ISSUE THREAD

**Issue by Antal1609** [Staartvin/Autorank-2#318]
I'm using ''player ranks'', the ranks which you can upgrade. And i'm using donator/staff ranks. For people without an extra rank everything works fine. But for people with an donator/staff rank; they can't do the first rank upgrade. It says no rankup found. Now my question, how can I solve this problem? 

Yes, I can manually add the right player rank when a player donates, but that cost time. And the purpose of this plugin is ''automatic'' :stuck_out_tongue: .

PermissionsEx: http://pastebin.com/JRzwQNfx
AdvancedConfig: http://pastebin.com/7BJcMynX
Errors: none

**Comment by 2fast4u2** [comment]
Are you using PermissionsEx? If so it would probably help if you posted the permissions file.

**Comment by Antal1609** [comment]
I did, lol :P

**Comment by Staartvin** [comment]
Hmm, so people that have a donator rank, is that their primary rank?

**Comment by Staartvin** [comment]
Also, which ranks of the advanced ranks do not work?

**Comment by Antal1609** [comment]
All ranks work fine, but the ''Starter'' rank is the default one. So when a player donates, that rank will be removed. So for people that where starter and donated doesn't have the starter rank anymore. That's why the plugin AutoRank can't see that rank. I can manually add the rank Starter to every donator... but that's not gonna to work xD 

* Alsto the stat blocks moved doesn't work. Some players got 2493/500 but it's not noded as ''Done''.

**Comment by Staartvin** [comment]
You can either change it so that when someone donates, the rank Donator is then added to the player. Instead of replacing the current rank of the player with the Donator rank, you can add the Donator rank to the player. That way the player will keep his current rank, but will also get the permissions of the donator rank. 

The other solution is to set 'get primary rank of vault' in the settings file of Autorank to false. 


Good luck, I'll be awaiting your answer.

**Comment by Antal1609** [comment]
The 'get primary rank of vault' setting solved some problems, tnx :P

1) Because the starter rank is the default rank is it not listed at your ''groups''. So when you donate you only got the donator rank. (Expect for players that already had an higher upgrade rank). But I can solve this problem by always give the player the rank ''Starter" + the Donator rank. Right?

2) The stat blocks moved doesn't work. Some players got 2493/500 but it's not noted as ''Done''.

**Comment by Antal1609** [comment]
Not tried them, but fish caught, crafting, mob kills, works fine. Also the block moved stat is working, but if players reached the requirement it isn't noted as done. So for example they got 2005/2000.

**Comment by Staartvin** [comment]
So a block placed requirement also doesn't auto complete? Could you show me your settings and advanced config?

**Comment by Antal1609** [comment]
I didn't use the block placed stat. You can see my advanced config in  the begin post.
- Settings: http://pastebin.com/7GEmSr7i

**Comment by Staartvin** [comment]
Hmm, that's very weird. Could you add a blocks moved requirement to another group and see if it also happens at that group?

**Comment by Antal1609** [comment]
Okay, send you the results about a few minutes.

**Comment by Antal1609** [comment]
Same. Current: 73507/5 (by foot)

**Comment by Antal1609** [comment]
Also AutoRank notes requirements that are using ''stats'' for other rank upgrades as done. So when you at rank1 and become rank2 you already got some things as done for the next upgrade. For example the mobs kills. I believe I readed somewhere that AutoRank will reset stats on a rank upgrade. (Except for votes & playtime.)

**Comment by Staartvin** [comment]
Okay, that sounds like super strange behavior. Autorank does indeed reset all progress of previous requirements when it ranks someone to a next rank. 

Could you turn on debug, restart your server and then show me the server log?

**Comment by Antal1609** [comment]
Do you have skype? For private chat :)
Skype: superantal

**Comment by Antal1609** [comment]
De log staat op skype.
