### ISSUE TITLE
Blocks moved tracked, but never completes

### ISSUE THREAD

**Issue by Hayden2006** [Staartvin/Autorank-2#321]
I have bukkit 1.9.2 and the latest stat3 and Autorank 3.7.3.

I have an issue where if I set up a blocks moved requirement for any of the transportation methods, /ar track will show that you have moved, but when you reach the requirement, it never gets marked with completion even with /ar complete.

Config in the PasteBin. I've commented out the problem areas since I can't get them to work.

http://pastebin.com/Ej4BiFRU

**Comment by Antal1609** [comment]
Same for me.

**Comment by Staartvin** [comment]
It seems there are more people having this problem. I'll look into it.
