### ISSUE TITLE
Has item singularity.

### ISSUE THREAD

**Issue by mdunlavy** [Staartvin/Autorank-2#325]
Apparently, the has item requirement no longer works in multiplicity.  For example:

If I have 
has item:
  value: blah;blah
has item:
 value: blahdy; blah

The /ar check and /ar view will only show the first has item requirement and will actually promote without the second item

If I have 
has item:
  value: blah;blah
has item2:
 value: blahdy; blah

/ar check and /ar view don't work. http://pastebin.com/3edUTtZx

I have tried to have multiple value lines for the one has item: requirement, and I have tried a host of other things... but it will never recognize the second has item requirement.

please advise

**Comment by mdunlavy** [comment]
I just saw this:            
            blocks broken: 
                value: (24;100;2),(30;100;2)
                # Break 100 sandstone blocks OR 100 webs
Which, by adapting the syntax for my has item predicament, I was able to create the requirement:
            has item:
                value: (322;1),(276;1)
Which is satisfied if the player has either a golden apple OR a diamond chestplate, but I want to create requirements using AND.  I have tried several combinations of different separators and parentheses, but nothing has worked. 

please advise.

**Comment by mdunlavy** [comment]
Really? No response to this at all?  Ridiculous.  #bump

**Comment by Staartvin** [comment]
Could you show me your advanced config?

**Comment by mdunlavy** [comment]
Thank you very much for your time! Yes I can show you!

http://pastebin.com/YeTd4Pv3

I am very sorry it took me so long to respond! We are in the middle of a move, so I was unable to get time away to send this to you!  Thank you again for your amazing plugin and for your help!


So the wierd thing about this is that only the last "has item" for each rank is displayed in the /ar view <rank>

**Comment by Staartvin** [comment]
Ah, each requirement should have its own unique name. So instead of 'has item', you can call the second one 'has item 2' or 'has item cool'. As long as it has the words 'has item' in it!

**Comment by mdunlavy** [comment]
My Gad. I tried that and it wouldn't work but now it is. fml.

Thank you.

Also, it would be a nice feature to have a has item requirement that says "Obtain x and y"  in the same way that you already have "Obtain x or y"...

Is that possible?

**Comment by Staartvin** [comment]
You want it so a requirement either requires x amount of stone or y amount of fish for example?

**Comment by mdunlavy** [comment]
No, I want the requirement to require x amount of stone AND y amount of fish. (instead of having 2 separate has item requirements)

**Comment by Staartvin** [comment]
That is not possible. I specifically designed so that you need two seperate requirements to make it easier understandable and readable.
