### ISSUE TITLE
I cannot get autorank working, ar check doesn't work and hours are not logged

### ISSUE THREAD

**Issue by Boter316** [Staartvin/Autorank-2#328]
12.05 21:52:48 [Server] INFO ... 8 more
12.05 21:52:48 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
12.05 21:52:48 [Server] INFO at me.armar.plugins.autorank.commands.manager.CommandsManager.onCommand(CommandsManager.java:128) ~[?:?]
12.05 21:52:48 [Server] INFO at me.armar.plugins.autorank.commands.CheckCommand.onCommand(CheckCommand.java:322) ~[?:?]
12.05 21:52:48 [Server] INFO at me.armar.plugins.autorank.commands.CheckCommand.check(CheckCommand.java:42) ~[?:?]
12.05 21:52:48 [Server] INFO at me.armar.plugins.autorank.util.uuid.UUIDManager.getUUIDFromPlayer(UUIDManager.java:236) ~[?:?]
12.05 21:52:48 [Server] INFO at me.armar.plugins.autorank.util.uuid.UUIDManager.getUUIDs(UUIDManager.java:360) ~[?:?]
12.05 21:52:48 [Server] INFO at me.armar.plugins.autorank.util.uuid.UUIDManager.addCachedPlayer(UUIDManager.java:45) ~[?:?]
12.05 21:52:48 [Server] INFO at me.armar.plugins.autorank.util.uuid.storage.UUIDStorage.storeUUID(UUIDStorage.java:192) ~[?:?]
12.05 21:52:48 [Server] INFO at me.armar.plugins.autorank.util.uuid.storage.UUIDStorage.isAlreadyStored(UUIDStorage.java:259) ~[?:?]
12.05 21:52:48 [Server] INFO at me.armar.plugins.autorank.util.uuid.storage.UUIDStorage.getPlayerName(UUIDStorage.java:245) ~[?:?]
12.05 21:52:48 [Server] INFO Caused by: java.lang.NullPointerException
12.05 21:52:48 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]
12.05 21:52:48 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
12.05 21:52:48 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
12.05 21:52:48 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:424) [lt.class:?]
12.05 21:52:48 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:465) [lt.class:?]
12.05 21:52:48 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:697) [CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
12.05 21:52:48 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
12.05 21:52:48 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
12.05 21:52:48 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
12.05 21:52:48 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'ar' in plugin Autorank v3.4
12.05 21:52:48 [Server] WARN Unexpected exception while parsing console command "ar check Boter316"

the paste is upside down I know, I grabbed it from console

anyway, what do I do? or is 1.7.10 not supported anymore, because I cannot find a new version as the forum post doesn't have an archive that I can see that dates farther back than 1.8.1

**Comment by 2fast4u2** [comment]
I believe you have to use version 3.7.2 or lower.
