### ISSUE TITLE
Autorank doesn't seem to be working for the 'global time' requirement.

### ISSUE THREAD

**Issue by zoredache** [Staartvin/Autorank-2#337]
I am trying to make a server that uses the global time for ranking up.  I am using the `global time` requirement, and I have a player that seems like it should meet the requirements, but isn't being leveled up.  I am not sure if I am miss-reading the comments in the config files, or if something is broken.

I have the player as belonging to the `Level01` group.  When I use `/ar gcheck` I see `94 days, 13 hours`, which should be more then enough to meet the 6h requirement to get to Level02.  When I look at `/ar track 1` it shows `Current: 136179/720`.  So it sure seems like I meet the requirements to level up, but `/ar check` doesn't level me up, it just shows the requirements for the next rank.

The underlying permissions system is permissionex, the server is 1.8.8.
- [AdvancedConfig.yml](https://gist.github.com/zoredache/8a38147af64faaed04b5d55b2993245b)
- [debug-20160526051023.txt](https://gist.github.com/zoredache/5df1b321f0f4b272986f476204633032)

**Comment by Jeje2201** [comment]
White you don't use "time: 6h" ? This format work for me
