### ISSUE TITLE
Sync or Import?

### ISSUE THREAD

**Issue by CobaltSparkz** [Staartvin/Autorank-2#339]
Dumb question - I have recently reset one of my servers, but kept all the AR data on a MySQL server. I tried the /ar import setting, no results, then tried /ar sync, also no results.

I can't quite understand the documentation in the wiki, due to the wording - Wondering if you could help?

Thanks

Sparky

**Comment by Staartvin** [comment]
You can use the _**/ar import**_ command, but that was built for importing data.yml files to Autorank. You'll have to convert the MySQL data to a data.yml in some way.

The _**/ar sync**_ command is used when you want to sync the MySQL server with the local file. However, since your data.yml is empty, nothing will be synced to the MySQL server.

**Comment by CobaltSparkz** [comment]
So essentially, I have a full MySQL DB That's completely useless? (Not meaning to sound rude, just curious!)

**Comment by Staartvin** [comment]
Welp, not necessarily. In the sense that there is no automated task that can obtain the data from the MySQL server and put it in the data.yml, it is useless. However and depending on the size of your MySQL database, you could try manually make a data.yml based on the data in the MySQL database. 

I could also look into a command that will read all your info from the MySQL database and put it in th e data,yml, if you would like that?

**Comment by CobaltSparkz** [comment]
Would be pretty awesome. Essentially got a MySQL DB that's full of data that I can't import or use, so would be good 📦

**Comment by Staartvin** [comment]
I've made a new command for you on this dev build: http://62.131.38.74:8080/job/Autorank/532/
To perform an extraction from MySQL to data.yml, you'll have to perform **/ar sync reverse**. Tell me if it worked for you!

**Comment by Staartvin** [comment]
You can also use this version:https://www.spigotmc.org/resources/autorank.3239/update?update=102166

**Comment by CobaltSparkz** [comment]
Hey, sorry for the delay - I'll try this and let you know :)
