### ISSUE TITLE
Ranks and prefixes don't update on other worlds

### ISSUE THREAD

**Issue by Roy416** [Staartvin/Autorank-2#348]
Hey yall. The server is using group manager as the permissions plugin. We are using Multiverse-Core, Per world plugins, Perworld inventory and perworld inventory. When the players rank up in a world e.g. survival, the prefix and ranks wont update when in another multiverse world such as factions. There is only one server, hence using multiverse.

**Comment by Staartvin** [comment]
Please provide more info, could you give your configs?
