### ISSUE TITLE
Auto Rank says "No rank up found"

### ISSUE THREAD

**Issue by TheSaltyPug** [Staartvin/Autorank-2#352]
When I do /ar check "name" I get the time reported for the player, but it says "no rank up found" at the end? Here is my AdvConfig, I have set it to use the Advanced config in the other file thing.

Thanks for the help!

http://pastebin.com/363bntsV

**Comment by Staartvin** [comment]
Your groups are not configured correctly: 

Let's take a look at one specific rank setup:
```
regular:
        requirements:
            time:
                value: 20h
        results:
            rank change: Member;regular
            command: 'say &p just got a promotion; broadcast &p has just been promoted to Regular!'
            message: 'Congratulations, you are now Regular.'
```

Right now, Autorank will not work for this group. The rank name (at the top, _regular_) should be the group from where a player is ranking. So let's say he's ranking from _Member_ to _Regular_, you'll need to put _Member_ there. Secondly, for the **rank change**, the first group is the group where the player is ranked from and the second group is the group he will be ranked to. So, in your case, the rank change tells Autorank to rank the player from Member to Regular, but the _regular_ at the top tells Autorank to check whether a player is the rank _regular_. Hence, you'll need to change _regular_ at the top with _Member_. You'll have to do this for all of your groups.

**Comment by TheSaltyPug** [comment]
Alright, that worked for the player ranks. How i want it to work is there are two sets of ranks: player and pvp. the player has permissions for both. pvp ranks are given when a player gets kills. When I do /ar check, it now says the time and rank up that is available, but the pvp one does not say it will check. Is it still checking? Yes, I did the changes you said to that too.
Thanks!

**Comment by Staartvin** [comment]
Could you show me your updated AdvancedConfig including the PVP ranks?

**Comment by TheSaltyPug** [comment]
http://pastebin.com/80w9EUuh

^ New paste with new advanced config.
I am usign my brother's player as a test subject. He is in BOTH the member group and the grunt group, but it does not say anything about a rank up to grunt with kills or anything.
Picture:
http://imgur.com/5nbuXUj

Thanks

**Comment by Staartvin** [comment]
Autorank can only check a player for one group at the same time. He has to complete the _Member_ rank before he can do the Grunt one.

**Comment by TheSaltyPug** [comment]
So will he go to member -> regular -> trusted -> elder before he can do the other ones?

**Comment by Staartvin** [comment]
Could you try setting _use primary group for vault_ to **true** in the Settings.yml?

**Comment by TheSaltyPug** [comment]
It already is, seems to have been by default.

**Comment by TheSaltyPug** [comment]
Bump

**Comment by Staartvin** [comment]
Sorry for the late reply. I gave you an incorrect answer. Could you try setting the _use primary group for vault_ to **false** (instead of true).

**Comment by Staartvin** [comment]
If you want to have a player rank up in two groups _simultaneously_, it is impossible. Autorank can rank players from group to group, but can only do so one at the time.

**Comment by TheSaltyPug** [comment]
I will try setting it to false; what is that supposed to do? 

So it cannot check two groups at one time, can that feature be added soon? It is kind of essential to my server.

**Comment by TheSaltyPug** [comment]
And I would really prefer not to install another plugin to get it done.

**Comment by Staartvin** [comment]
Setting it to false makes it so Autorank checks all ranks that a player has, not only the primary one.

**Comment by TheSaltyPug** [comment]
I set it to false, but now it ONLY checks the time based. I tried setting players to the highest time based, and it gives me "player is in group grunt, no rank up found." I just checked the config however, and it is still set up correctly. 

NOTE: I updated to version 3.8 and installed the latest Statz version
