### ISSUE TITLE
AutoRank - multiple rankups

### ISSUE THREAD

**Issue by OblivionNW** [Staartvin/Autorank-2#359]
When users rank up when meeting requirements they sometimes rank up multiple times (Jump some ranks), they also sometimes get ranked to the same rank multiple times.

**Comment by OblivionNW** [comment]
@Staartvin this issue is most likely related to #217

**Comment by OblivionNW** [comment]
Has this been fixed in a newer build?

**Comment by Staartvin** [comment]
Yes, Autorank received an overhaul in version 4, making this issue obsolete.
