### ISSUE TITLE
Rank up server lag

### ISSUE THREAD

**Issue by OblivionNW** [Staartvin/Autorank-2#360]
When users rank up after meeting the time requirement the server sometimes lags or freezes until the rank up is complete.

**Comment by Staartvin** [comment]
Can you show me your startup log and AdvancedConfig.yml?

**Comment by OblivionNW** [comment]
Adv config: http://pastebin.com/1fNkCJx1
Log:  http://pastebin.com/Lis1ZTWu

**Comment by Staartvin** [comment]
Could you try and upgrade to Autorank 3.8.2 if possible?

**Comment by OblivionNW** [comment]
Sure

**Comment by OblivionNW** [comment]
Still having the issue, may be linked to #359

**Comment by OblivionNW** [comment]
Has this been fixed in a newer build?

**Comment by Staartvin** [comment]
I'm not sure, I can't reproduce the issue.
