### ISSUE TITLE
Time not increasing for any player

### ISSUE THREAD

**Issue by Pr0Pancakes** [Staartvin/Autorank-2#362]
Time's doesn't seem to increase for any player would appreciate any help with this i've left some general info you might need below, wouldn't let me upload the zip file had to put it in dropbox

https://www.dropbox.com/s/zmpgf6uw40is063/config%20settings%20and%20debug.zip?dl=0

**Comment by Pr0Pancakes** [comment]
New update found this in the console http://pastebin.com/bHgjhApi

**Comment by Staartvin** [comment]
You should install Statz to let Autorank work.

**Comment by Pr0Pancakes** [comment]
Ah I see, I've installed stats and the plugin has begun working. I do have a question though, how did the plugin work before without the statz plugin? times were increasing and suddenly they stopped.

**Comment by Staartvin** [comment]
I'm not sure why it wasn't working before. It should have. Anyway, with Statz installed it'll all work fine!
