### ISSUE TITLE
Craft Scheduler Thread - 57

### ISSUE THREAD

**Issue by wedza** [Staartvin/Autorank-2#365]
Hello,

I love autorank, it's the main plugin of my server and I works well for my usage.

I configured the Advanced config (and I think I made an error writing it) and I get this error.

`[22:43:31] [Craft Scheduler Thread - 57/WARN]: Exception in thread "Craft Scheduler Thread - 57"[22:43:31] [Craft Scheduler Thread - 57/WARN]: org.apache.commons.lang.UnhandledException: Plugin Autorank v3.8.1 generated an exception while executing task 512at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)at java.lang.Thread.run(Thread.java:745)Caused by: java.lang.NoClassDefFoundError: me/staartvin/statz/hooks/Dependencyat me.armar.plugins.autorank.hooks.DependencyManager.isAFK(DependencyManager.java:98)at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:46)at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:81)at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.run(PlaytimesUpdate.java:30)at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)... 3 moreCaused by: java.lang.ClassNotFoundException: me.staartvin.statz.hooks.Dependencyat java.net.URLClassLoader.findClass(URLClassLoader.java:381)at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)at java.lang.ClassLoader.loadClass(ClassLoader.java:424)at java.lang.ClassLoader.loadClass(ClassLoader.java:357)... 9 more`

Here is my [Advanced Config . yml](http://pastebin.com/XZQYR7rF)

Thanks you very much !

**Comment by CathalCraft** [comment]
Same issue here: http://pastebin.com/uVDW61bG
Error occurs every 5 minutes.

Autorank v3.8.1
Spigot 1.10.2

**Comment by Staartvin** [comment]
You'll need to install Statz!

**Comment by wedza** [comment]
Stats or Statz ?
[This one ?](http://dev.bukkit.org/bukkit-plugins/lolmewnstats/)
If it is this one, it's not compatible 1.10 :cry: 

Thanks for your quick relpy !

**Comment by Staartvin** [comment]
Youll need Statz, made by me :)

**Comment by Staartvin** [comment]
Let's hope it works!
