### ISSUE TITLE
Afk time not being counted

### ISSUE THREAD

**Issue by ALufkin24** [Staartvin/Autorank-2#366]
Is there a way to make non afk time count?

I have a player who like to afk farm a lot. I don't want him to acquire time while he is in afk. Is there a way to fix that?

Also, is there a way to make it where they have to rank up Xhrs over Xdays??  Can I make the requirement 48hrs AND 14 days??
Example: 
   Elite:
        requirements:
            time:
                value: 48h
                value: 14d
        results:
            rank change: Elite;Legend
            command: 'say &p has just been promoted to Legend!'
            message: 'Congratulations, you are now a Legend!'
    Legend:
        requirements:
            time:
                value: 192h
                value: 60d
        results:
            rank change: Legend;Noble
            command: 'say &p has just been promoted to Noble!'
            message: 'Congratulations, you are now a Noble!'

**Comment by Staartvin** [comment]
Yes, you can set _afk integration_ in the Settings.yml to true. After that, you'll need to have a plugin that records AFK players like Essentials, AfkTerminator, UltimateCore or RoyalCommands.

**Comment by Staartvin** [comment]
For your second question, the answer is no. You cannot specify a time range where players should meet the requirements.
