### ISSUE TITLE
Votes and Stats

### ISSUE THREAD

**Issue by Henaminator** [Staartvin/Autorank-2#367]
Does this Autorank plugin support another plugin instead of stats when it comes to voting rank-up's?  (When votes are being required.) Because the Stats is a bit inactive, including the Authors, it also got so many problems with it and generate random errors.

Does this work with the Statz? And how does it work?

**Comment by Staartvin** [comment]
Yes, you can also use Statz. You'll need to install Votifier or NuVotifier.

**Comment by Henaminator** [comment]
There should be a way to transfer all the Stats from the Stats plugin to Statz

**Comment by Staartvin** [comment]
I'm working on adding a converter!
