### ISSUE TITLE
How do I reset players rank?

### ISSUE THREAD

**Issue by Tundral** [Staartvin/Autorank-2#370]
Hey. i'd like to be able to test myself if all of the parts of ranking up work alright and also just be able to do the ranking up myself. The only problem is that I haven't found any option or command or anything to reset a players ranking and stats. Is this a feature you yet haven't implemented or am I missing something?

**Comment by bshayhoe** [comment]
If you wanted to reset a player, you could set them back to the first group via your perms plugin, as for a stats reset, if you are using Statz this is entirely impossible to my knowledge...

Bshay

**Comment by Staartvin** [comment]
To reset a player to a specific rank, you'll have to downgrade him to manually via your permissions plugin. You can then perform /ar reset <player name>. 

If you're using Statz, you cannot reset data at the moment.

**Comment by Tundral** [comment]
Thanks for the help. too bad statz doesn't allow modifying the stats
