### ISSUE TITLE
Problems with the counting of killed mobs

### ISSUE THREAD

**Issue by ArtNRG** [Staartvin/Autorank-2#374]
I'm using Autorank v3.8.3 and Statz v1.3. 
Server is running Paper version git-Paper-"a653680" (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)

This section of autorank config was working ok with the Stats plugin, but after migrating on Statz some problems are appeared. This condition is not taken even after killing a lot of WITHER_SKELETON's.

```
mobs killed:
                value: 1;WITHER_SKELETON
```

Same problem:

```
mobs killed:
                value: 1;ENDER_DRAGON
```

But it's ok with both below:

```
mobs killed:
                value: 5;GUARDIAN
```

```
mobs killed:
                value: 1;GHAST
```

Autorank AdvancedConfig.yml [http://pastebin.com/53rvLSuu](http://pastebin.com/53rvLSuu)
Autorank Settings.yml [http://pastebin.com/i14Xzsxn](http://pastebin.com/i14Xzsxn)
Statz config.yml [http://pastebin.com/1QqwN5xz](http://pastebin.com/1QqwN5xz)

**Comment by Staartvin** [comment]
Hmm, I'll be testing all the mob kills and see which ones still give problems!
