### ISSUE TITLE
No rankup found

### ISSUE THREAD

**Issue by bshayhoe** [Staartvin/Autorank-2#375]
Hello Author,

Autorank is saying that it cannot find any rankups when I have added more than 10, I am using the advanced config which you can find here: http://pastebin.com/QhmLWu5k

I am sure it is a stupid mistake but hopefully you are able to assist me

Thanks.

**Comment by Staartvin** [comment]
Which ranks are giving problems?

**Comment by bshayhoe** [comment]
It is Elder rank which is giving me an issue

**Comment by Staartvin** [comment]
Can you show me what Autorank shows when you type /ar check when in the group Elder?

**Comment by bshayhoe** [comment]
Ok, that has been fixed to my knowledge, but now when I type /ar check I am presented with this:
Read upwards...
12.08 19:18:41 [Server] INFO ... 15 more
12.08 19:18:41 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.10.2.jar:git-Spigot-5391d73-00359a1]
12.08 19:18:41 [Server] INFO at me.armar.plugins.autorank.commands.manager.CommandsManager.onCommand(CommandsManager.java:150) ~[?:?]
12.08 19:18:41 [Server] INFO at me.armar.plugins.autorank.commands.CheckCommand.onCommand(CheckCommand.java:296) ~[?:?]
12.08 19:18:41 [Server] INFO at me.armar.plugins.autorank.commands.CheckCommand.check(CheckCommand.java:143) ~[?:?]
12.08 19:18:41 [Server] INFO at me.armar.plugins.autorank.rankbuilder.holders.RequirementsHolder.meetsRequirement(RequirementsHolder.java:79) ~[?:?]
12.08 19:18:41 [Server] INFO at me.armar.plugins.autorank.playerchecker.requirement.BlocksBrokenRequirement.meetsRequirement(BlocksBrokenRequirement.java:91) ~[?:?]
12.08 19:18:41 [Server] INFO at me.armar.plugins.autorank.statsmanager.handlers.StatzHandler.getNormalStat(StatzHandler.java:63) ~[?:?]
12.08 19:18:41 [Server] INFO Caused by: java.lang.NullPointerException
12.08 19:18:41 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
12.08 19:18:41 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot-1.10.2.jar:git-Spigot-5391d73-00359a1]
12.08 19:18:41 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot-1.10.2.jar:git-Spigot-5391d73-00359a1]
12.08 19:18:41 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.2.jar:git-Spigot-5391d73-00359a1]
12.08 19:18:41 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [spigot-1.10.2.jar:git-Spigot-5391d73-00359a1]
12.08 19:18:41 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-5391d73-00359a1]
12.08 19:18:41 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
12.08 19:18:41 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
12.08 19:18:41 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-5391d73-00359a1]
12.08 19:18:41 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.10.2.jar:git-Spigot-5391d73-00359a1]
12.08 19:18:41 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.10.2.jar:git-Spigot-5391d73-00359a1]
12.08 19:18:41 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot-1.10.2.jar:git-Spigot-5391d73-00359a1]
12.08 19:18:41 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot-1.10.2.jar:git-Spigot-5391d73-00359a1]
12.08 19:18:41 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.10.2.jar:git-Spigot-5391d73-00359a1]
12.08 19:18:41 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.10.2.jar:git-Spigot-5391d73-00359a1]
12.08 19:18:41 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.10.2.jar:git-Spigot-5391d73-00359a1]
12.08 19:18:41 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'ar' in plugin Autorank v3.8.4
12.08 19:18:41 [Server] ERROR null
12.08 19:18:41 [Server] INFO bshayhoe issued server command: /ar check

**Comment by bshayhoe** [comment]
This is with version 3..8.4

**Comment by Staartvin** [comment]
Could you try this version? http://62.131.38.74:8080/job/Autorank/

**Comment by bshayhoe** [comment]
Works fine, apparently Autorank can't find the rank/ to promote from in the perm file
![2016-08-13_09 13 33](https://cloud.githubusercontent.com/assets/7383025/17642256/625918fc-6136-11e6-81b7-e581559b2bde.png)

**Comment by Staartvin** [comment]
Can you show me your permissions file?

**Comment by bshayhoe** [comment]
http://pastebin.com/0DpZs6At

**Comment by Staartvin** [comment]
You have group called 'rookie',  but you use the group 'Rookie' in the Autorank Config. Change either rookie into Rookie or the other way around!

**Comment by bshayhoe** [comment]
Ok, I have changed it in my perms and restarted the server. The issue is still there.
