### ISSUE TITLE
Autorank v3.8.5 generated an exception

### ISSUE THREAD

**Issue by TheChampTF** [Staartvin/Autorank-2#410]
http://paste.yu8.me/?6542b0a1fa18ed3a#7NX/+yEJtpa4Vb/TBntetPPO41gL5VO/ryrDBEK2XHY=

^Those works normally, so not sure what is wrong here.

**Comment by Staartvin** [comment]
Could be due to capital letter of Fishing and Repair?

**Comment by TheChampTF** [comment]
Not sure, trying to rename everything from capital to lowercase now
