### ISSUE TITLE
NullPointerException in PlayTimes.getTime()

### ISSUE THREAD

**Issue by v3Monsta** [Staartvin/Autorank-2#421]
**Autorank:** 3.8.5.1
**Statz:** 1.4

Before I noticed this in console, it happened twice with 5 minutes in-between the two exceptions.

**Stacktrace:** http://hastebin.com/ilukexisop.vbs

**Comment by Staartvin** [comment]
Do you know when it happens? Approximately?

**Comment by v3Monsta** [comment]
I checked the time stamps of both exceptions and it was 5 minutes apart- which is the same amount specified by interval check in the Settings.yml file.

Interestingly enough I re-enabled the plugin with debugging enabled to try and reproduce the NPE but nothing happened this time.
