### ISSUE TITLE
Players able to run hooks when not opped

### ISSUE THREAD

**Issue by plasticblues** [Staartvin/Autorank-2#423]
Just recieved a report of this, all players are able to run /ar hooks and /ar hook even after denying the permission to their groups. They do not have an allow anywhere and they are not opped.

**Comment by plasticblues** [comment]
Was this fixed in the newer versions or just closed because it's not important?

**Comment by Staartvin** [comment]
I've fixed this in the latest version of Autorank ;)

**Comment by plasticblues** [comment]
Thank you I appreciate it!
