### ISSUE TITLE
Is there a way to moderate rankups by # of days logged in?

### ISSUE THREAD

**Issue by DramasticStar** [Staartvin/Autorank-2#425]
I'm a little confused about how to do this, or if it's even possible with this pluggin.

I want my players to be able to rank up like this:

Rankup Requirements:
Newbie: 1st login
Member: 1 Day Logged (non-consecutive)
Regular: 7 days logged (non-consecutive)

1st login (Nov 1st): [Newbie]
2nd login (Nov 2nd) rank up to [Member]
3rd - 6th Login (Nov 3rd - Nov 6th)

Then say they skip a few days....

7th login (Nov 10th) - No rank up as they have only logged in for a total of 6 days
8th login (Nov 11th) - Rank up to [Regular]

Does this make sense? Is this possible?

**Comment by Staartvin** [comment]
Yes, I think this is possible if you mean by 'time logged' the last time they logged in?

**Comment by DramasticStar** [comment]
Basically like.. Even if they only logged in for 1 minute each day... As long as they logged on for a total of 7 days (non consecutively) they would rank up for meeting the 7 day mark and not have to play for a collective game time of 7 days (168 hours). 

But I don't want it so that if they logged in for 5 consecutive days (no. After how long they've played for) , skipped a week, and then logged in for their "sixth day"  on the server and get ranked up because they've technically been on the server for over 7 days.

**Comment by Staartvin** [comment]
Hmm, that is unfortunately not possible yet, but I can work on adding such a feature.

**Comment by DramasticStar** [comment]
That would actually be fantastic if you could figure it out. Since Mojang hit us with the EULA and we can't give rewards for voting any longer, I've been trying to find an alternative that keeps a similar system without actually counting time spent playing.

**Comment by Staartvin** [comment]
I've updated the dev branch with new functionality, can you try this version (http://178.62.255.148:8080/job/Autorank/49/)? Try using **/ar activity**!

**Comment by DramasticStar** [comment]
Thanks! I'll play with this for a few days and give you some feedback!
