### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by Wilci** [Staartvin/Autorank-2#431]
Hey!

Do you think you could add support for the plugin Quests?
Where some of the new requirements would be like "Have x amount of questpoints(1 given by every completed quest) to get a new rank and such, I think that Autorank and quests would would very great together and I would love to see you adding support for this plugin.

Regards Wilci! :)

**Comment by michaeldriskell** [comment]
Yes this would be a great idea! I downloaded the quests plugin recently and theres so many cool features. Id love to be able to use autorank with it! Please add this feature :)

**Comment by Redstonetorch** [comment]
Yeah I use autorank too, this would be aweomse to have with it

**Comment by Staartvin** [comment]
What kind of properties do you want Autorank to read?

1. How many questspoints a player has? 
2. How many quests a player completed? 

Anything else?

**Comment by Wilci** [comment]
If it is possible to read if a player has completed a specific quest would be great.

**Comment by Staartvin** [comment]
I will look into that!

**Comment by Staartvin** [comment]
Quests support has been added for Autorank.
