### ISSUE TITLE
"meets all the requirements but has already completed this rankup before"

### ISSUE THREAD

**Issue by VediusPollio** [Staartvin/Autorank-2#433]
Hello, I am trying to set up Arutorank on a server, and after someone (the person I'm testing this with) ranked up, I manually set their rank to go back one to test something, now no matter what I do it always says  "meets all the requirements but has already completed this rankup before" in /ar check. I have tried resetting every data file I can find and nothing fixes it, and I doing something wrong? Is there any way to fix this?

**Comment by frizzbee30** [comment]
you can change the infinite ranking option  :)
