### ISSUE TITLE
build 627 (test) error on start up

### ISSUE THREAD

**Issue by frizzbee30** [Staartvin/Autorank-2#435]
Hi, build 627 is failing to load on spigot 1.11.2 on our test server. Only posting here so that it may help you with later builds  :)
 
Thanks
 
 
http://pastebin.com/YaX7sqkk

**Comment by Staartvin** [comment]
Thanks for posting. I'm currently working on an overhaul of Autorank (Autorank 4.0), and it's not done yet.
