### ISSUE TITLE
Paths showing even without prerequisites 

### ISSUE THREAD

**Issue by Fordy436** [Staartvin/Autorank-2#447]
Main issues I'm highlighting:
1) Paths show in "/ar view list" even if they aren't achievable making it difficult to find the correct path
2) The default 'rank change' result (one given in the default config) doesn't appear to be working with PEX - No console errors.

It seems that every time you complete a Path (rank), you have to manually choose the next rank with "/ar choose RankName", but when you do "/ar view list", it shows every path on the system, whether they can actually advance to that path or not. I have 21 ranks on my Server and I don't want my Players to have to route through all 21 different Paths to find the current one they're supposed to advance to.

Maybe make it so unavailable paths (due to prerequisites not being met) aren't visible in the Path list?

I may be going about this the wrong way... I used to use the simpleconfig.yml and that isn't available anymore so this advanced version is all new to me. Here's the code example of how I tried to convert my old simpleconfig into the new format:

simpleconfig: (example using only 4 ranks)
Rank1: Rank2 after 3m
Rank2: Rank3 after 30m
Rank3: Rank4 after 1h

Attempted Conversion: ( Pastebin Version: http://pastebin.com/UDvPmC2f )

Do you have a fix for what I'm trying to do? On my Server, Players rank up simply by playing... when they reach a specific time played, they get promoted to the next rank in the system. They have to choose now though.

**Comment by Staartvin** [comment]
Thanks for the feedback. I'm adding an option for a path to show it on the list if a does not meet the prerequisites. By default (in the next beta), Autorank will only show paths where you meet the prerequisites.

Also, the rank change result is very buggy. Unfortunately, I cannot fix this (it's an issue with Vault implementation), but I recommend using a command result to perform the 'pex user &p set group <group name you want here>'.
