### ISSUE TITLE
Jobs are not aviable (jobs version 3.8.0)

### ISSUE THREAD

**Issue by Imothep80** [Staartvin/Autorank-2#449]
`[10:07:42 INFO]: Autorank Hooks:`

`[10:07:42 INFO]: JOBS: NOT AVAILABLE`

`>jobs`
`[10:07:43 INFO]: ------- ======= Jobs ======= -------`
`[10:07:43 INFO]: ----- ====== Page 1 of 6 ====== -----`
`[10:07:43 INFO]: /jobs join [Jobname] - Ausgewählten Job erlernen.`
`[10:07:43 INFO]: /jobs browse - Zeigt alle verfügbaren Jobs an.`
`[10:07:43 INFO]: /jobs bonus [jobname] - Show job bonuses`
`[10:07:43 INFO]: /jobs info [Jobname] [Tätigkeit] - Zeigt an, wie ein Job für was bezahlt wird.`
`[10:07:43 INFO]: /jobs area add/remove/info/list - Modify restricted areas.`
`[10:07:43 INFO]: /jobs stats [Spielername] - Zeigt die Level deiner Jobs an.`
`[10:07:43 INFO]: /jobs points [playername] - Shows how much points player have.`

Jobs Version 3.8.0
Any suggestions?

**Comment by Staartvin** [comment]
Did you install Statz, if so, what version?

**Comment by Imothep80** [comment]
Yes, Version 1.4

**Comment by Staartvin** [comment]
What version of Jobs are you running?

**Comment by Imothep80** [comment]
now 3.8.2
