### ISSUE TITLE
Cannot Remove Test Path

### ISSUE THREAD

**Issue by cjburkey01** [Staartvin/Autorank-2#452]
When editing the Paths.yml, removing the Test path causes it to be readded upon the next loading of the plugin.

**Comment by Staartvin** [comment]
I cannot seem to reproduce this but: when I remove it, it doesn't come back?

**Comment by cjburkey01** [comment]
I'll get the Paths.yml tomorrow, it's late and my VNC viewer appears to be broken.

**Comment by Killertom63** [comment]
Second this bug. 

Test does always come back.

**Comment by Imothep80** [comment]
I got the same bug.
If you edit the Path.yml during the Server is running and reload this, the plugin seems to rewrite this. I can reproduce this every time. This is not an permissions Problem.

**Comment by Staartvin** [comment]
What happens if you stop the server, remove the test path and restart? Does it reappear?

**Comment by Imothep80** [comment]
> What happens if you stop the server, remove the test path and restart? Does it reappear?

After this precedure he accepts the new data. I see that is create a file called: Path.yml.swap (or something else)

**Comment by Staartvin** [comment]
But the Paths.yml doesn't contain the test path anymore?

**Comment by Imothep80** [comment]
right. because he delete the swap file after stopping Server. "Test Path" is just an symptom not the trigger. when you edit your "new" file you get the same Problem again, until you stop your Server and replace/edit the file.
