### ISSUE TITLE
Can't automatically assign path, or use /ar choose

### ISSUE THREAD

**Issue by SnowyMar** [Staartvin/Autorank-2#453]
Autorank wont automatically choose a path for my player. 
 This is my path config

FNG:
    prerequisites:
        in group: 
            value: FNG
    requirements:
        time: 
            value: 3m
    results:
        command:
            value: "pex user &p group set Private"
    options:
        infinite pathing: false
        auto choose: true
        Priority: 10 
Private:
    prerequisites:
        in group: 
            value: Private
    requirements:
        time: 
            value: 7m
    results:
        command:
            value: "pex user &p group set Coroporal"
    options:
        infinite pathing: false
        auto choose: true
        priority: 9
Coroporal:
    prerequisites:
        in group: 
            value: Coroporal
    requirements:
        time: 
            value: 1h
    results:
        command:
            value: "pex user &p group set RarestPepe"
    options:
        infinite pathing: false
        auto choose: true
        Priority: 8

**Comment by SnowyMar** [comment]
/ar check also does not allow me to see the time played, it goes straight into /ar view and etc.

**Comment by SnowyMar** [comment]
lastly, If I wanted to do /ar choose, it wouldnt work. It would say "An internal error occured while attempting to perform this command" with or without setting auto choose to true or false.

**Comment by SnowyMar** [comment]
#############################################################################
#                                                                           #
#                   Autorank Settings                                       #
#                                                                           #
#   This config is used to configure Autorank. The other configs provide    #
#   a way to configure the rank system. This config is for configuring the  #
#   the options Autorank has to offer you                                   #
#                                                                           #
#############################################################################

afk integration: true
# If a compatible AFK plugin is found Autorank will not count online time for AFK players
# This option is always on when using the SimpleConfig
# Currently supports: Essentials, RoyalCommands and UltimateCore
# Autorank automatically chooses what plugin to use for AFK integration.

use partial completion: false 
# When this is true, players can use /ar complete # to complete a requirement at any moment they like.
# When this is false, players will only be able to /ar check and check for all requirements at one time. They would need to have all requirements at that moment.

interval check: 5
# This is the interval between checks of Autorank (in minutes).
# Lowering this number will increase accuracy but will also increase server lag.

use time of: Autorank
# You can specify what time plugin Autorank will use to calculate the time that a player has played.
# This only changes the local time. 
# A list to choose from:
# 1. Autorank
# 2. Stats
# 3. OnTime
# 4. Statz
# If no valid time plugin was found, it defaults to Autorank

leaderboard layout: '&6&r | &b&p - &7&d %day%, &h %hour% and &m %minute%.'
leaderboard length: 5
# changes the appearance of the /ar leaderboard command
# &r : Ranking in the leaderboard
# &p : Player name
# &m : Minutes (with full days and full hours not counted)
# &h : Hours (with full days not counted)
# &d : Days
# &tm : Total amount of minutes
# &th : Total amount of hours

check command layout: "&p has played for &time and is on path ''&path''. Requirements to be ranked up: &reqs"
# Changes the layout of the /ar check command.
# &p : Player name
# &time : time in hours, minutes and seconds
# &path : Path the player has chosen.
# &reqs : a list of all requirements

sql:
    enabled: false
    hostname: localhost:3306
    username: root
    password: ''
    database: minecraft
    table: autorank
# All these options are for configuring your MySQL database with Autorank.
# Hostname has to include a port, but doesn't have to be port 3306.

auto-updater:
    check-for-new-versions: false
#   When check-for-new-versions is true, Autorank will tell you when a new version is available.

advanced dependency output: false
# If this is true, Autorank will tell you in the console what dependencies were found and which ones weren't found.
# Turn this off to remove the console spam from Autorank about dependencies.
# This feature can be useful when Autorank can't find your dependency, but you have it installed.

show help command based on permission: true
# If this is true, the /ar help command will only show the available commands for a certain player.
# If a player doesn't have the permission to perform the command, it will not show that command on the help page.

use debug: false
# Only set this to true when you want to debug Autorank
# When this is true, Autorank will spit out debug messages

show warnings: true
# Whether Autorank has to show critical warnings.
# Leave this set to true. You can only change it to false when Autorank is giving you false warnings.

use primary group for vault: true
# Most permission plugins will only work properly with Autorank if you let it only get the primary group.
# Some need to get all the groups however. You probably only need to change this when a dev tells you to.

broadcast resetting of data files: true
# Autorank keeps track of amount of time played per day, week and month.
# When a new day, week or month starts, Autorank will reset the times of all players (except the total time, this is always preserved).
# If this value is set to true, Autorank will broadcast to all players when their data gets reset.

use global time in leaderboard: false
# By default, Autorank will use the local time of a player when for the leaderboard. When this is set to true,
# /ar leaderboard will be sorted on the global time of a player (provided that it exists).

disable automatic path checking: false
# By default, Autorank will check whether a player meets all requirements for its path every x minutes.
# If you want to disable this feature and let players manually check whether they completed all requirements, set this to true.

automatically archive old data: true
# This is turned on by default. When this is set to true, Autorank will archive data of players that haven't seen been online for some time.

**Comment by Killertom63** [comment]
I have pretty much the same as you. Player plays for X amount of time, then is promoted. Then plays for X amount of more time, then is promoted. I did this like the following -

`Apprentice:
  prerequisites:
    in group:
      value: Apprentice
  requirements:
    global time: 2d
  results:
    rank change: Wizard
    command: say &p just got a promotion to Wizard!
    command2: pp user &p setrank Wizard
    message: to your activity, you are now a Wizard!
  options:
    auto choose: true
    infinite pathing: true`

However. Now I have the issue that every time they come on the server it says Apprentice Path selected. Dev needs to make those messages a toggle. It seems the dev had different intentions to how he wanted the plugin to go. As apposed to the way most people actually wish to use it. :(

**Comment by Staartvin** [comment]
@Killertom63
Are you running Autorank 4.0.2? If so, remove the rank change result and set infinite pathing to false, that's why Autorank keeps selecting the rank for you! You told it to do so.

**Comment by Killertom63** [comment]
Thanks, I'll test that out.

**Comment by SnowyMar** [comment]
thank you =D

**Comment by SnowyMar** [comment]
![image](https://cloud.githubusercontent.com/assets/25497518/22567372/a7fe3982-e95d-11e6-92bb-5ccf65aa0634.png)

**Comment by Staartvin** [comment]
Are you using /ar  choose?

**Comment by SnowyMar** [comment]
Does autorank not see my in game ranks? I've removed infinite path.  
![image](https://cloud.githubusercontent.com/assets/25497518/22567449/e676da34-e95d-11e6-95e5-69b87a3d25e4.png)

**Comment by SnowyMar** [comment]
![image](https://cloud.githubusercontent.com/assets/25497518/22568301/4f7c41d8-e961-11e6-91e0-4d19c87682a0.png)

also it looks like the leaderboard does not count actual time being played, I added 8 mins to it.

**Comment by SnowyMar** [comment]
I tried using /ar choose it says "an internal error occured while attempting to perform this command. Although I don't want to have to use /ar choose (want it to work automatically, I have auto choose:true. My paths come up fine with /ar view list. But it does not actually rank up with my players time.

**Comment by Killertom63** [comment]
Give me your updated paths file please?

**Comment by SnowyMar** [comment]
FNG:
    prerequisites:
        in group: 
            value: FNG
    requirements:
        time: 
            value: 12h
    results:
        command:
            value: "pex user &p group add Private"
    options:
        auto choose: true
Private:
    prerequisites:
        in group: 
            value: Private
    requirements:
        time: 
            value: 1d
    results:
        command:
            value: "pex user &p group add Corporal"
    options:
        auto choose: true
Corporal:
    prerequisites:
        in group: 
            value: Corporal
    requirements:
        time: 
            value: 2d
    results:
        command:
            value: "pex user &p group add SadPepe"
    options:
        auto choose: true
