### ISSUE TITLE
Play time resets

### ISSUE THREAD

**Issue by Killertom63** [Staartvin/Autorank-2#454]
I use your plugin so that I can auto rank up my players after X amount of time. I'm on bungee so I'm using global time for this. However, quite often and not the time will reset. Now I notice this because my scoreboard shows time played. I've lived with this issue for ages now, and it's just tedious to go in and check everyones time on each server, which I cannot do all the time. 

On top of that, is there a way to turn off "You have automatically been assigned to the path "Wizard" as it comes up every time someone changes server.

**Comment by Staartvin** [comment]
If you're  using a global time setup, Autorank will not remember the path chosen on other  servers, so it will rank the player to the Wizard path if he is not on it on that server. Makes sense, right?

**Comment by Killertom63** [comment]
But can you still make it so that message doesn't come up. Anyways, that's hardly my main issue. My main issue is that peoples times reset. And have been doing so for months.
