### ISSUE TITLE
<AUTORANK> Warning: Permissions group 'guest' should be 'Guest'

### ISSUE THREAD

**Issue by sleepingcandy** [Staartvin/Autorank-2#455]
![image](https://cloud.githubusercontent.com/assets/10253610/22583811/c8462dc4-e9e6-11e6-8d96-78566975ce80.png)

![image](https://cloud.githubusercontent.com/assets/10253610/22583786/a58a2164-e9e6-11e6-8d95-6d66b6b90f16.png)

![image](https://cloud.githubusercontent.com/assets/10253610/22583789/a922f1d4-e9e6-11e6-9f47-a2610ea02c7e.png)

???

**Comment by Staartvin** [comment]
This means you have a rank up for a group called 'guest',  but there is a permission group that is called 'Guest'. Replace all the guest (with lowercase) to Guest (first letter is uppercase) in your advanced config.

**Comment by sleepingcandy** [comment]
The 3rd screenshot is the advanced config. all of the words 'guest' is with an uppercase G

**Comment by Staartvin** [comment]
Try setting the group in your permission plugin to lowercase. Some permission plugins return their groups all in lowercase. (or update to Autorank 4)

**Comment by sleepingcandy** [comment]
I just got this,
![image](https://cloud.githubusercontent.com/assets/10253610/22585314/1d398558-e9ef-11e6-9836-f03ea8305c89.png)

**Comment by Staartvin** [comment]
You're member group should also be specified in the permissions plugin ;)

**Comment by sleepingcandy** [comment]
It is in the 2nd screenshot, right?

**Comment by Staartvin** [comment]
Can you provide me with your fresh advanced config and permissions config?

**Comment by sleepingcandy** [comment]
Group Manager Permissions: http://pastebin.com/Si5nJZWt

Advanced Config: http://pastebin.com/HQG0aHJD

These are the configurations I'm running right now, still need to work on them for the server.

**Comment by Staartvin** [comment]
Try to lowercase Member and Vip in your permissions file as well.

**Comment by sleepingcandy** [comment]
This is what I got:

![image](https://cloud.githubusercontent.com/assets/10253610/22590256/2fc3c8d4-ea06-11e6-885a-edfc9d5a803b.png)

**Comment by Staartvin** [comment]
So you put vip and member to lowercase in your permissions file and restarted the server?

**Comment by Staartvin** [comment]
I don't see a Vip group in your permissions file:O

**Comment by sleepingcandy** [comment]
I'm not going to be using VIP, I'm using B1, B2, B3, etc. so i need to change that.

**Comment by sleepingcandy** [comment]
I changed the names of the ranks to what I wanted, and this happened:

![image](https://cloud.githubusercontent.com/assets/10253610/22595323/eb52a742-ea1e-11e6-8db5-a1a6bd5a7a7a.png)

Even though in my permissions file, 'Guest' is with a capital.

![image](https://cloud.githubusercontent.com/assets/10253610/22595351/117e21d0-ea1f-11e6-919f-b8dda6c1419f.png)

**Comment by Staartvin** [comment]
In your permissions file, all the ranks that appear in anywhere in the AdvancedConfig will need to be lowercased! So Guest must be lowercased in your permissions file (as it is used in Autorank's AdvancedConfig.yml).

**Comment by sleepingcandy** [comment]
would it be easier if I kept all the ranks lowercase?

**Comment by Staartvin** [comment]
Yes, definitely!

**Comment by sleepingcandy** [comment]
I did that, and now I have this:
![image](https://cloud.githubusercontent.com/assets/10253610/22596131/464e8faa-ea22-11e6-92b8-db174a988eaa.png)

**Comment by Staartvin** [comment]
What, that doesn't make sense. Please contact me on Skype (Staartvin) and we can talk a bit quicker!

**Comment by sleepingcandy** [comment]
Just added you.

**Comment by Staartvin** [comment]
Solved over Skype!
