### ISSUE TITLE
SUGGESTION: Allow AR to choose to use AdvancedConfig or Paths

### ISSUE THREAD

**Issue by nathan93** [Staartvin/Autorank-2#459]
Would it be possible to put out a version with an option in the Settings file that allows administrators to choose which file Autorank uses to handle ranking and requirements? Something like this:

`#Set the file for Autorank to use as its configuration for handling rank-ups and requirements.`
`#Options: Paths.yml, AdvancedConfig.yml, SimpleConfig.yml`
`set-config: AdvancedConfig.yml`

I feel the new version 4 with the paths configuration is highly inconvenient and overly complicated, I can't even get it working properly on my server even after reading the wiki. I much prefer the Advanced Config, however, I know it's not an option to revert the plugin back before version 4, so I'm suggesting that you allow administrators to choose their most prefered config file so to make the plugin easier and more user friendly.

**Comment by Staartvin** [comment]
Unfortunately, Autorank 4 is completely built around the Paths file and does not allow to insert _data_ from another format. It's unfortunate that you do not understand the Paths file, but it is the way to go. Did you take a look at the updated tutorial [here](https://github.com/Staartvin/Autorank-2/wiki/Convert-SimpleConfig.yml-to-Paths.yml)? 

I would gladly help you.
