### ISSUE TITLE
Reload Exception

### ISSUE THREAD

**Issue by zerafox** [Staartvin/Autorank-2#461]
I'm not sure what's wrong this time, my parsing is correct and I made sure that none of the names are the same.
When I run command /ar reload I get this error in console:

04.02 19:35:21 [Server] INFO ... 8 more
04.02 19:35:21 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[custom18.jar:git-Spigot-4741400-a1d3777]
04.02 19:35:21 [Server] INFO at me.armar.plugins.autorank.commands.manager.CommandsManager.onCommand(CommandsManager.java:169) ~[?:?]
04.02 19:35:21 [Server] INFO at me.armar.plugins.autorank.commands.ReloadCommand.onCommand(ReloadCommand.java:41) ~[?:?]
04.02 19:35:21 [Server] INFO at me.armar.plugins.autorank.pathbuilder.PathManager.initialiseFromConfigs(PathManager.java:154) ~[?:?]
04.02 19:35:21 [Server] INFO at me.armar.plugins.autorank.pathbuilder.PathBuilder.initialisePaths(PathBuilder.java:223) ~[?:?]
04.02 19:35:21 [Server] INFO at me.armar.plugins.autorank.config.PathsConfig.getPrerequisites(PathsConfig.java:180) ~[?:?]
04.02 19:35:21 [Server] INFO Caused by: java.lang.NullPointerException
04.02 19:35:21 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
04.02 19:35:21 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [custom18.jar:git-Spigot-4741400-a1d3777]
04.02 19:35:21 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [custom18.jar:git-Spigot-4741400-a1d3777]
04.02 19:35:21 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:400) [custom18.jar:git-Spigot-4741400-a1d3777]
04.02 19:35:21 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:437) [custom18.jar:git-Spigot-4741400-a1d3777]
04.02 19:35:21 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:636) [custom18.jar:git-Spigot-4741400-a1d3777]
04.02 19:35:21 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[custom18.jar:git-Spigot-4741400-a1d3777]
04.02 19:35:21 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[custom18.jar:git-Spigot-4741400-a1d3777]
04.02 19:35:21 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[custom18.jar:git-Spigot-4741400-a1d3777]
04.02 19:35:21 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'ar' in plugin Autorank v4.0.2
04.02 19:35:21 [Server] WARN Unexpected exception while parsing console command "ar reload"

**Comment by zerafox** [comment]
I feel silly, after posting this I realized that I had this in the file:
```
ca:
  requirements:
    total time: 14d
    gamemode: 0
  results:
    command2: lp user &p switchprimarygroup ca
    message: Congratulations, you were given Community Assitant!
  options:
    display name: Staff Path
    auto choose: false
    show based on prerequisites: true
```
How can it show based on non-existant prereq's? Haha!
I've fixed it now:
`ca:
  prerequisites:
    total time: 14d
  requirements:
    total time: 14d
    gamemode: 0
  results:
    command2: lp user &p switchprimarygroup ca
    message: Congratulations, you were given Community Assitant!
  options:
    display name: Staff Path
    auto choose: false
    show based on prerequisites: true`

**Comment by Staartvin** [comment]
Great you fixed it yourself!
