### ISSUE TITLE
Players Ranking Early

### ISSUE THREAD

**Issue by zerafox** [Staartvin/Autorank-2#464]
I'm having a serious problem where AR isn't following it's own settings.
I have players who are supposed to rank at 1d 12hrs, but they're ranking at 1d.

I myself just ranked at 1d 10m for a Rank that requires 2d.

And the only way I can see to fix this 'completely' is to edit the playerdata.yml so AR doesn't think they've already completed the path when I have to push them back a permission rank again.

What is going on here?
Is it a wrong setup?
```
Rank3:
  prerequisites:
    permission:
      value: rank.3
  requirements:
    time:
      value: 1d12h
      options:
        auto complete: true
    gamemode: 0
  results:
    command:
      value: lp user &p promote player
    message:
      value: Congratulations, you were promoted to Beginner!
  options:
    display name: Beginner
    auto choose: true
    show based on prerequisites: true
Rank4:
  prerequisites:
    permission:
      value: rank.4
  requirements:
    time:
      value: 2d
      options:
        auto complete: true
    gamemode: 0
  results:
    command:
      value: lp user &p promote player
    message:
      value: Congratulations, you were promoted!
  options:
    display name: Player Path 4
    auto choose: true
    show based on prerequisites: true
```

This could break my server if it's pushing people through paths too quickly..

**Comment by zerafox** [comment]
When I use /ar check
I'm told my total playtime is 1 day, 14 hours, and 5 minutes.
But AR said I met "Rank4" requirements and completed that path for me..
It did the same for another player who has 1 day, 1 hour, 55 minutes. They were pushed to "Rank4" but didn't complete it..

It's not because of some other plugin.. Atleast not something requiring statz, because I didn't install that. :(
I need a solution for this.. It just pushed me through a path again after I edited the files to correct it.

**Comment by ironik42** [comment]
I'm having the same issue where the time requirement to advance to the second path is already completed by players that are brand new(never played on the server before) and /ar check shows this. I mistakenly banned someone for hacking before I discovered that this was an actual issue with the plugin. I've dropped a line on the Discord channel too, but it's eerily quiet there...
