### ISSUE TITLE
Having a difficult time understanding the new paths configuration.

### ISSUE THREAD

**Issue by Tundral** [Staartvin/Autorank-2#466]
So I'm moving from AR v3.8.4 to the latest version and the whole system seems to have been changed. 

So on version 3 I used to have a setup where players would start as Newbie and then after doing a certain amount of tasks determined in the advancedconfig.yml they would rank up, until they were the highest rank and couldn't rank up anymore. 

How can I do this on AR 4.x Does each "path" correlate to one rank change in the old advancedconfig.yml. So would I have to just make it so that there's "paths" from each rank to the next so that they're always auto-chosen once the last one has been finished.

I've attached my advancedconfig as a txt file if it helps understand
[AdvancedConfig.txt](https://github.com/Staartvin/Autorank-2/files/763638/AdvancedConfig.txt)

**Comment by Staartvin** [comment]
I've written extensive tutorials on the wiki of Autorank, but this is the gist of it:

A path can be used to perform certain results when requirements are set up. For example, you can rank a player from rank A to rank B when he is in rank A, has walked 1000 blocks and played for at least 10 hours. 

For more info, please use the wiki!

**Comment by Tundral** [comment]
So essentially it works like I thought, or am I missing something?

**Comment by Staartvin** [comment]
Yes, I think you are on the  right  track. Try playing around with the paths file and I can provide you with some feedback.

**Comment by zoredache** [comment]
> I've written extensive tutorials on the wiki of Autorank, 

I don't think it is as extensive as you believe it is.  For example, you give no examples at all in [this page](https://github.com/Staartvin/Autorank-2/wiki/How-to-configure-the-Paths.yml-file%3F) for any results other then giving out money.  Is there some listing of all the possible results a person can use?  In a converted file I see a `command` as one, is there a way to trigger off a series of commands?  Can you accept an array under the `commands` node?  We really need you to provide a lot more documentation and variety in your examples.
