### ISSUE TITLE
Bukkit md5 chat color

### ISSUE THREAD

**Issue by jonassm** [Staartvin/Autorank-2#470]
Hi,

I'm having an issue when i run any /ar command, and in my bug report it states:

 Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor

**Comment by Staartvin** [comment]
What version of Autorank are you using? This should have been fixed in the latest beta.

**Comment by jonassm** [comment]
Latest beta, i switched to Spigot though

Sendt fra min iPhone

Den 11. feb. 2017 kl. 00.02 skrev Staartvin <notifications@github.com<mailto:notifications@github.com>>:


What version of Autorank are you using? This should have been fixed in the latest beta.

-

**Comment by Staartvin** [comment]
Well that should fix it.
