### ISSUE TITLE
Just installed, internal error when using /ar reload

### ISSUE THREAD

**Issue by Cboxhero** [Staartvin/Autorank-2#471]
Freshly installed AutoRank 4.0.2 on a 1.11.2 server. After installing it, starting the server, stopping and starting the server again, with no changes to autorank, there is an internal error when using /ar reload.

**Comment by Staartvin** [comment]
First, never use /ar reload. I'll disable that command as it is hell. Then stop the server, remove the test path and restart your server.

**Comment by Cboxhero** [comment]
Oh, awesome! Good to know after fiddling with this problem for close to a week. Haha
Now, I'm just having a problem with the paths working at all.

**Comment by Staartvin** [comment]
Can you provide your Paths file and what problems you are getting?

**Comment by Cboxhero** [comment]
Paths file: http://pastebin.com/tf970Y3W
It's saying in game that there are no paths to choose when using /ar view list.
And when I use /ar check I get "Cboxhero has played for 22 hours and 50 minutes and currently has no path. There are no paths left to choose." Even though I am 'scrub' rank in pex.

**Comment by Staartvin** [comment]
Could you reset your playerdata file? (playerdata.yml)

**Comment by Cboxhero** [comment]
Even after deleting everything in playerdata.yml and restarting server, it's doing the same thing.

**Comment by Staartvin** [comment]
Are you still having this problem with Autorank 4.0.4?

**Comment by Cboxhero** [comment]
No I am not. Everything seems to be working now.
