### ISSUE TITLE
Request,

### ISSUE THREAD

**Issue by DutchUser** [Staartvin/Autorank-2#472]
Can you please add an command where players can see how much they as example allready voted?

Example: You need to vote <time> more. (<times allready votes>)

Thanks! :)

**Comment by Staartvin** [comment]
You can already do this with **/ar track**!

**Comment by DutchUser** [comment]
If i try he just say "Invalid format, use /ar track #."

If i do that he say "# is not a valid number!"

**Comment by DutchUser** [comment]
Nevermind i see now.

**Comment by DutchUser** [comment]
No. I mean that players can see how much they voted or played.

Not what they still need. Just the totaal play and vote times.
