### ISSUE TITLE
After reading and configuring paths (High Priority) You are using a 'rank change' result in path 'Test1', but that result doesn't exist!

### ISSUE THREAD

**Issue by kingofthecogs** [Staartvin/Autorank-2#474]
I don't have a Test1 rank in the paths file at all, I've reinstalled this completely and set it up and the error still persists:

thrall:
  prerequisites:
    in group:
      value: thrall
  requirements:
    money: 10000
    mobs killed: 200
    time: 4h
  results:
    rank change: viking
    command: broadcast &p has just completed path 'Viking'!
    command2: give &p 1 100
    message: Congratulations, you completed the 'Viking' path!
  options:
    display name: The path to Viking!

What is it doing? there are no error's in console either.

**Comment by Staartvin** [comment]
Stop the server and remove the test path (it is still in your Paths.yml). Then restart your server.

**Comment by kingofthecogs** [comment]
Have done, it's changed to the rank now, I'm studying the examples as I write this so hopefully should now work. It seems more effective to edit the file live and reloading

**Comment by Staartvin** [comment]
Reloading is not recommended as it can cause major bugs that Autorank does not like. Ideally, you turn off your server, then configure your Paths and restart to test. Perhaps using a test server so you don't have to constantly restart the production server.

**Comment by kingofthecogs** [comment]
Yeah I've just found that out haha, it's stable without including "options" seems to be the issue now, does I was setting this up as per example:

    options:
        display name: "Becoming a Veteran"
        auto choose: true

but does it work like the rest of the config eg:

    options:
        display name: 
                value: "Becoming a Veteran"
        auto choose: 
                value: true

?

**Comment by Staartvin** [comment]
The options don't have a value parameter, so the former is correct.

**Comment by kingofthecogs** [comment]
I'll work on it,

Thanks for your help :-)
