### ISSUE TITLE
"You are using rank change ... but doesn't exist!"

### ISSUE THREAD

**Issue by mewtrix** [Staartvin/Autorank-2#475]
I am at an absolute loss. I keep getting this message http://i.imgur.com/IhQZyKZ.png no matter what I do with my Paths.yml (http://codejaw.com/yxdoy). I have tried Copying and pasting my permissions directly into the paths file, putting the entire permissions file (http://codejaw.com/2p0qp7w) in the directory, etc. 
I am probably just an idiot and can't correctly import my permissions file, but I digress.
I am using PEx and Autorank 4.0.3

Thanks for any help

**Comment by Raldeme** [comment]
Hi I've used autorank before using the advanced config, but trying it now I am also having the same issue.
I believe that it's because the Result; rank change    is not registering, I am very new to java coding so I dont know how it could be fixed.

**Comment by SharkDice** [comment]
I'm having the exact same problem. Word for word. I've even tried deleting the config and refreshing it.

**Comment by mewtrix** [comment]
Okay so an update on the situation.
I looked further into it and it turns out pex just doesn't like the rank up variable provided by autorank. It would rather give the command to promote than anything. However, doing so somehow negates any form of an automatic ladder somehow and requires players to do /ar choose, which can be burdensome. I haven't tested if this works on its own or if the ladder itself works on its own. However, yet again, changing it to a command result with the pex &p promote command does negate this error message.

**Comment by Raldeme** [comment]
what i dont understand is, it worked in the older version with pex :/ 
thank you for responding with a temporary solution, can you also give a way to demote the same way as the derankable function would?

**Comment by mewtrix** [comment]
I think the problem is the path.yml file itself. The advanced config and simple config kind of mashed together to make a very moldable hybrid that allows a good deal of customization, but in return, causes some inconsistancies with simple setup if not with the "desirable" plugins (i.e. using pex instead of another permissions plugin)

What do you mean by the derankable function? In autorank? You can essentially do the same process but with command: pex &p demote

Unfortunately, with either of these ways, the paths plugin may/may not require users to manually choose these routes via /ar choose. I'm not sure, because as I have said before, I haven't tested it yet myself. I haven't had anyone on my server for that long and I lack the will for effort to go through the extensive process of removing myself from the ranking system or anything of the sort. However, all I know is that /ar choose has all the paths individually named instead of having something like a "group ladder" for a lack of a better word, and the path would be like "default -> member1-> member2" under an umbrella named "defaultpath" or something of the sort.

I hope this helps at all

**Comment by Staartvin** [comment]
Autorank does not support 'rank change' results anymore, as specified in the message. You should replace it with a 'command' result that sets the permission group of that player.

**Comment by Nickfish011** [comment]
Any idea what command I would have to use then? I see alot of people using pex so does that mean I have to install pex to use the plugin? I use groupmanager.

**Comment by mewtrix** [comment]
Try doing manuadd **&b** rank. I don't think it likes the @ sign.

**Comment by Nickfish011** [comment]
Thanks alot bro I got it to work! However I did &p instead of &b

**Comment by mewtrix** [comment]
shoot, messed that up, hahaha
good to hear it worked though

**Comment by Nickfish011** [comment]
You're good lol.. I'm confused why it would be & instead of @ but for now that's the last thing I want to worry about haha

**Comment by Staartvin** [comment]
Good that you got it to work out in the end. Closing this :)
