### ISSUE TITLE
Could not set up requirement 'time'...

### ISSUE THREAD

**Issue by Redstorm3265** [Staartvin/Autorank-2#477]
Server version: spigot 1.11.2
plugin version:  4.0.3

Error: http://pastebin.com/xQcfU7mn
Settings: http://pastebin.com/06jugZgE
Paths: http://pastebin.com/v4Z99hhq

Regardless of what format of time I use, it refuses to see it as a valid form of requirement.

**Comment by Staartvin** [comment]
You cannot use 's' as a time unit, only 'm' (minutes), 'h' (hours) and 'd' (days) are allowed.
