### ISSUE TITLE
AFK detecting seems to not be working

### ISSUE THREAD

**Issue by jonassm** [Staartvin/Autorank-2#478]
Hi,

I have the default config in terms of checking AFK and so on, however, i've had a friend stand afk for 3+ hours, and he's still gatherting time.

Running latest spigot and latest autorank beta.

**Comment by Staartvin** [comment]
What AFK plugin are you using?

**Comment by jonassm** [comment]
Autorank integrated.

**Comment by Staartvin** [comment]
Autorank can't detect on its own whether a player is AFK. You need an AFK checker like Essentials to check when a player is AFK.

**Comment by dutchy1001** [comment]
I use EssentialsX for the AFK and it still doesn't work for me either
![2017-03-02_07 51 07](https://cloud.githubusercontent.com/assets/5569980/23497916/345d8c00-ff1d-11e6-9025-0022adee1223.png)
This 20 minutes in AFK
Using the following
- Autorank v4.0.4
- EssentialsX [build 468](https://ci.drtshock.net/job/essentialsx/)
- Spigot 1.11.2

I do not use Statz, mainly because the AFK setting is already in the Autorank config which I then presume is handled by Autorank.

**Comment by Staartvin** [comment]
The AFK only works when Statz is installed. Statz is the bridge between any connection of Autorank and a third party plugin.

**Comment by dutchy1001** [comment]
So what is the AFK setting in the Autorank config do?

**Comment by Staartvin** [comment]
With that setting you can toggle whether you want Autorank to use AFK integration (if available).

**Comment by dutchy1001** [comment]
With Staz it's working.
I presume the documentation needs altering to make it more clear that Statz is also needed for AFK as, like I said before, with the node in the Autorank config many will presume it's intergrated with Autorank.

Atleast now we know this issue could be closed if the OP acknowledge the fix.

**Comment by jonassm** [comment]
You Can close. Cant use computer atm.

Sendt fra min iPhone

Den 2. mar. 2017 kl. 13.43 skrev dutchy1001 <notifications@github.com<mailto:notifications@github.com>>:


With Staz it's working.
I presume the documentation needs altering to make it more clear that Statz is also needed for AFK as, like I said before, with the node in the Autorank config many will presume it's intergrated with Autorank.

Atleast now we know this issue could be closed if the OP acknowledge the fix.

**Comment by Staartvin** [comment]
I think it's good to use write that down somewhere, yes.
