### ISSUE TITLE
Converter from 3.8.5 at 4.0.5.

### ISSUE THREAD

**Issue by TheIntelloBox** [Staartvin/Autorank-2#480]
Hello !

I used AutoRank 3.8.5 but the latest update (V.4.0.5) change the system. Now the advanced config does nothing, and I must do again my ranks in the paths.yml. 
So could you add a converter for the AdvancedConfig.yml for the paths.yml ?

Thanks ! :)

**Comment by Staartvin** [comment]
Good news, there already is one! Try '/ar convert AdvancedConfig'.

**Comment by TheIntelloBox** [comment]
Nice but : 
"You are using a 'rank change' result in path "Citoyen", but that result doesn't exist.

How can I fix it ?

**Comment by Staartvin** [comment]
Remove the rank change result and replace it with a command result that sets the permission group of  a player.

**Comment by TheIntelloBox** [comment]
How do I put multiple commands ?

**Comment by Staartvin** [comment]
'command1:',  'command2:' and 'command3'.

**Comment by TheIntelloBox** [comment]
How do I use the old /ar check ?

**Comment by Staartvin** [comment]
What do you mean?

**Comment by TheIntelloBox** [comment]
With the old /ar check pseudo we could see the next rank with the time, but now we must do /ar check Owner, /ar check Default, etc. Do you understand ?

**Comment by Staartvin** [comment]
No, you can still do /ar check. That's not changed ;)

**Comment by TheIntelloBox** [comment]
No it says that I must do /ar choose, etc, it's so difficult.

**Comment by Staartvin** [comment]
Add auto choose: true option to the path! See the wiki for more info about that.

**Comment by TheIntelloBox** [comment]
I added this, but this says me do /ar choose, etc.

**Comment by TheIntelloBox** [comment]
I added this, but this says me do /ar choose, etc.

**Comment by Staartvin** [comment]
Closed due to inactivity.
