### ISSUE TITLE
Internal Error with /ar view list

### ISSUE THREAD

**Issue by SloppyJalopy** [Staartvin/Autorank-2#484]
Server Log: http://pastebin.com/rRyFazdL
Path.yml file: http://pastebin.com/bF8Gnhau

Playing around with Auto Ranker, Trying to get it to work when this error came up.

**Comment by Staartvin** [comment]
Could you stopping your server, removing the whitespace lines and restarting it too see if that fixes stuff?

**Comment by SloppyJalopy** [comment]
Getting rid of "show based on prerequisites: true" has fixed the problem, but now it shows all my ranks which is a problem.

**Comment by Staartvin** [comment]
What version of Autorank are you using? The 'show based on prerequisites' should not affect your paths.yml in any meaningful way.

**Comment by Staartvin** [comment]
Closed due to inactivity.
