### ISSUE TITLE
Autorank 3.8.5.1 and 4.0.5 EssentialsX AFK Integration

### ISSUE THREAD

**Issue by FrankHG** [Staartvin/Autorank-2#485]
Hi .. Im sorry, but im back :-)
i was just getting my stuff together for an upgrade, and i thought i would give 4.0.5 a try.. 
4.0.5 complained about statz not beeing installed and not beeing able to do AFK integration, I was running EssentialsX B468 later i tried B370 as in the wiki on GitHub. No errors .. just no AFK integration.
I dont want to use Statz as i only use playtime in ranking.
EDIT: Ive also tried this with 3.8.5.1 which dont give me any errors on statz and AFK integration.
could you help me?

**Comment by Staartvin** [comment]
Autorank needs Statz when you want to use AFK integration. That's why it is complaining. You can disable the tracking of Statz in the config, so it becomes a lightweight plugin.

**Comment by FrankHG** [comment]
Thanks for the quick reply :-)
