### ISSUE TITLE
/ar check causes an internal error

### ISSUE THREAD

**Issue by mcawsome2** [Staartvin/Autorank-2#487]
Console Log- http://pastebin.com/vu4UYvHh
Paths.yml- http://pastebin.com/HS3L2MEe

Everytime I do /ar check it give the information on how long you played for but it doesn't give you the requirements need. Instead it says "An internal error occurred while attempting this command" 

http://imgur.com/a/U3Lwe

**Comment by Staartvin** [comment]
It seems your SQLite is doing some strange things. Statz can't initialize the SQLite database properly and then Autorank fails accordingly
