### ISSUE TITLE
Autorank not completing jobs level as DONE

### ISSUE THREAD

**Issue by G4MEON** [Staartvin/Autorank-2#489]
In my path I have a requirement that the player needs level 20 in woodcutter.  Players are going past level 20 and autorank isnt completing the requirement as done and ranking them up.

**Comment by Staartvin** [comment]
What requirement is it?

**Comment by G4MEON** [comment]
The requirement is job level 20 in woodcutter.

**Comment by Staartvin** [comment]
Can you provide your paths.yml file?

**Comment by G4MEON** [comment]
Attached is the path I have created so far.  As well as the jobs level
completion not being checked off as done, I have a give item of an
enchanted diamond axe for completion of Lumberjack that is giving players
glass instead.  When I use the same command in game or in console it gives
the player the appropriate axe.

**Comment by Staartvin** [comment]
I don't see the paths file. Could you use pastebin.com?
