### ISSUE TITLE
[Bug] Moving a player to a differnet rank, they are still stuck on their "path"

### ISSUE THREAD

**Issue by FrozenBeard** [Staartvin/Autorank-2#490]
This is an infuriating bug, if you move a user to a different rank, say a donator, and they have already accepted the prerequisites that checks their rank, even after they donate they will be downgraded!

As an example my my server, a normal player is ranking from Cadet to sailor, so they do the prerequisites which checks they are Cadet first, so they are accepted, now they decide to donate half way through this for a higher up rank. The ranking carrys on in the background even though they are a completely different rank now and when they reach it they get demoted as it thinks they are trying to rank still even though they are a higher up rank.

**Comment by Staartvin** [comment]
Thanks for mentioning this. I will add a system that will automatically check if a player switched ranks and then remove the path.
