### ISSUE TITLE
[Suggestion] Better antiafk

### ISSUE THREAD

**Issue by xion87** [Staartvin/Autorank-2#491]
I would like autorank to don't count the time if player will stay in same X coordinate position or in same chunk for much time, it will help to fight player that use antiafk thing like this: https://i.ytimg.com/vi/4yunvDBDmfU/maxresdefault.jpg

**Comment by Staartvin** [comment]
You should a plugin like afkTerminator that determines when a player is AFK (also works with AFK fountains).

**Comment by xion87** [comment]
Oh nice plugin i never see that ^^
