### ISSUE TITLE
Not all Path Completion messages received when multiple players qualify

### ISSUE THREAD

**Issue by obzidi4n** [Staartvin/Autorank-2#492]
Little bug we noticed ..

We currently have a 'message' set as a result of completing a path, such as "Bob leveled up!".   However, when multiple players complete requirements simultaneously, they're all receiving the same message - presumably the first one in the queue.  (So, if Bob, Tim and Sue all rankup at the same time, they all see the message personalized for Bob.)

All other associated commands are executing fine, however. (change player permissions level, give/take money, etc.)

Here's a sample of the config.

```
rank3:
  prerequisites:
    in group:
      value: novice
  requirements:
      time: 20m
      money: 500
  results:
      command:
        value: pp user &p promote playergroups;eco take &p 499
      message: '&p has been promoted to Novice!'
  options:
    auto choose: true
    display name: "Novice"
```

**Comment by Staartvin** [comment]
That's odd. I've never seen this bug and can't really reproduce it. Perhaps some more investigation is needed.

**Comment by obzidi4n** [comment]
Quick update.  Looks like it really has nothing to do with concurrent rankups after all.  It's just inserting other player's names ..  odd.

![2017-04-02_16 37 09](https://cloud.githubusercontent.com/assets/14152234/24590856/ae6a2b44-17c2-11e7-818e-4ac064dba130.png)

**Comment by Staartvin** [comment]
Whose perspective is this? What is the name of the player?

**Comment by obzidi4n** [comment]
Hi -- player is "creeperbro" but receives a rankup message for "Harrison012495"

**Comment by Staartvin** [comment]
I think that message is sent by your permissions plugin when you perform the 'pp user &p promote playergroups' command. It does not seem to affect this user, it just tells that Harrison has been promoted!

**Comment by obzidi4n** [comment]
hmm .. ok, will do some more digging on this one.  :)

**Comment by Staartvin** [comment]
Closed due to inactivity. Re-open if still relevant!
