### ISSUE TITLE
Rank progression cannot occur even though player had the necessary pre-requisites.

### ISSUE THREAD

**Issue by Zyrille** [Staartvin/Autorank-2#494]
I'm using Autorank 4.0.5 on my Spigot Minecraft 1.11.2 server. I've installed and reinstalled autorank many times and had finally gotten it working. However prior the install that actually worked, some players have already logged in and I suppose the server has technically recorded data from them.

Now after the install, the only pre-requisite I added was for the player to be inside group1 to be promoted to group2, however AR says that I need to choose a path since there are multiple ones. Upon choosing, regardless of the fact that the player was in the group, it says pre-requisites are not met.

Would anyone have any idea on how to fix this?

I've already tried manually editing the playerdata.yml to manually set their 'chosen' rank. However as soon as I logged on that character in-game, I got promoted to the next rank because I had all the requirements, which I thought fixed the problem but upon checking /ar check, it seems that AR didn't choose a path for me.

These are isolated cases for players who's had ranks before, everyone who entered the server for the 'first' time after installing the working version of ar for me are able to rank up properly.

**Comment by Staartvin** [comment]
Could you provide your paths file and the player data file?

**Comment by Staartvin** [comment]
If you want to reset their progress, reset all their data (try removing their whole entry instead of just a few things).

**Comment by FrozenBeard** [comment]
Are you trying to make a linear ranking system like, group1 > group2 > group3?

**Comment by Zyrille** [comment]
@Staartvin If I reset their progress, I assume I have to erase their entries inside my permissions (i use pex) file too?

Paths:
`# Paths file - This file will contain all paths that a player is allowed to take. Previously known as 'AdvancedConfig.yml'.
# This file contains (by default) a Test group that shows the basic syntax of this file.
# For more information, go to https://github.com/Armarr/Autorank-2/wiki/How-to-configure-the-Paths.yml-file%3F.
# Paths file - This file will contain all paths that a player is allowed to take. Previously known as 'AdvancedConfig.yml'.
# This file contains (by default) a Test group that shows the basic syntax of this file.
# For more information, go to https://github.com/Armarr/Autorank-2/wiki/How-to-configure-the-Paths.yml-file%3F.

Beginner to Adventurer:
  prerequisites:
    in group:
      value: Beginner
  upon choosing:
    message:
      value: '&6&l[Tiny Towny Ranks] &fGreetings! You have started your journey to
        become an &lAdventurer!'
  requirements:
    time:
      value: 1m
  results:
    command:
      value: pex promote &p Autorank
    message:
      value: '&6&l[Tiny Towny Ranks] &fCongratulations, you have completed the requirements
        to become an &1Adventurer&f!'
    message2:
      value: '&6&l[Tiny Towny Ranks] &fFor your next requirement, you will need to
        have a total playtime of &660 minutes&f;'
    message3:
      value: '&6&l[Tiny Towny Ranks] &fBreak/mine a total of &6500 blocks&r; and place
        a total of &6250 blocks&f.'
    message4:
      value: '&6&l[Tiny Towny Ranks] &fMay the gods bless your travels, &1Adventurer&f!'
  options:
    display name: I. The Adventurer
    auto choose: true
Adventurer to Apprentice:
  prerequisites:
    in group:
      value: Adventurer
  upon choosing:
    message:
      value: '&6&l[Tiny Towny Ranks] &fGreetings! You have started your journey to
        become an &2Apprentice&f!'
  requirements:
    time:
      value: 1h
    money:
      value: 5000
    blocks broken:
      value: 500
    blocks placed:
      value: 250
  results:
    command:
      value: pex promote &p Autorank
    command2:
      value: eco take &p 5000
    command3:
      value: broadcast &fCongratulations &6&p &fhas reached the rank of &2Apprentice&f!
    message:
      value: '&6&l[Tiny Towny Ranks] &fCongratulations, you have completed the requirements
        to become an &2Apprentice&f!'
    message2:
      value: '&6&l[Tiny Towny Ranks] &fFor your next requirement, you will need to
        have a total playtime of &63 hours&r&f.'
    message3:
      value: '&6&l[Tiny Towny Ranks] &fBreak/mine a total of &62500 blocks&r and place
        a total of &61500 blocks&r&f.'
    message4:
      value: '&6&l[Tiny Towny Ranks] &fMay the gods bless your travels, &1Apprentice&f!'
  options:
    display name: II. Apprenticeship Journey
    auto choose: true
Apprentice to Templar:
  prerequisites:
    in group:
      value: Apprentice
  upon choosing:
    message:
      value: '&6&l[Tiny Towny Ranks] &fGreetings! You have started your journey to
        become a &3Templar&f!'
  requirements:
    time:
      value: 3h
    money:
      value: 10000
    blocks broken:
      value: 2500
    blocks placed:
      value: 1500
  results:
    command:
      value: pex promote &p Autorank
    command2:
      value: eco take &p 10000
    command3:
      value: broadcast &fCongratulations &6&p &fhas reached the rank of &3Templar&f!
    message:
      value: '&6&l[Tiny Towny Ranks] &fCongratulations, you have completed the requirements
        to become a &3Templar&f!'
    message2:
      value: '&6&l[Tiny Towny Ranks] &fFor your next requirement, you will need to
        have a total playtime of &65 hours&r&f.'
    message3:
      value: '&6&l[Tiny Towny Ranks] &fBreak/mine a total of &66500 blocks&r, place
        a total of &63000 blocks&r&f,'
    message4:
      value: '&6&l[Tiny Towny Ranks] &fand finally, kill a total of &6300 monsters&f.'
    message5:
      value: '&6&l[Tiny Towny Ranks] &fMay the gods bless your travels, &3Templar&f!'
  options:
    display name: III. Templar Training
    auto choose: true
Templar to Sentinel:
  prerequisites:
    in group:
      value: Templar
  upon choosing:
    message:
      value: '&6&l[Tiny Towny Ranks] &fGreetings! You have started your journey to
        become a &4Sentinel&f!'
  requirements:
    time:
      value: 5h
    money:
      value: 15000
    blocks broken:
      value: 6500
    blocks placed:
      value: 3000
    mobs killed:
      value: 300
  results:
    command:
      value: pex promote &p Autorank
    command2:
      value: eco take &p 10000
    command3:
      value: broadcast &fCongratulations &6&p &fhas reached the rank of &4Sentinel&f!
    message:
      value: '&6&l[Tiny Towny Ranks] &fCongratulations, you have completed the requirements
        to become a &4Sentinel&f!'
    message2:
      value: '&6&l[Tiny Towny Ranks] &fFor your next requirement, you will need to
        have a total playtime of &68 hours&r&f.'
    message3:
      value: '&6&l[Tiny Towny Ranks] &fBreak/mine a total of &610000 blocks&r, place
        a total of &67000 blocks&r&f,'
    message4:
      value: '&6&l[Tiny Towny Ranks] &fand finally, kill a total of &61500 monsters&f.'
    message5:
      value: '&6&l[Tiny Towny Ranks] &fMay the gods bless your travels, &4Sentinel&f!'
  options:
    display name: IV. The Way of Sentinels
    auto choose: true
Sentinel to Scholar:
  prerequisites:
    in group:
      value: Sentinel
  upon choosing:
    message:
      value: '&6&l[Tiny Towny Ranks] &fGreetings! You have started your journey to
        become a &5Scholar&f!'
  requirements:
    time:
      value: 8h
    money:
      value: 25000
    blocks broken:
      value: 10000
    blocks placed:
      value: 7000
    mobs killed:
      value: 1500
  results:
    command:
      value: pex promote &p Autorank
    command2:
      value: eco take &p 25000
    command3:
      value: broadcast &fCongratulations &6&p &fhas reached the rank of a &5Scholar&f!
    message:
      value: '&6&l[Tiny Towny Ranks] &fCongratulations, you have completed the requirements
        to become a &5Scholar&f!'
    message2:
      value: '&6&l[Tiny Towny Ranks] &fFor your next requirement, you will need to
        have a total playtime of &610 hours&r&f.'
    message3:
      value: '&6&l[Tiny Towny Ranks] &fBreak/mine a total of &615000 blocks&r, place
        a total of &69500 blocks&r&f,'
    message4:
      value: '&6&l[Tiny Towny Ranks] &fand finally, kill a total of &63000 monsters&f.'
    message5:
      value: '&6&l[Tiny Towny Ranks] &fMay the gods bless you with more wisdom, &5Scholar&f!'
  options:
    display name: V. A Scholastic Purview
    auto choose: true
Scholar to Kingsguard:
  prerequisites:
    in group:
      value: Scholar
  upon choosing:
    message:
      value: '&6&l[Tiny Towny Ranks] &fGreetings! You have started your journey to
        become a &6Kingsguard&f!'
  requirements:
    time:
      value: 10h
    money:
      value: 50000
    blocks broken:
      value: 15000
    blocks placed:
      value: 9500
    mobs killed:
      value: 3000
  results:
    command:
      value: pex promote &p Autorank
    command2:
      value: eco take &p 50000
    command3:
      value: broadcast &fCongratulations &6&p &fhas reached the rank of a &6Kingsguard&f!
    message:
      value: '&6&l[Tiny Towny Ranks] &fCongratulations, you have completed the requirements
        to become a &6Kingsguard&f!'
    message2:
      value: '&6&l[Tiny Towny Ranks] &fFor your next requirement, you will need to
        have a total playtime of &612 hours&r&f.'
    message3:
      value: '&6&l[Tiny Towny Ranks] &fBreak/mine a total of &620000 blocks&r, place
        a total of &613000 blocks&r&f,'
    message4:
      value: '&6&l[Tiny Towny Ranks] &fand finally, kill a total of &65000 monsters&f.'
    message5:
      value: '&6&l[Tiny Towny Ranks] &fMay your shield defend you well, &6Kingsguard&f!'
  options:
    display name: VI. The Kingsguard Shield
    auto choose: true
Kingsguard to Justicar:
  prerequisites:
    in group:
      value: Kingsguard
  upon choosing:
    message:
      value: '&6&l[Tiny Towny Ranks] &fGreetings! You have started your journey to
        become a &7Justicar&f!'
  requirements:
    time:
      value: 12h
    money:
      value: 75000
    blocks broken:
      value: 20000
    blocks placed:
      value: 13000
    mobs killed:
      value: 5000
  results:
    command:
      value: pex promote &p Autorank
    command2:
      value: eco take &p 75000
    command3:
      value: broadcast &fCongratulations &6&p &fhas reached the rank of a &7Justicar&f!
    message:
      value: '&6&l[Tiny Towny Ranks] &fCongratulations, you have completed the requirements
        to become a &7Justicar&f!'
    message2:
      value: '&6&l[Tiny Towny Ranks] &fFor your next requirement, you will need to
        have a total playtime of &615 hours&r&f.'
    message3:
      value: '&6&l[Tiny Towny Ranks] &fBreak/mine a total of &630000 blocks&r, place
        a total of &615000 blocks&r&f,'
    message4:
      value: '&6&l[Tiny Towny Ranks] &fand finally, kill a total of &610000 monsters&f.'
    message5:
      value: '&6&l[Tiny Towny Ranks] &fMay the gods bless your just decisions, &7Justicar&f!'
  options:
    display name: VII. The Just Lives On
    auto choose: true
Justicar to Warchief:
  prerequisites:
    in group:
      value: Justicar
  upon choosing:
    message:
      value: '&6&l[Tiny Towny Ranks] &fGreetings! You have started your journey to
        become a &8War&cchief&f!'
  requirements:
    time:
      value: 15h
    money:
      value: 100000
    blocks broken:
      value: 30000
    blocks placed:
      value: 15000
    mobs killed:
      value: 10000
  results:
    command:
      value: pex promote &p Autorank
    command2:
      value: eco take &p 100000
    command3:
      value: broadcast &fCongratulations &6&p &fhas reached the rank of a &8War&cchief&f!
    message:
      value: '&6&l[Tiny Towny Ranks] &fCongratulations, you have completed the requirements
        to become a &8War&cchief&f!'
    message2:
      value: '&6&l[Tiny Towny Ranks] &fFor your next requirement, you will need to
        have a total playtime of &620 hours&r&f.'
    message3:
      value: '&6&l[Tiny Towny Ranks] &fBreak/mine a total of &640000 blocks&r, place
        a total of &618000 blocks&r&f,'
    message4:
      value: '&6&l[Tiny Towny Ranks] &fand finally, kill a total of &615000 monsters&f.'
    message5:
      value: '&6&l[Tiny Towny Ranks] &fMay the gods bless the wars you wage, &8War&cchief&f!'
  options:
    display name: VIII. Warring Warchiefs
    auto choose: true
Warchief to Archseer:
  prerequisites:
    in group:
      value: Warchief
  upon choosing:
    message:
      value: '&6&l[Tiny Towny Ranks] &fGreetings! You have started your journey to
        become an &9Arch&1seer&f!'
  requirements:
    time:
      value: 20h
    money:
      value: 175000
    blocks broken:
      value: 40000
    blocks placed:
      value: 18000
    mobs killed:
      value: 15000
  results:
    command:
      value: pex promote &p Autorank
    command2:
      value: eco take &p 175000
    command3:
      value: broadcast &fCongratulations &6&p &fhas reached the rank of a &9Arch&1seer&f!
    message:
      value: '&6&l[Tiny Towny Ranks] &fCongratulations, you have completed the requirements
        to become an &9Arch&1seer&f!'
    message2:
      value: '&6&l[Tiny Towny Ranks] &fFor your next requirement, you will need to
        have a total playtime of &625 hours&r&f.'
    message3:
      value: '&6&l[Tiny Towny Ranks] &fBreak/mine a total of &645000 blocks&r, place
        a total of &620000 blocks&r&f,'
    message4:
      value: '&6&l[Tiny Towny Ranks] &fand finally, kill a total of &620000 monsters&f.'
    message5:
      value: '&6&l[Tiny Towny Ranks] &fMay the gods see bountiful blessings in your
        future, &9Arch&1seer&f!'
  options:
    display name: IX. All Seeing Eye
    auto choose: true
Archseer to Magister:
  prerequisites:
    in group:
      value: Archseer
  upon choosing:
    message:
      value: '&6&l[Tiny Towny Ranks] &fGreetings! You have started your journey to
        become a &aMagi&2ster&f!'
  requirements:
    time:
      value: 25h
    money:
      value: 225000
    blocks broken:
      value: 45000
    blocks placed:
      value: 20000
    mobs killed:
      value: 20000
  results:
    command:
      value: pex promote &p Autorank
    command2:
      value: eco take &p 225000
    command3:
      value: broadcast &fCongratulations &6&p &fhas reached the rank of a &aMagi&2ster&f!
    message:
      value: '&6&l[Tiny Towny Ranks] &fCongratulations, you have completed the requirements
        to become a &aMagi&2ster&f!'
    message2:
      value: '&6&l[Tiny Towny Ranks] &fFor your next requirement, you will need to
        have a total playtime of &630 hours&r&f.'
    message3:
      value: '&6&l[Tiny Towny Ranks] &fBreak/mine a total of &650000 blocks&r, place
        a total of &625000 blocks&r&f,'
    message4:
      value: '&6&l[Tiny Towny Ranks] &fand finally, kill a total of &625000 monsters&f.'
    message5:
      value: '&6&l[Tiny Towny Ranks] &fMay the gods see bountiful blessings in your
        future, &aMagi&2ster&f!'
  options:
    display name: X. The Magical Magister
    auto choose: true
Magister to Inquisitor:
  prerequisites:
    in group:
      value: Magister
  upon choosing:
    message:
      value: '&6&l[Tiny Towny Ranks] &fGreetings! You have started your journey to
        become an &bInqui&3sitor&f!'
  requirements:
    time:
      value: 30h
    money:
      value: 300000
    blocks broken:
      value: 50000
    blocks placed:
      value: 25000
    mobs killed:
      value: 25000
  results:
    command:
      value: pex promote &p Autorank
    command2:
      value: eco take &p 300000
    command3:
      value: broadcast &fCongratulations &6&p &fhas reached the rank of an &bInqui&3sitor&f!
    message:
      value: '&6&l[Tiny Towny Ranks] &fCongratulations, you have completed the requirements
        to become an &bInqui&3sitor&f!'
    message2:
      value: '&6&l[Tiny Towny Ranks] &fFor your next requirement, you will need to
        have a total playtime of &635 hours&r&f.'
    message3:
      value: '&6&l[Tiny Towny Ranks] &fBreak/mine a total of &670000 blocks&r, place
        a total of &630000 blocks&r&f,'
    message4:
      value: '&6&l[Tiny Towny Ranks] &fand finally, kill a total of &630000 monsters&f.'
    message5:
      value: '&6&l[Tiny Towny Ranks] &fMay the gods provide answers to the questions
        you seek, &bInqui&3sitor&f!'
  options:
    display name: XI. Questing Inquisitor
    auto choose: true
Inquisitor to Strategos:
  prerequisites:
    in group:
      value: Inquisitor
  upon choosing:
    message:
      value: '&6&l[Tiny Towny Ranks] &fGreetings! You have started your journey to
        become a &dStra&5tegos&f!'
  requirements:
    time:
      value: 30h
    money:
      value: 500000
    blocks broken:
      value: 50000
    blocks placed:
      value: 25000
    mobs killed:
      value: 25000
  results:
    command:
      value: pex promote &p Autorank
    command2:
      value: eco take &p 500000
    command3:
      value: broadcast &fCongratulations &6&p &fhas reached the rank of a &dStra&5tegos&f!
    message:
      value: '&6&l[Tiny Towny Ranks] &fCongratulations, you have completed the requirements
        to become a &dStra&5tegos&f!'
    message2:
      value: '&6&l[Tiny Towny Ranks] &fFor your next requirement, you will need to
        have a total playtime of &640 hours&r&f.'
    message3:
      value: '&6&l[Tiny Towny Ranks] &fBreak/mine a total of &690000 blocks&r, place
        a total of &640000 blocks&r&f,'
    message4:
      value: '&6&l[Tiny Towny Ranks] &fand finally, kill a total of &640000 monsters&f.'
    message5:
      value: '&6&l[Tiny Towny Ranks] &fMay the gods guide your journey to attain higher
        wisdom, &dStra&5tegos&f!'
  options:
    display name: XI. The Strategist
    auto choose: true
Strategos to Caesar:
  prerequisites:
    in group:
      value: Strategos
  upon choosing:
    message:
      value: '&6&l[Tiny Towny Ranks] &fGreetings! You have started your journey to
        become a &eCae&6sar&f!'
  requirements:
    time:
      value: 40h
    money:
      value: 500000
    blocks broken:
      value: 90000
    blocks placed:
      value: 40000
    mobs killed:
      value: 40000
  results:
    command:
      value: pex promote &p Autorank
    command2:
      value: eco take &p 500000
    command3:
      value: broadcast &fCongratulations &6&p &fhas reached the rank of a &eCae&6sar&f!
    message:
      value: '&6&l[Tiny Towny Ranks] &fCongratulations, you have completed the requirements
        to become a &eCae&6sar&f!'
    message2:
      value: '&6&l[Tiny Towny Ranks] &fFor your next requirement, you will need to
        have a total playtime of &650 hours&r&f.'
    message3:
      value: '&6&l[Tiny Towny Ranks] &fBreak/mine a total of &6100000 blocks&r, place
        a total of &650000 blocks&r&f,'
    message4:
      value: '&6&l[Tiny Towny Ranks] &fand finally, kill a total of &660000 monsters&f.'
    message5:
      value: '&6&l[Tiny Towny Ranks] &fMay the gods bless kingdoms that you build,
        &eCae&6sar&f!'
  options:
    display name: XIII. The Rise of Caesar
    auto choose: true
Caesar to Warmaster:
  prerequisites:
    in group:
      value: Caesar
  upon choosing:
    message:
      value: '&6&l[Tiny Towny Ranks] &fGreetings! You have started your journey to
        become a &cWar&4master&f!'
  requirements:
    time:
      value: 50h
    money:
      value: 1000000
    blocks broken:
      value: 100000
    blocks placed:
      value: 50000
    mobs killed:
      value: 60000
  results:
    command:
      value: pex promote &p Autorank
    command2:
      value: eco take &p 1000000
    command3:
      value: broadcast &fCongratulations &6&p &fhas reached the rank of a &cWar&4master&f!
    message:
      value: '&6&l[Tiny Towny Ranks] &fCongratulations, you have completed the requirements
        to become a &cWar&4master&f!'
    message2:
      value: '&6&l[Tiny Towny Ranks] &fFor your next requirement, you will need to
        have a total playtime of &6100 hours&r&f.'
    message3:
      value: '&6&l[Tiny Towny Ranks] &fBreak/mine a total of &6200000 blocks&r, place
        a total of &6100000 blocks&r&f,'
    message4:
      value: '&6&l[Tiny Towny Ranks] &fand finally, kill a total of &6100000 monsters&f.'
    message5:
      value: '&6&l[Tiny Towny Ranks] &fMay the gods raise hail and firestorm on your
        battlefields, &cWar&4master&f!'
  options:
    display name: XIV. A Warmaster's Raging Fire
    auto choose: true
Warmaster to Fate:
  prerequisites:
    in group:
      value: Warmaster
  upon choosing:
    message:
      value: '&6&l[Tiny Towny Ranks] &fGreetings! You have started your journey to
        become a &f&lFate&f!'
  requirements:
    time:
      value: 100h
    money:
      value: 2000000
    blocks broken:
      value: 200000
    blocks placed:
      value: 100000
    mobs killed:
      value: 100000
  results:
    command:
      value: pex promote &p Autorank
    command2:
      value: eco take &p 2000000
    command3:
      value: broadcast &f&lCongratulations! &6&p &fhas achieved the highest rank, &f&lFate&f!
    message:
      value: '&6&l[Tiny Towny Ranks] &fCongratulations, you have completed the requirements
        to become a &f&lFate&f!'
    message2:
      value: '&6&l[Tiny Towny Ranks] &fThis is the last rank achievable in this server,
        you have done well.'
    message3:
      value: '&6&l[Tiny Towny Ranks] &fWe thank you for supporting our server and
        for continously playing!'
    message4:
      value: '&6&l[Tiny Towny Ranks] &fMay your reign be infinite and everlasting
        as time, &f&lFate&f!'
  options:
    display name: XV. The Everlasting Fate
    auto choose: true
`

Playerdata:
`e98a31e7-cad0-4b30-a7df-81f5dbaf2e5e:
  exempt leaderboard: true
  started paths: []
  completed paths:
  - Beginner to Adventurer
  - Adventurer to Apprentice
3b26000c-4cbe-4865-a6e0-6826d18c46ea:
  exempt leaderboard: false
  started paths:
  - Apprentice to Templar
  completed paths:
  - Beginner to Adventurer
  - Adventurer to Apprentice
  chosen path: Apprentice to Templar
  completed requirements:
  - 0
  - 2
  - 3
a8662495-e3be-4d3e-bf1a-b0b82da75271:
  exempt leaderboard: false
  started paths:
  - Adventurer to Apprentice
  completed paths:
  - Beginner to Adventurer
  chosen path: Adventurer to Apprentice
  completed requirements:
  - 0
05b333a8-a5b8-4692-bbc9-8b3ce1e69e95:
  exempt leaderboard: false
  started paths:
  - Adventurer to Apprentice
  completed paths:
  - Beginner to Adventurer
  chosen path: Adventurer to Apprentice
  completed requirements:
  - 0
  - 2
  - 3
13a16f3f-5b71-4061-9481-33d7776b7fdc:
  exempt leaderboard: false
ac8ca0ba-c960-48ff-8c48-d75428e6fc9c:
  exempt leaderboard: false
  started paths:
  - Adventurer to Apprentice
  completed paths:
  - Beginner to Adventurer
  chosen path: Adventurer to Apprentice
  completed requirements:
  - 0
19151ef0-ed45-4994-a45a-71f8f53e7dda:
  exempt leaderboard: false
  started paths:
  - Adventurer to Apprentice
  completed paths:
  - Beginner to Adventurer
  chosen path: Adventurer to Apprentice
  completed requirements:
  - 0
af91b8e6-9bec-4c9b-8b06-f36fceebe04e:
  exempt leaderboard: false
  started paths:
  - Adventurer to Apprentice
  completed paths:
  - Beginner to Adventurer
  chosen path: Adventurer to Apprentice
  completed requirements:
  - 0
  - 2
  - 3
1afd45df-4ebe-4777-b404-2014efde0dc8:
  exempt leaderboard: false
  started paths:
  - Adventurer to Apprentice
  completed paths:
  - Beginner to Adventurer
  chosen path: Adventurer to Apprentice
  completed requirements:
  - 0
a181038c-de12-488a-ac37-4e8bea402c3d:
  exempt leaderboard: false
  started paths:
  - Adventurer to Apprentice
  completed paths:
  - Beginner to Adventurer
  chosen path: Adventurer to Apprentice
  completed requirements:
  - 0
  - 2
  - 3
edca9f20-6362-4334-b0cd-108bd74e9b53:
  exempt leaderboard: false
  started paths:
  - Adventurer to Apprentice
  completed paths:
  - Beginner to Adventurer
  chosen path: Adventurer to Apprentice
  completed requirements:
  - 0
8fbafd64-fb88-469a-9e12-17be61c224e6:
  exempt leaderboard: false
  started paths:
  - Adventurer to Apprentice
  completed paths:
  - Beginner to Adventurer
  chosen path: Adventurer to Apprentice
  completed requirements:
  - 0
1186433b-071f-41b7-a97a-9cd34f846245:
  exempt leaderboard: false
  started paths:
  - Adventurer to Apprentice
  completed paths:
  - Beginner to Adventurer
  chosen path: Adventurer to Apprentice
72b5f5ac-f51d-465f-9602-25e0cd139504:
  exempt leaderboard: false
9bd7409d-b65c-4893-8401-54e552f3f634:
  exempt leaderboard: false
  chosen path: Apprentice to Templar
  completed requirements:
  - 2
  - 3
  started paths:
  - Apprentice to Templar
462304dd-4c13-4fe0-bbd0-5c627b985a5c:
  exempt leaderboard: false
`

@FrozenBeard I have already created the linear ranking system, yes. Please see my paths.yml content above.

**Comment by Zyrille** [comment]
Found a way to fix! I did the following steps for reference if anyone runs into the same problem:

- stopped the server completely
- edited user permissions and removed from the group
- edited playerdata and removed player's information/data
- started the server
- added the player to the "default (Beginner)" rank which is also the starting point of my autoranks
- made the player choose the first part of the path listed in my paths.yml

Thank you @Staartvin for suggesting the data wipe. I didn't know at first how to go about that safely without damaging the plugin and current settings but it's all good now.

**Comment by Zyrille** [comment]
Okay, I think I celebrated too early. For some reason after doing this, autorank isn't reading the time I'm spending online.

**Comment by Staartvin** [comment]
So it correctly determines what path players should be in, but it does not count time anymore?

**Comment by Zyrille** [comment]
There's actually... a lot of issues that cropped up after that.

**Time being recorded as an issue**:
When I do the steps from the one I listed above for everyone else, time still moves for them, but for me (who's an admin/owner) it isn't working for some reason. I know there is the permission node to exempt people from time being recorded but I don't have it anywhere near my permissions so I'm not sure why it's doing that. I've removed "*" from my permission nodes too and it still didn't work.

**Console running the commands**:
Another problem I ran into was when the member was a part of the moderator group and the second autorank from my paths yml which is the Adventurer group. So everything is okay, they log into the server, they got the Beginner Rank > moved into the Adventurer rank after 1 minute, I promoted the player to moderator so they are tagged with [Moderator] Username [AutorankRank]. However the problem came in when these people were trying to level up from Adventurer > Apprentice. For some reason when console ran the command, their progression to Adventurer > Apprentice did not happen. From what you can see in my paths.yml file, I "promote" them through pex in the autorank cluster to avoid a cluttered pex file, but should I "add" the groups coming after instead of promoting?

**/AR top resetting**:
So everytime I do a restart on my server, or I actually can't remember what triggers it the /ar top resets all the times and I'm not sure how to configure it properly so it can list down the time from /ar activity. Players have been starting to complain about the /ar top not being accurate. :<

**Comment by Zyrille** [comment]
The issue encountered was more of a permissions plugin, but some were simply misconfigurations which @Staartvin was kind enough to patiently run me through.

Issue: /ar top resetting everytime there is a restart
Fix: in your configuration, set globaltime leaderboard to false.

Issue: autorank isn't detecting the group pre-requisite for the next rank
Fix: This specially happens if you have multiple groups in your permission file, for my server I have three (autorank, supporter ranks, staff ranks) which all has their own ladder (I use PEX); make sure you turn 'primary Vault group' to false in Settings.yml so autorank will recognize all of the groups a player is in instead of just the primary one.

The console running the commands issue was actually a permissions issue; so unrelated to this.

Thanks again to the author for being awesome and sharing his time trying to troubleshoot the issues I was having.
