### ISSUE TITLE
[bug] prerequisites figuring out what "group" someone is in in luckperms default.

### ISSUE THREAD

**Issue by FrozenBeard** [Staartvin/Autorank-2#495]
By default you have to use the default.yml for your first group in luckperms, its possible to re-name this in the luckperms config:
```
group-name-rewrite:
  default: Deckhand
```
The issue is, autorank does not read this name rewrite properly, a new player that gets put into "default" group can then not rank up to the next group as its prerequisites is not recognised, if I change it to the name in set in group-name-rewrite Autorank throws a hissy fit telling me there's an error ever second.

I have had to set my default group to "default" to get it to work, as it does not respect renaming it in luckperms.
```
default:
  prerequisites:
    in group:
      value: default
```

**Comment by Staartvin** [comment]
Unfortunately, that's a bug with Vault.

**Comment by Staartvin** [comment]
Autorank does not directly access LuckPerms, but uses Vault as a middleman. Vault apparently does not support this rewrite function.
