### ISSUE TITLE
Several same type requirements

### ISSUE THREAD

**Issue by WyRe** [Staartvin/Autorank-2#499]
I would like setup Autorank main path to demand several mcmmo skills, I mean, I would like people promote from Guests group to Citizens when they have got 30 in fishing skill, 20 in acrobatics and 10 in swords; this is my `Paths.yml` config:
```
Documentos:
  prerequisites:
    in group:
      value: Visitantes
  requirements:
    money:
      value: 1000
    mcmmo skill level:
      value: 20;acrobatics
    mcmmo skill level:
      value: 10;swords
    mcmmo skill level:
      value: 30;fishing
  results:
    command: broadcast &p ya tiene los papeles!
    command2: eco give &p 5000
    command3: pex user &p group set Ciudadanos
    message: Felicidades, ya no eres un extraño!
  options:
    display name: Documentos
    auto choose: true
```

but the plugin only recognises the last mcmmo skill, what am I doing wrong? Maybe the plugin does not support that kind of setup? 

Thank you so much.

**Comment by Staartvin** [comment]
Autorank does support this setup, so no worries. You have to add an integer after the requirement name if you have multiple of them. So, 

mcmmo skill level 1: bla bla
mcmmo skill level 2: bla bla
Etc

**Comment by WyRe** [comment]
Thank you so much. :D
