### ISSUE TITLE
Paths.yml was wiped, rebuilt it, now players are restarted on their path.

### ISSUE THREAD

**Issue by jonassm** [Staartvin/Autorank-2#500]
Hi,

I recently had a issue where my paths.yml was wiped. It happened after i added an extra command to execute when players are done on their path(s).

Anyways, i rebuilt the paths.yml and everything is now working as intended, heres my issue.

I had a player on a path, that is completed when you play for 24 hours. At the time of the paths wipe, he was at 19 hours. After rebuilding, he is now at 14 minutes, even though his /ar times says 19 hours.

EDIT: The 'total' time on /ar times was also reset for all players. /ar leaderboard still shows correct values.

EDIT 2: Nope, there goes my leaderboard.

EDIT 3: There's total time backups! Thanks staartvin! Just need to figure out how to initiliaze it.

EDIT 4: Fixed leaderboard issue. /ar times  still shows wrong value in 'total' field.

Here's my paths.yml
```
Newcomer to novice:
    prerequisites:
        in group: 
            value: default
    requirements:
        time: 
            value: 5h
    upon choosing:
        message: 
            value: 'After 5 hours playtime, you will be a Novice!'
    results:
        command:
            value: 'pex user &p group set freshie'
    options:
        infinite pathing: false
        auto choose: true
        priority: 1
Novice to regular:
    prerequisites:
        in group: 
            value: freshie
    requirements:
        time: 
            value: 1d
    upon choosing:
        message: 
            value: 'After 24 hours playtime, you will be a Regular!'
    results:
        command:
            value: 'pex user &p group set regular' 
    options:
        infinite pathing: false
        auto choose: true
        priority: 2
Regular to veteran:
    prerequisites:
        in group: 
            value: regular
    requirements:
        time: 
            value: 100h
    upon choosing:
        message: 
            value: 'After 100 hours playtime, you will be a Veteran!'
    results:
        command:
            value: 'pex user &p group set veteran' 
    options:
        infinite pathing: false
        auto choose: true
        priority: 3
```

**Comment by Staartvin** [comment]
Your path file looks fine to me. What is the current problem you're having? The total time is not correctly synced?

**Comment by jonassm** [comment]
Yes, sorry this is very cluttered.

Issue 1:
/ar times shows wrong values, even though /ar leaderboard shows correct. To be exact, when performing /ar times all values are correct except total.

Issue 2:
After my paths.yml was wiped, all progress was wiped for my players. Is there a way to recover said progress?

**Comment by Staartvin** [comment]
The progress of the players is normally stored in the playerdata.yml file, but it may have been overridden. Check your backups folder (in the Autorank folder) to see if there is a backup of that file.

**Comment by Staartvin** [comment]
For the first issue, could you check if **/ar activity** shows the correct timings?

**Comment by jonassm** [comment]
Hi,

/ar activity shows correct values.

In terms of progression, i'm now seeing the people who were not online when paths was wiped did not lose their progression, and their /ar times is correct.

**Comment by Staartvin** [comment]
Hmm, odd stuff. I don't exactly know what happened, as I can't really look back into your logs, but I have the feeling that perhaps some reset command was run for a few people.

**Comment by jonassm** [comment]
What i really just want now is /ar times to show correct values again.

My skype name is jmorbjerg. If you have the time, i'm willing to provide whatever information you need.
