### ISSUE TITLE
autorank.exclude preventing players from earning play-time

### ISSUE THREAD

**Issue by SioWolf** [Staartvin/Autorank-2#501]
The permission autorank.exclude is preventing players from earning playtime on the server. Doing /ar time when that permission has been added to your rank, it reported "Today: 0 minutes".

The permission autorank.timeexclude SHOULD be the one doing this, autorank.exclude should only prevent them from being ranked.

**Comment by Staartvin** [comment]
Thanks for notifying me, and sorry for replying so late.
