### ISSUE TITLE
Automatically choose path.

### ISSUE THREAD

**Issue by ALufkin24** [Staartvin/Autorank-2#502]
When I do /ar choose Visitor, it says that I do not meet prereq of the path; type /ar view prereq Visitor. When I view it, it says to be in group Visitor. I'm already in that group though. Why is it saying that I don't meet the prereq when I'm already in the default group 'Visitor'? When a new player comes on, doesn't it automatically put them in Visitor group?

 Path.yml: https://pastebin.com/a4f2vLKt
 Settings: https://pastebin.com/s5EJtTvV

**Comment by Staartvin** [comment]
Try to change this 'use primary group for vault: true' to 'use primary group for vault: false'.
