### ISSUE TITLE
Internal Error When Running Command And PreReq Group Not Being Detected

### ISSUE THREAD

**Issue by heckabecca** [Staartvin/Autorank-2#507]
Hey there,

I just upgraded to the latest update released today. After doing so I am having an issue running the command /ar view list. It gives me an internal error message in game when trying to use and throws the following errors in the console:
https://pastebin.com/rCu0gqXJ

I am also having an issue with prereqs. When trying to choose a rank path it says "You do not meet the prerequisites of this path!" The prereq is to be in a specified group, which I am in so I'm not sure why its not allowing the path to be chosen. I've attached my pex permissions file and the paths.yml. What am I doing wrong?

I just want players to be able to complete the 8 requirements then automatically be put into the next rank. Instead, players have to do /ar check to gain their rank if all the reqs are completed, and then have to do /ar choose to select the next rank. How can I make this automatic? I used the "auto choose: true" in the config, but it is not auto choosing the next path.

Paths.yml:
https://pastebin.com/rkRZNHvT

Permissions.yml:
https://pastebin.com/agCmxur6

**Comment by Staartvin** [comment]
Hmm, good question. Let me copy your set up and see whether I also get the error.

**Comment by Staartvin** [comment]
I think I found the issue. Let me push a new update to you.

**Comment by Staartvin** [comment]
Could you try this version: http://178.62.255.148:8080/job/Autorank/84/

**Comment by heckabecca** [comment]
No internal issues or errors in console with this version. 

I'm still having the problem though with not being able to choose a path. Even though I do meet the prereqs of being in a certain group, it says I don't meet the prereqs of this path. This leaves me unable to rank to the next level...Did you happen to see if I set something up wrong? Also, I am part of 2 groups, could that be the issue?

**Comment by heckabecca** [comment]
That isnt the issue, I removed myself from the second permission group and it still says I don't meet prereqs..

**Comment by Staartvin** [comment]
What path are you trying to get in?

**Comment by heckabecca** [comment]
I'm trying to get into the Troller path. I was able to complete the first path just fine but after that, its just stuck.

**Comment by heckabecca** [comment]
It seems to be working now. Found a couple permission issues, thanks for the help :)

**Comment by heckabecca** [comment]
Dang it nvm. Still having the same issue. I'm in the required prereq group, yet still cant choose the next path cause it says I'm not in that group. I pinpointed where the problem is though.

On my server I have it so players have 2 groups assigned to them at a time. When in just one group, Autorank works perfect, and I'm able to choose the next path. But, when I am a part of 2 different permission groups, that's when it won't let me choose the next path. :(

**Comment by Staartvin** [comment]
Can you try to set 'use primary group of Vault' to false in the setting file and try again?

**Comment by heckabecca** [comment]
That seems to have solved the problem! Thank you!
