### ISSUE TITLE
Could not set up requirement 'time'

### ISSUE THREAD

**Issue by Sidious82** [Staartvin/Autorank-2#508]
upon install of Autorank-4.0.6:
https://pastebin.com/987raeYe

existing 4.0.5 path.yml:
https://pastebin.com/PFbjuwiH

conclusion: had to revert to Autorank-4.0.5

**Comment by Sidious82** [comment]
this was promised to be automatic and easy...

**Comment by Staartvin** [comment]
Let me test this on my local machine.

**Comment by Staartvin** [comment]
It seems it has something to do with the Paths file, not Autorank. Let me check the formatting.

**Comment by Staartvin** [comment]
I found the problem: you cannot have a '1'. I don't know why and it shouldn't work like that, but that's a bug. I'm working on fixing it.

**Comment by Staartvin** [comment]
[This version](http://178.62.255.148:8080/job/Autorank/86/) should fix this mistake.
