### ISSUE TITLE
[bug] Needs to be a delete or reset last group

### ISSUE THREAD

**Issue by FrozenBeard** [Staartvin/Autorank-2#511]
There needs to be a delete user or reset last group, old data is causing a lot of issues still from terrible upgrades over time and the data not being converted properly. 
The auto picking a path isn't working properly if you have a donator that inherits 2 ranks. The primary group which is passed to vault is their Donator rank, which is set as their "last group". 
Now I have everything setup to rank them up a track properly in my config, it works. But since there is no track system for autorank its checking externally to the vault instead of it checking the past path they were in.
It really makes no sense, as I reset a few players data and it worked as it should but with some it does not.
We need a full user delete or a reset last group.

**Comment by vapecloudbear** [comment]
Bump^ This is now implemented.
