### ISSUE TITLE
I want donators to also be able to rank up.

### ISSUE THREAD

**Issue by devonkeith** [Staartvin/Autorank-2#513]
As soon as a player buys a rank or as soon as they are staff, Autorank immediately stops checking them (still counts time), but won't rank them up. I want autorank to rank up regardless of what rank they are.

**Comment by FrozenBeard** [comment]
I also asked for this!
This is driving me absolutely nuts that Donators cant rank up.

There needs to be an "OR" operator, so when its checking the prerequisites, you can do     
```
in group:
      value: default
or in group:
     value: donatorrank1
or in group:
     value: donatorrank2
or in group:
     value: donatorrank3
```

**Comment by Staartvin** [comment]
In fact, there is an operator! Try doing this:

`Java

in group:
    value: (default), (donatorrank1), (donatorrank2), (donatorrank3)
`

**Comment by FrozenBeard** [comment]
@Staartvin I will give this a try.
One issue I can see, is if they are a donator rank, and they can select whatever path they want then, as I'll have to out the donator ranks in ALL the rank prerequisites. 

So for example

Player1 is:
Donator1 (Primary group)
AutoRank1

They could select AutoRank5 as the prerequisites would be
```
AutoRank5:
    in group:
        value: AutoRank4, (donatorrank1), (donatorrank2), (donatorrank3)
```

Normal players would be checked they are infant AutoRank4 before they can select AutoRank5, as its a linear system. But this wont be the same for Donator1.

This is why I was suggesting having a track system, to see what position on the track they are at.

**Comment by FrozenBeard** [comment]
Yes as I assumed. I added the "Captain" rank I give to donators to all the ranks, and it just skipped all of them and went direct to the last rank, there for bypassing the entire ranking system.
```
  prerequisites:
    in group:
      value: Firstmate, Captain, Admiral
```

**Comment by heckabecca** [comment]
Just create another path with the exact same ranks except require the donor rank in the prereq.

**Comment by FrozenBeard** [comment]
That dousnt work, read my reply.
