### ISSUE TITLE
Changing rank doesn't work

### ISSUE THREAD

**Issue by Wilci** [Staartvin/Autorank-2#517]
Hey!

I have created a path and everything runs smooth except for one little thing.  I got this set up:
Results:
    Command: manuadd @p Vip
But that doesn't make the player rank up to Vip.
I am using Group manager for permissions and groups.
And the only message I get in my console is "Player not found!
Any help would be much appreciated!
I have tried to change @p to %player% and @player but none of them helped.

**Comment by Keystirras** [comment]
The placeholder is not @p or %player%

Try &p
