### ISSUE TITLE
Autorank 2 not promoting?

### ISSUE THREAD

**Issue by MrPinkyyy** [Staartvin/Autorank-2#527]
I spent a lot of time looking at the setup for the new Autorank and seeing how other people managed to set their up but I can't seem to figure out why mine won't promote other users.
[Paths.txt](https://github.com/Staartvin/Autorank-2/files/1137279/Paths.txt)

If someone would be able to show me what I have done wrong or what I am not understanding it would help greatly

**Comment by Redstonetorch** [comment]
Is this your default rank?

**Comment by MrPinkyyy** [comment]
Alright I'll give it a try, Thank you

**Comment by MrPinkyyy** [comment]
Responding to the first comment, Peasant is my Default rank. I have added in a second rank for Citizen just checking it is right,
[Paths.txt](https://github.com/Staartvin/Autorank-2/files/1140357/Paths.txt)

**Comment by Redstonetorch** [comment]
Right. As I said before the paths.txt is almost entirely different than the way I have mine set up with advancedconfig/yml... 

From what I can see , the only problem is that you dont have a top rank- (rank priority 1) and 1000 may be too high, maybe try 100, go down from there, and make three ranks, set one to 100 one to 50 and one to 1..  set the requirements something easy for testing purposes, like 3mins 5 mins and 7 mins just to see if its working properly.

**Comment by Redstonetorch** [comment]
if you have discord I could work with you there, and maybe help you out - but i cant promise anything

**Comment by MrPinkyyy** [comment]
Yeah it's still not promoting if you wanna add me on Discord and help me through it it would be great. id: Noob120#0976
