### ISSUE TITLE
[request] (Again) A proper path tracking system. 

### ISSUE THREAD

**Issue by FrozenBeard** [Staartvin/Autorank-2#528]
I am again requesting a PROPER path tracking system, where you go up tracks, Just like LuckPerms, where you have a list (In order) of the Linear ranks, in order people progress up.

Look at my config, its fine. https://pastebin.com/EG7kBQSS

I've told you already how this command works, but let me refresh your memory, because i JUST KNOW this will be the first response I get asking about the luckperms command.

You should be testing with LuckPerms, there is nothing else out there that rivals the quality of this plugin, nobody should be using anything else.

`lp user &p parent settrack ranks firstmate`
https://github.com/lucko/LuckPerms/wiki/Command-Usage#lp-usergroup-usergroup-parent-settrack

I have a file called "ranks" which has this in it:
```
name: ranks
groups:
- default
- cadet
- sailor
- carpenter
- gunner
- boatswain
- firstmate
- quartermaster
```
As you can see what this command does is it clears any other existing rank **in that specific ranks track** and sets it to _firstmate_. Now there is a promote up track feature in luckperms I was using before this, but the state of autorank I couldn't trust using it, as Autorank randomly puts people in different "paths".

I STILL have stupid errors that shouldn't happen. Since your conversion for data has been so piss poor over different versions the data is allover the shop, I had a player randomly rank up to Quartermaster, the last rank first, and THEN he was set to gunner and he ranked up form there. Hes a VERY long term player, played for 3 years on the server, so hes had every iteration of data, hes been donator etc. 
I think what happened was he was donator, then when that run out, he did /rankup which I have mapped to /ar check, This then picked quatermaster for some reason? And then when he did /rankup again it noticed he had other ranks that he hadn't yet ranked too, so it then set him as gunner. Can you see WHY needing a proper track system is needed? It needs to check they are at the right place and only works in a linear fashion. There is absolutely no checking at all going on.
It needs to go rank1 > rank2 > rank3. and it needs to check, if you are Rank2, it should not allow you to be fucking put into rank1. Just look at how luckperms does tracks, its exactly what is needed for autorank.

**Comment by Staartvin** [comment]
Thanks for the detailed explanation, although I'm not sure whether I understand what settrack does exactly. Does it clear all other groups of a player and set the rank to first mate? Or does it clear all groups of the player if the group belongs to one of the groups in the player's current track? 

Your primary issue seems to be that Autorank does not check whether a player is meeting the prerequisites of the group before it performs actions on that player. 

For example, the Cadet path (to Sailor) does not continously check whether the player is still a Cadet, correct?

**Comment by FrozenBeard** [comment]
Luckperms allows multiple ranks/groups per player, settrack is telling luckperms up promote someone up/down a specific _track_ (Like I posted above with the list of ranks), since players can be part of multiple groups/ranks this means they can have separate tracks. for instance I have these tracks:
- Ranks (The ranks I posted above)
- Donators (Donators inherit their normal rank + a donator rank thats set as their primary (For vault))
- Staff (These are the staff ranks in a track system, so staff can be promoted separately)
- Building (Build team, these have separate ranks)

So in my example, A player could be a donator + a rank. I dont want to delete the donator rank, they just need their ranks track to be updated, so its saying update their ranks track to XYZ. leaving the donators tracks alone. Again, I cant do this as Autorank does not have or allow or work with any tracks system, its just all slapped into one file.

There is a MAJOR issue where over years the data for players is an utter mess, my suggestion of a track system solves these things:

1. Actually having a proper linear system, so it knows where a player is and what is next instead of this seemably random paths stuff.
2. it will allow Donators to rank up, or it'll allow people with multiple ranks to rank up, your system at present only allows someone to be one rank and one rank only, it cannot check a specific track of a player, ranks or donator or staff.
3. If you had it working with a tracks system you could have an automated helper rank that progresses up a helper ranking system as well as their normal ranking.
4. Any other aspect in-game that changes a playters rank, if its manual, part of a game, a donation etc, isn't tracked by autorank. so it still thinks they are on the same path even if they have changed ranks, its not checking if they are on the right track!

> Your primary issue seems to be that Autorank does not check whether a player is meeting the  prerequisites of the group before it performs actions on that player. For example, the Cadet path (to Sailor) does not continously check whether the player is still a Cadet, correct?

Kind of.. read what I wrote, This makes no sence if a player is more than 1 rank. What if they are a donator on a donator track? you cant add the donator ranks to ALL the prerequisites as I tried it has NO idea where the player is at in the ssyutem, it cant tell if its Rank1 > Rank2> rank3. It has no idea where the player is, its guessing, you need a SOLID linear system that goes from one to another, this is a track system.

Please both download and test luckperms, you should not be using anything else to test with, everything else is fully outdated, nothing can compare to the feature set and stability of luckperms.
I have linked to the docs in my first post, this is worth reading to understand it.
