### ISSUE TITLE
cannot track witherskeletons or zombiepigman as a requirement. 

### ISSUE THREAD

**Issue by FatalBlade** [Staartvin/Autorank-2#529]
mobs killed7:    
            value: 500;wither_skeleton   

this is how I have it in my paths.yml and it shows up with /ar check to say I need to kill 500 of them but when I kill one or twenty and try /ar track it will say 0/500 killed. 

For zombiepigman  I can't even figure out how to put it into the paths.yml to try and track them as a killable mob.

**Comment by FatalBlade** [comment]
Correct

On Jul 25, 2017 2:34 PM, "Staartvin" <notifications@github.com> wrote:

You are using Statz, right?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Staartvin/Autorank-2/issues/529#issuecomment-317829071>,
or mute the thread

**Comment by Staartvin** [comment]
I think I found the issue. I'm working on a fix!
