### ISSUE TITLE
Re Ranking  (Do-over)

### ISSUE THREAD

**Issue by sharkybushbaby** [Staartvin/Autorank-2#530]
Question . 
On my server I have a way a player can change rank via signs. and in 1 rank ( Jedi ) Im using auto rank to progress in that class. ( example to Jedi Knight )
If a player at some point changes class with the signs.( to bounty Hunter ) and then later wants to start fresh  and returns to the ( Jedi ) Class it wont let them progress to (jedi Knight) as its logged they already have. Is there a way that if that re enter the Jedi  / Default class they can redo the requirements without  me having to delete the stored UUid shtuff. . ?

other wise they are stuck at Jedi / default.

Appreciate your Time thank you

**Comment by sharkybushbaby** [comment]
I discovered infinite ranking option.... 

(lots of configs on this one sorry )

**Comment by Staartvin** [comment]
Good that you figured it out yourself!
