### ISSUE TITLE
Port Autorank to Sponge.

### ISSUE THREAD

**Issue by fcpwiz** [Staartvin/Autorank-2#531]
Hi Staartvin,

AutoRank is one of my favorite plugins for Bukkit/Spigot, but now with the direction everything is going in - Sponge seems to be the new home for plugins.

I would _love_ to see AutoRank made available for Sponge/SpongeForge servers!

**Comment by Staartvin** [comment]
I have planned this for the future!

**Comment by Sade66** [comment]
Any updates on this? It would be awesome to have AutoRank on Sponge.
