### ISSUE TITLE
Items to Rank up. 

### ISSUE THREAD

**Issue by sharkybushbaby** [Staartvin/Autorank-2#536]
Hey, Sorry to bother you again @Staartvin 
But im giving a class 4 recuirments to rank up. 
xp works fine
world works fine. but i need a player to obtain 2 blocks to finish off. 
I dont appear to be changing when I get the blocks?

heres what I have.

JediKnight:
        requirements:
            exp:
                value: 150
            world:
                value: Tython
            has item:
                value: 252;1;11;BlueHolocron;true
            has item2:
                value: 252;1;5;GreenHolocron;true

the item/block is a concrete powder, the first blue and second is Lime. 
I see the value is the 252(block) amount 1, data11(is that the color of the block?) item name(is renamed in game).

what am i not doing wrong Ive tried a few variations. IS the data the color?
Please help. thanks as ever for your time.

**Comment by Staartvin** [comment]
Hey good question! The wiki states the order like this: 'id;amount;data;name;false/true', see https://github.com/Staartvin/Autorank-2/wiki/Requirements-&-Results

For Blue concrete powder, we would get '252;1;11;Blue powder;true'. It seems you already have that. 

Could you try /ar track to see if it tracks the blocks correctly?

**Comment by sharkybushbaby** [comment]
Just quickly . Ive set it to 
JediKnight:
        requirements:
            exp:
                value: 150
            world:
                value: Tython
            has item:
                value: 252;1;11
            has item2:
                value: 252;1;5
And this works. 
It says however, obtain1 concrete powder (dam,value:11) in game.... whats Dam?

 I can change this in the resource pack which wont effect it. 

ar track to 252:11 isnt a valid number.

**Comment by Staartvin** [comment]
252;1;11 is the same as 252;1;11;Blue powder;true, but in the second case you add a display name that Autorank shows. If you just use '252;1;11', Autorank will show 'Blue powder' instead of 'Concrete Powder (damage value 11)'. Try using _252;1;11;Blue powder;false_, with the 'false' at the end.

**Comment by Staartvin** [comment]
The true/false at the end marks whether the item should also have the exact name, so _252;1;11;BlueHolocron;true_ would mean that a player needs a blue concrete powder block with the exact name 'BlueHolocron'.

**Comment by sharkybushbaby** [comment]
Beautiful. Blue Holocron with false works a treat.  Just a quick side question. does a player have to type ar check to get the rank? or will it do it itself?

**Comment by Staartvin** [comment]
A player can either force the check by doing **/ar check** or wait for ~5 min. Every 5 min (you can change this in the Settings), Autorank will check players.

**Comment by sharkybushbaby** [comment]
ok thanks for everything thing Staarvin. Youve been a great help

**Comment by Staartvin** [comment]
No problemo, have fun using Autorank!
