### ISSUE TITLE
issue with 4.0.7 Dev 10  exception

### ISSUE THREAD

**Issue by frizzbee30** [Staartvin/Autorank-2#538]
Hi, 1.12.1 latest commit

Appreciate it is a dev version, seems to be working but getting an exception on boot and while running.

Thanks

https://pastebin.com/jBNSzasq

**Comment by Staartvin** [comment]
Autorank will soon require PluginLibrary: https://www.spigotmc.org/resources/plugin-library.17645/
Try downloading that, it doesn't need any configuring.

**Comment by frizzbee30** [comment]
Thanks, figured it was looking for a library, but couldnt find it lol. Dropped it in but getting this on boot?

https://pastebin.com/6Z1cxgPA

sorry, just quickly grabbed it from console so inverted.

Thanks

**Comment by Staartvin** [comment]
Ah, I know why. That version of PluginLibrary is outdated. I can't yet upload a new one, but I can try to set up some development builds for it, so that you can also download the latest version. I can try to fix this somewhere today, hang on for a bit.

**Comment by Staartvin** [comment]
I got it up and running. Try using this version of PluginLibrary: http://178.62.255.148:8080/job/PluginLibrary/2/

**Comment by frizzbee30** [comment]
Hi, thanks for looking at it. Still getting an error with dev build?

https://pastebin.com/ML9Z2xqM

**Comment by Staartvin** [comment]
Hmm, what version of Vault are you running?

**Comment by frizzbee30** [comment]
Hi, noticed this in startup

https://pastebin.com/ddjHzmwA

vault version:
[21:43:54] [Server thread/INFO]: [Vault] Loading Vault v1.5.6-b49

Thanks

**Comment by frizzbee30** [comment]
Hi, I still have an issue with the pluginlibrary loading, and hence lot's of Autorank exceptions?  Thanks  :)

**Comment by frizzbee30** [comment]
pluginlibrary version from 28th appears to fix I think.
