### ISSUE TITLE
Time help!

### ISSUE THREAD

**Issue by kadenmohr** [Staartvin/Autorank-2#543]
I want to make it so a player joins my skyblock server, the said player starts off as a guest, as he plays for a hour or two he will get ranked up to a Member, that member will then go on to play for 3 more days and become trusted, how would I go about setting this up?
Also how would I make it so if someone joins and buys a donor rank but they only have 45 minutes played will they be deranked?

**Comment by Staartvin** [comment]
Please see the wiki for a very detailed explanation. Note that you can create two paths: one from guest to member and one from member to trusted

**Comment by kadenmohr** [comment]
I did check the wiki page I had a very hard time understanding it, I tried using a YouTube turtoial said well but the Sinple Config is gone now.

**Comment by kadenmohr** [comment]
My config looks like this 

Test:
     Prerequisites:
            time: 0d 0h 0m
     Requirements:
            time: 0d 2h 0m
     Results:
         command: manuals &p Member

What should I be changing?

**Comment by kadenmohr** [comment]
The final command was manuadd &p Member my bad I screwed up on typing
