### ISSUE TITLE
Custom description for Requirement not working

### ISSUE THREAD

**Issue by LordDarmix** [Staartvin/Autorank-2#544]
Good evening,

I'm trying to put some custom descritions on my Paths.yml file, but none of them will work.

This is one of the paths I've created:

```
Noble-Terrateniente:
  prerequisites:
    in group: Noble
  requirements:
    time: 40d
    money: 1000000
      options:
        description: 'Be rich as hell'
    votes: 100
      options:
        description: 'Vote a lot!'
  results:
    command: ex run mensaje_ascenso_Terrateniente player:p@&p
    command2: pex user &p group set Terrateniente
  options:
    display name: Noble
    infinite pathing: true
    auto choose: true
```
It just shows the default in lang.yml file while using /ar check.

**Comment by Staartvin** [comment]
Could you try to format your config? I can't see whether you've used the correct indentation.

**Comment by LordDarmix** [comment]
Sorry about that, i just updated it to show correctly.

**Comment by vapecloudbear** [comment]
Bump^ same issue for me as well.

**Comment by Staartvin** [comment]
Working on a fix for next Autorank version!
