### ISSUE TITLE
AR Not Hooking into Jobs

### ISSUE THREAD

**Issue by AlbinoTucan** [Staartvin/Autorank-2#546]
Having trouble trying to get Jobs to hook into Autorank.  Everything else works and I believe the formatting is correct as that is not shooting any errors at me.

AR Version - 4.0.7
Statz Version - 1.4.3
Jobs Version - 4.1.3
Hastebin Settings - https://hastebin.com/osiyolepeg.bash
Hastebin Path Ex. - https://hastebin.com/xoyocukiso.cs

If you need the full config setup let me know.

![screenshot_9](https://user-images.githubusercontent.com/31980346/30508775-86553b56-9a64-11e7-9819-a03c1d6672e6.png)

**Comment by AlbinoTucan** [comment]
Forgot a colon.
GG NO RE

**Comment by AlbinoTucan** [comment]
Found the issue.
Jobs is loading after Statz and AutoRank so it's not picking up the hook.
Reloading Statz and then AutoRank in that order fixes it because AutoRank cannot find Statz if you just reload AutoRank.
Slowdown the load time for your plugin so that it gives other plugins a chance to load in and be hooked in to.

**Comment by Staartvin** [comment]
Thanks for letting me know. I've already been working on this issue, but I'll keep this open until the next release. It should be fixed by then.

**Comment by AlbinoTucan** [comment]
Alright, is it going to all be hooked into that PluginLibrary stuff that you have going on?

**Comment by Staartvin** [comment]
Yes, you are right!

**Comment by AlbinoTucan** [comment]
Fixed in latest updates.  Must have latest Autorank, PluginLibrary and Statz for it to work properly.
Thank you.
