### ISSUE TITLE
Multiple Auto-Choose/Complete Paths

### ISSUE THREAD

**Issue by TheSaltyPug** [Staartvin/Autorank-2#547]
** I AM AWARE THAT YOU SAID SOMEWHERE THIS IS NOT POSSIBLE. I am making this so hopefully it will get added. Let me explain.

Helllo.
On my server, I have 2 types of "groups": time based groups, and kill based groups. So there are 4 Time based groups, which work fine. Then there are kill groups, which the player should be added to a different group when they have a certain amount of player kills.

I realize that both of these paths work. However, they do not work at the same time. What happens if a player on my server reaches the kill threshold for the kill group to rank into the next one, but the plugin is not checking for kills. It is checking for time. I fear that it will have to check through time path before it even starts the kill path.

Can you add a feature to allow all paths to be checked? You coiuld add in the playerdata config a list of paths that the plugin auto checks.

Could you PLEASE add this? 
Else, could you make an option that if one path does not auto complete, it changes to check to other possible path for the next global auto check?
Else, I will have to find a special way to have two instances of the plugin running that have different configs.

Thanks for considering :)

**Comment by Staartvin** [comment]
Could you give your paths file and show me what paths you would want to be merged? I'm never against adding new functionalities, but perhaps it's already possible?

**Comment by TheSaltyPug** [comment]
https://pastebin.com/QMyw7g0F

here is the paths.yml.

So d1_member through d3_trusted are the time ranks, and w1_grunt through w4_general are the kill ranks.

**Comment by Staartvin** [comment]
Yes, instead of 'in group' you can check for 'permission' I believe. Check the wiki to make sure it's the correct syntax ;-)

**Comment by TheSaltyPug** [comment]
Ok, @Staartvin , But then how would I make them both check at the same time?
