### ISSUE TITLE
[Suggestion] /ar rankup to prevent forcing the player to rank up

### ISSUE THREAD

**Issue by AlbinoTucan** [Staartvin/Autorank-2#548]
**Enhancement**
At first glance this may seem like stupid idea and the opposite of the meaning of autorank, but bear with me.  A command that asks players if they wish to rankup rather than forcing it once they have all requirements.  This can be done a few ways or if you have your own idea use it. This is kinda the best one I can think of and would probably be the easiest to add.

When running /ar check add a confirmation once they have completed all requirements.
"You have completed all requirements type: '/ar rankup' to go to the next rank!"

Usage: I would like to be able to remove money from their accounts once they rankup as a sort of price/money sink (This is not the issue as I know I can just run an /eco command to remove money).  The problem I am facing is I don't want them to accidentally spend the money by checking their requirements if they are saving up for something else.

An option could be added in the base config as something like: enable autorankup: true/false

If this is already a feature and I have completely missed it please inform me on how to do it.

**Comment by Staartvin** [comment]
Good suggestion! I see what I can do. :-)
