### ISSUE TITLE
Autorank conflict with CTSNC

### ISSUE THREAD

**Issue by JamesMCL44** [Staartvin/Autorank-2#549]
Hi there, I have found the following possible bug caused by Autorank with CTSNC scoreboard module.
I have tried the following while keep CTSNC Scoreboard running:
- install lower version of autorank --> still got same error message
- disable autorank (which I dont want to) --> no error message

Error message generated upon player join server:
https://pastebin.com/QEW4zW3i

the same/similar error also triggered when player leave server

Please assist in resolving, thanks.

**Comment by Staartvin** [comment]
It seems that CTSNC is probably relying on an older version of Autorank. Maybe provide the developer of CTSNC with this error, as there it's an error from their part ;)

**Comment by Staartvin** [comment]
I'll keep this open for your updates about the issue.

**Comment by JamesMCL44** [comment]
Ok, I will file the same error to them and update you here

**Comment by JamesMCL44** [comment]
Hi there,
The author of CTSNC has provided a snapshot of their plugin which works very well.

This report may be flagged as resolved. Thanks a lot.

**Comment by Staartvin** [comment]
Great to hear he fixed it!
