### ISSUE TITLE
Need help with /ar choose & /ar view llist(not working as intended)

### ISSUE THREAD

**Issue by Dwaynedee** [Staartvin/Autorank-2#550]
Everytime i do /ar view list, it kept saying 'There are no paths that you can choose', when i do /ar check, it says that i currently has no path, and theres no path left to choose. I followed your wiki very closely:

https://github.com/Staartvin/Autorank-2/wiki/Multiple-ranking-paths-for-one-group

This is what my path.yml looks like currently:

https://pastebin.com/75g88HBp)

According to the wiki provided above, it should have shown member when i do /ar view list, can you tell me what is wrong?

**Comment by Dwaynedee** [comment]
I've found the problem, thankyou.

**Comment by Staartvin** [comment]
Good that you solved it yourself!
