### ISSUE TITLE
Multiple Group Support

### ISSUE THREAD

**Issue by Bensirpent07** [Staartvin/Autorank-2#553]
Autorank V4.0.7

I'm currently using PEX as my permissions along with Autorank. The only trouble that I seem to be having is that it seems like Autorank doesn't check multiple groups, only the primary one.
For example: 

Player - Groups: Group1, Builder, Staff

If I weighted Builder as the primary group, Autorank doesn't seem to see that the player is also in Group1 or Staff.

Here is my real example:
If I'm in the group "Stone" and "Builder", Builder is the primary group because of it's weight. However Autorank doesn't consider me being in the Stone group.

Here is my [Paths.yml](https://pastebin.com/P3aXmefm)

**Comment by Staartvin** [comment]
You can change this option in the Settings.yml. Look for the option 'use primary Group of Vault' and set it to false.

**Comment by Bensirpent07** [comment]
Ah ok, I misunderstood that configuration option. Exactly what I'm looking for, appreciate it 👍
