### ISSUE TITLE
Bungeecord mysql time sync doesn't work (v4.1)

### ISSUE THREAD

**Issue by Justos** [Staartvin/Autorank-2#560]
Hello,
we have a bungeecord network with 2 Servers and a mysql database where the time's are saved, the mysql works fine, but it doesn't sync/getting read from the data.yml, we want that on Server 1 and Server 2 the player's have the same time, but it doesn't sync between these 2 servers.

**Comment by JoMW1998** [comment]
i am having a simalar problem autorank 4.1 is not working for me at all even after i place the plugin in to the plugins folder.

**Comment by JoMW1998** [comment]
i am trying to make a good server with plugins and i was successful with most of it till i wanted to use autorank 4.1

**Comment by Staartvin** [comment]
@JoMW1998 You should use the latest version of Autorank.

**Comment by Staartvin** [comment]
@Justos Do you have both your servers pointing to the same mysql database? Are both instances of Autorank using the same database?

**Comment by Justos** [comment]
@Staarvin Yes. I have all servers in same mysql database and it does not work :(

**Comment by Justos** [comment]
it will display different time on each server even though they are in the same mysql dtabase

**Comment by Staartvin** [comment]
What command do you use to show the time of a player?

**Comment by Staartvin** [comment]
Also, have you synced your local data.yml with the database?

**Comment by Staartvin** [comment]
There is a difference between the local server time and the global server time of Autorank.
On each of your server, Autorank keeps track of how many minutes a player has played on that particular server. This is the time in the data.yml. Autorank can also keep track of the data that is played across all servers of the network. That is your global time in the MySQL database. This means that on each server **/ar check** will show the time a player has played on that particular server, while **/ar gcheck** will show you the time the player has played over all servers. This means that the **gcheck** should be (roughly) the same over all servers, while the **check** differs between servers.

Do you understand?

**Comment by Justos** [comment]
Oops. Thanks a lot for your help, but one question. Will the rankings be on all servers?

**Comment by Staartvin** [comment]
What do you mean by rankings?

**Comment by Justos** [comment]
Rank up

**Comment by Justos** [comment]
Rank up on all servers with global time. Sorry im from Finland

**Comment by Staartvin** [comment]
If you are using a rankup with global time, then yes, it will be on all servers.

**Comment by Justos** [comment]
Thank you!
