### ISSUE TITLE
AutoRank Paths file finished an still same error

### ISSUE THREAD

**Issue by Jager67** [Staartvin/Autorank-2#562]
Ok I've setup the Paths.yml file an I still got an issue it seems. I'm running 1.7.10 version of MC and Autorank-3.8.5.1 version.

https://pastebin.com/1NJUu38Y

Here is my Latest Log file.

https://pastebin.com/i3LSVAwU

**Comment by Staartvin** [comment]
Hmm, it seems you are using the paths file, but that was only introduced in Autorank v4. Since you are running a lower version, you should use the Advanced Config. That's where the error is coming from. See the wiki for a tutorial on the advanced config. Look for Autorank 3.

**Comment by Jager67** [comment]
Here my Advanced Config it seems right but I'm probably wrong.
https://pastebin.com/7d9K8pEr

**Comment by Jager67** [comment]
Here's the error I'm getting, I have been able to get rid of all errors besides this one.
https://pastebin.com/B8i5HbFG
My PEX groups are all the same names as the advanced config file.
Here's my advance config: https://pastebin.com/DEtsgDca
Heres my PEX config: https://pastebin.com/WjTn7F3B

**Comment by Staartvin** [comment]
You have OVERALORD in the advanced config, while there is OVERLORD in your PEX config. Those are different.

**Comment by Jager67** [comment]
Awesome Thanks I've been looking at these configs like crazy I can't believe I missed that.
