### ISSUE TITLE
Fatal 4.1 Flaw

### ISSUE THREAD

**Issue by Fordy436** [Staartvin/Autorank-2#563]
Plugin won't even load with the 4.1 version.

`19.11 16:35:26 [Server] ERROR Could not load 'plugins/Autorank-4.1.jar' in folder 'plugins'
19.11 16:35:26 [Server] INFO org.bukkit.plugin.UnknownDependencyException: PluginLibrary
19.11 16:35:26 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:216) [spigot101.jar:git-Spigot-99c2a37-3819f8d]
19.11 16:35:26 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:302) [spigot101.jar:git-Spigot-99c2a37-3819f8d]
19.11 16:35:26 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:747) [spigot101.jar:git-Spigot-99c2a37-3819f8d]
19.11 16:35:26 [Server] INFO at org.bukkit.Bukkit.reload(Bukkit.java:525) [spigot101.jar:git-Spigot-99c2a37-3819f8d]
19.11 16:35:26 [Server] INFO at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot101.jar:git-Spigot-99c2a37-3819f8d]
19.11 16:35:26 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot101.jar:git-Spigot-99c2a37-3819f8d]
19.11 16:35:26 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot101.jar:git-Spigot-99c2a37-3819f8d]
19.11 16:35:26 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [spigot101.jar:git-Spigot-99c2a37-3819f8d]
19.11 16:35:26 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [spigot101.jar:git-Spigot-99c2a37-3819f8d]
19.11 16:35:26 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot101.jar:git-Spigot-99c2a37-3819f8d]
19.11 16:35:26 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot101.jar:git-Spigot-99c2a37-3819f8d]
19.11 16:35:26 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot101.jar:git-Spigot-99c2a37-3819f8d]
19.11 16:35:26 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
19.11 16:35:26 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
19.11 16:35:26 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot101.jar:git-Spigot-99c2a37-3819f8d]
19.11 16:35:26 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot101.jar:git-Spigot-99c2a37-3819f8d]
19.11 16:35:26 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot101.jar:git-Spigot-99c2a37-3819f8d]
19.11 16:35:26 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot101.jar:git-Spigot-99c2a37-3819f8d]
19.11 16:35:26 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot101.jar:git-Spigot-99c2a37-3819f8d]`

**Comment by Staartvin** [comment]
You should also download PluginLibrary, look on Spigot for the link, as I can't browse the Internet right now.

**Comment by Fordy436** [comment]
Ok. If it's a requirement it might be an idea adding it to the spigot plugin page as there is no mention of it
