### ISSUE TITLE
Auto-Rank is not functioning.

### ISSUE THREAD

**Issue by K-21** [Staartvin/Autorank-2#564]
Hi,

Replaced the .jar file with the newly updated version and the plugin now stops working.

I'd also like to know if it's possible to sync actual player-game time with playtime, as it currently only tracks from when the plugin was installed. I also don't want to lose the config I have currently set up. Cheers in advance.

**Comment by PetrichorCraft** [comment]
I don't know of a way to sync the times, sorry. 

But about the new version, I had that error as well. After looking at the error, I saw that you needed to install [Plugin Library](https://www.spigotmc.org/resources/plugin-library.17645/), and it works fine now. I hope this helps.
