### ISSUE TITLE
Many exception executing task errors.

### ISSUE THREAD

**Issue by BroMayo** [Staartvin/Autorank-2#567]
Hey Staartvin, i really appreciate your plugin and your hard work. I am currently setting up a 1.12.2 bukkit server using Autorank 4.1, Jobs, McMMO, PEX, Statz, Vault and the PluginLibrary.

Autorank is continually throwing exception errors for:
task 43, 32, 37, executing /ar check ect..

If you have any help/advice for me i would greatly appreciate it, thank you!

**Comment by BroMayo** [comment]
Sorry i do not know why the format is so bad.

**Comment by Staartvin** [comment]
Please use pastebin.com for the files. Also, could you give the exact error it throws, with stack trace please.

**Comment by BroMayo** [comment]
exception 37:
https://pastebin.com/ncDWZy7U
32:
https://pastebin.com/YTcu7j8F
when doing /ar check
https://pastebin.com/xpATXVyK
52:
https://pastebin.com/B1iVJ6zc
and here is my path and setting files
path:
https://pastebin.com/dE6ub2p4
settings:
https://pastebin.com/E6zkM0uW

Thank you for the timely reply!

**Comment by BroMayo** [comment]
if it does happen to be the statz plugin do you know of any alternative stat plugins that would link mcmmo stats with autorank?

**Comment by BroMayo** [comment]
Well i moved over to spiggot and it all seems to be working now thanks friend!
