### ISSUE TITLE
could not load.. ?

### ISSUE THREAD

**Issue by Ezhax** [Staartvin/Autorank-2#571]
22.12 22:35:46 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
22.12 22:35:46 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
22.12 22:35:46 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
22.12 22:35:46 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:308) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
22.12 22:35:46 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:216) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
22.12 22:35:46 [Server] INFO org.bukkit.plugin.UnknownDependencyException: PluginLibrary
22.12 22:35:46 [Server] ERROR Could not load 'plugins/Autorank-4.1.jar' in folder 'plugins'

**Comment by Kuouo** [comment]
Download PluginLibrary and add it to your plugins server. Restart the server.
