### ISSUE TITLE
No Simple/Advance config generated?

### ISSUE THREAD

**Issue by SaltedBiscuit** [Staartvin/Autorank-2#575]
Version 4.1
Running Spigot 1.12.2 on the server:
when i restart the server the Autorank folder is generated.

But internalprops, paths, and settings are the only YML files generated.
I added my own SimpleConfig.yml but im not sure if the plugin is using them.

Also, it doesnt seem to recognise i exist when i do /ar check SaltedBiscuit
EDIT: "SaltedBiscuit is excluded from ranking"

**Comment by TeenWolf23** [comment]
I had the same thing happen, so I tried to set it up with MySQL and it kept saying the information was incorrect so I gave up.

**Comment by PurelyAliyah** [comment]
There isn't a simple config or advanced config anymore, Everything is done through the path's file.

**Comment by Staartvin** [comment]
Closing because answer has been provided.
