### ISSUE TITLE
Trying To Rank Upon Playtime.. Getting This

### ISSUE THREAD

**Issue by KensonPlays** [Staartvin/Autorank-2#576]
Screenshot hosted on Drive.

https://drive.google.com/a/kensonplays.com/uc?id=1h9zKci-YY5a5KvJsmlHSV8mDMK6AezV3

**Comment by vapecloudbear** [comment]
https://github.com/Staartvin/Autorank-2/wiki/Requirements-&-Results#requirements

Look at the example. You have to remove the percent signs on line 17. If you want no value there. Just replace the % with 0

Btw, great job posting the screenshot. That or logs help pinpoint issue quickly.
