### ISSUE TITLE
Can I add two values for a result?

### ISSUE THREAD

**Issue by huangwarrior** [Staartvin/Autorank-2#579]
Like title says.
I tried this in paths/yml   

----------------------------------- 
Example: (Didn't work)

pathTEST:
    prerequisites:
        in group:
            value: "default"
    requirements:
        time:
            value: "8h"
    results:
        command:
            **value**: 'lp user &p group set veteran'
            **value**: 'f powerboost player &p 2'
        message:
            value: '&6You have been promoted to &7veteran&6, &p'

**Comment by huangwarrior** [comment]
SOLVED!

Instead of this:
command:
value: 'lp user &p group set veteran'
value: 'f powerboost player &p 2'

This:
command: 'lp user &p group set veteran'
command2: 'f powerboost player &p 2'

I think you should add examples of adding different values for a prequisite/result in the example section of the wiki.

**Comment by vapecloudbear** [comment]
Bump^ Close
