### ISSUE TITLE
MyCommand Issue (minecraft)

### ISSUE THREAD

**Issue by alemuradas1328** [Staartvin/Autorank-2#581]
Hey guys, im fixing my server bugs and erros and i dont know what is this or how to fix
(obs: my server is 1.5.2 and the plugin is for the last version anyway if there is a way to fix im accepting TNKS)

21.01 14:23:05 [Server] SEVERE Exception in thread "Craft Scheduler Thread - 182" 
21.01 14:23:05 [Server] SEVERE org.apache.commons.lang.UnhandledException: Plugin MyCommand v5.3.4 generated an exception while executing task 37
21.01 14:23:05 [Server] INFO at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
21.01 14:23:05 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
21.01 14:23:05 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
21.01 14:23:05 [Server] INFO at java.lang.Thread.run(Unknown Source)
21.01 14:23:05 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()Ljava/util/Collection;
21.01 14:23:05 [Server] INFO at it.mri.mcstats.MetricsLite.postPlugin(MetricsLite.java:286)
21.01 14:23:05 [Server] INFO at it.mri.mcstats.MetricsLite.access$3(MetricsLite.java:279)
21.01 14:23:05 [Server] INFO at it.mri.mcstats.MetricsLite$1.run(MetricsLite.java:174)
21.01 14:23:05 [Server] INFO at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:58)
21.01 14:23:05 [Server] INFO at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
21.01 14:23:05 [Server] INFO ... 3 more

**Comment by Staartvin** [comment]
This is not an error from Autorank, please contact the developer(s) of MyCommand instead.
