### ISSUE TITLE
Bad Packet ID

### ISSUE THREAD

**Issue by alemuradas1328** [Staartvin/Autorank-2#582]
Hey guys, im using spigot 1.5.2 in my minecraft server, if anyone know what is and how to fix pls tell me ! tnks

21.01 14:35:28 [Server] SEVERE io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 109
21.01 14:35:28 [Server] SEVERE at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:393)
21.01 14:35:28 [Server] SEVERE at io.netty.handler.codec.ByteToMessageDecoder.messageReceived(ByteToMessageDecoder.java:138)
21.01 14:35:28 [Server] SEVERE at io.netty.channel.DefaultChannelHandlerContext.invokeMessageReceived(DefaultChannelHandlerContext.java:379)
21.01 14:35:28 [Server] SEVERE at io.netty.channel.DefaultChannelHandlerContext.fireMessageReceived(DefaultChannelHandlerContext.java:364)
21.01 14:35:28 [Server] SEVERE at io.netty.handler.timeout.ReadTimeoutHandler.messageReceived(ReadTimeoutHandler.java:150)
21.01 14:35:28 [Server] SEVERE at io.netty.channel.DefaultChannelHandlerContext.invokeMessageReceived(DefaultChannelHandlerContext.java:379)
21.01 14:35:28 [Server] SEVERE at io.netty.channel.DefaultChannelHandlerContext.fireMessageReceived(DefaultChannelHandlerContext.java:364)
21.01 14:35:28 [Server] SEVERE at io.netty.channel.DefaultChannelPipeline.fireMessageReceived(DefaultChannelPipeline.java:786)
21.01 14:35:28 [Server] SEVERE at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:120)
21.01 14:35:28 [Server] SEVERE at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:489)
21.01 14:35:28 [Server] SEVERE at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:464)
21.01 14:35:28 [Server] SEVERE at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:358)
21.01 14:35:28 [Server] SEVERE at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
21.01 14:35:28 [Server] SEVERE at java.lang.Thread.run(Unknown Source)
21.01 14:35:28 [Server] SEVERE Caused by: java.io.IOException: Bad packet id 109
21.01 14:35:28 [Server] SEVERE at org.spigotmc.netty.PacketDecoder.decode(PacketDecoder.java:47)
21.01 14:35:28 [Server] SEVERE at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:356)
21.01 14:35:28 [Server] SEVERE ... 13 more
21.01 14:35:28 [Server] SEVERE io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 97
21.01 14:35:28 [Server] SEVERE at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:393)
21.01 14:35:28 [Server] SEVERE at io.netty.handler.codec.ReplayingDecoder.channelInactive(ReplayingDecoder.java:326)
21.01 14:35:28 [Server] SEVERE at io.netty.channel.DefaultChannelHandlerContext.invokeChannelInactive(DefaultChannelHandlerContext.java:262)
21.01 14:35:28 [Server] SEVERE at io.netty.channel.DefaultChannelHandlerContext.fireChannelInactive(DefaultChannelHandlerContext.java:248)
21.01 14:35:28 [Server] SEVERE at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:77)
21.01 14:35:28 [Server] SEVERE at io.netty.handler.timeout.ReadTimeoutHandler.channelInactive(ReadTimeoutHandler.java:144)
21.01 14:35:28 [Server] SEVERE at io.netty.channel.DefaultChannelHandlerContext.invokeChannelInactive(DefaultChannelHandlerContext.java:262)
21.01 14:35:28 [Server] SEVERE at io.netty.channel.DefaultChannelHandlerContext.fireChannelInactive(DefaultChannelHandlerContext.java:248)
21.01 14:35:28 [Server] SEVERE at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:762)
21.01 14:35:28 [Server] SEVERE at io.netty.channel.AbstractChannel$AbstractUnsafe$4.run(AbstractChannel.java:566)

**Comment by Staartvin** [comment]
What version of Autorank are you using?
