### ISSUE TITLE
AR 4.1 Unable to see Path

### ISSUE THREAD

**Issue by Josh19992016** [Staartvin/Autorank-2#584]
Hello, I am using AR 4.1 and am struggling to get it setup correctly even with 1 extra rank, with the default config it creates, using "/ar view list" shows "Test path". When I input my rank "Zombie" and upload to server then reload, "Zombie" doesn't show and I see nothing wrong with the config and a few others also see no problem. I have tried to re install the plugin multiple times with no success. 

Here is the config: https://hastebin.com/yeliruhiwo.pas

Test:
  prerequisites:
    world: world_nether
    money: 1000
  requirements:
    money: 10000
    blocks broken: 50
  results:
    command: broadcast &p has just completed path 'Default'!
    command2: give &p 1 100
    command3: 'lp user &p switchprimarygroup default'
    message: Congratulations, you completed the 'Default' path!
  options:
    display name: Test path
	
Zombie:
  prerequisites:
    world: world_nether
  requirements:
    blocks broken: 1000
  results:
    command: broadcast &p has just completed path 'Zombie'!
    command2: give &p 1 100
    command3: 'lp user &p switchprimarygroup Zombie'
    message: Congratulations, you completed the 'Zombie' path!
  options:
    display name: Zombie Bait

**Comment by vapecloudbear** [comment]
Are you switching groups altogether, or promoting the player from default to zombie. If so, the better way would be to create a track in luckperms and do lp user &p promote (track name here). That way the player doesn’t have 2 separate parents. Also
