### ISSUE TITLE
1.12.2 version with pluginlibary 1.1 and autorank 4.1 ERROR

### ISSUE THREAD

**Issue by sch00lb0yq** [Staartvin/Autorank-2#591]
ERROR Requirement 'blocks broken' relies on 'Statz' being installed, but that plugin is not installed!
01.02 12:31:19 [Server] WARN Autorank has some warnings for you: 
01.02 12:31:19 [Server] WARN (Priority 10) 'Requirement 'blocks broken' relies on 'Statz' being installed, but that plugin is not installed!'

**Comment by TomekkStorm** [comment]
Hi,
i've got the same message. You have to install the plugin "Statz"
