### ISSUE TITLE
Time not being tracked for anyone

### ISSUE THREAD

**Issue by jdk789** [Staartvin/Autorank-2#594]
I installed this plugin yesterday and I love it however it appears that the time a player has played is not being tracked. I am currently having to manually add there time based on there statistics page and i am unsure as to why it is not doing this automatically like it should. I haven't really changed any configs apart from the ranks available. Do I need to install a separate plugin to track the time played?

**Comment by Staartvin** [comment]
No, Autorank should automatically track time. If you do /ar check, what does it show?

**Comment by jdk789** [comment]
When I run that command it shows the time that I have added manually. If i check in say 1 hours time it still shows the old time. No new time is being added
Also when i do /ar time it shows 0 hours - 0 days on all time frames

**Comment by Staartvin** [comment]
Can you turn on debug mode in the settings? Then, let Autorank run for a bit and make sure to have a few players on for at least 20 minutes. Afterwards, post the log of your console here (using pastebin or something like that).

**Comment by jdk789** [comment]
will do that now. there will only be 2 players online right now but hopefully that will be enough

**Comment by Staartvin** [comment]
Should be enough. They should not be OPs though.

**Comment by jdk789** [comment]
I will deop myself for a while. what about having the * permission?

**Comment by Staartvin** [comment]
Being OP or having the * permission may disable the tracking of time. Therefore, you might want to check time of other players.

**Comment by jdk789** [comment]
ok. i will remove that rank from myself and my alt for now

**Comment by jdk789** [comment]
https://pastebin.com/G8ZqDjPi
this is the last 30 mins of logs.

**Comment by Staartvin** [comment]
Hmm, it seems that when Autorank wants to update the playtime of a player, it cannot do this because it requires Statz for it to work. You either need to download Statz or update Autorank, because the newer versions of Autorank don't need Statz anymore.

**Comment by jdk789** [comment]
i will see if there is a newer version to what I have. thank you

**Comment by jdk789** [comment]
what is the most recent version of the plugin please. It appears I am using the most recent available on Bukkit and spigot

**Comment by Staartvin** [comment]
On Spigot, the most recent version is 4.1. You are using v3.8.5.1

**Comment by jdk789** [comment]
Hey, I installed the newer version and it just failed to work. I also tried going back to the 3.8.5.1 version with Statz plugin but that wouldnt work just responded with an internal error whenever I try to do /ar check

**Comment by Staartvin** [comment]
Can you give me the error when you run the newer version of Autorank?

**Comment by SkyCrafterYT** [comment]
When you install Autorank 4.1, make sure you also use the plugin "PluginLibrary". This is assuming Autorank isn't even loading like it did for me.

https://www.spigotmc.org/resources/plugin-library.17645/
