### ISSUE TITLE
AutoRank : %autorank_time_of_player%

### ISSUE THREAD

**Issue by TheIntelloBox** [Staartvin/Autorank-2#596]
Hey ! :D 

The placeholder of AutoRank : %autorank_time_of_player% is useless because on my scoreboard the time played is in seconds... So I have 7000000 seconds... How can I change that ? :D

Thanks ! :D

**Comment by Staartvin** [comment]
Hmm, you should contact the author of placeholder api! That's extended_clip :). Autorank can't do anything about this issue.
