### ISSUE TITLE
Having trouble with rank-change result.

### ISSUE THREAD

**Issue by SkyCrafterYT** [Staartvin/Autorank-2#601]
My Autorank keeps spamming me with https://i.imgur.com/NNmkYJy.png. Please help! https://i.imgur.com/doNIyxE.png

**Comment by Staartvin** [comment]
You are using a 'rank change' result, but that is not supported in the latest version of Autorank. You should use a command result that changes the permission group of a player.

**Comment by SkyCrafterYT** [comment]
Thank you! I will manually change it!
