### ISSUE TITLE
Remove Spigot specific API usage

### ISSUE THREAD

**Issue by MsDemonicRaven** [Staartvin/Autorank-2#602]
It's telling me its not up to date even though i just downloaded the plugin today. 

not sure whats going on....but i need this plugin for autorank. Please help or find a way to update it so it will load and not give the (is it up to date?) error.

https://pastebin.com/HubHBDpE

**Comment by MsDemonicRaven** [comment]
Also, it looks like plugin library doesn't support Statz 1.4.5. It says on the page it support 1.4.4.

**Comment by Staartvin** [comment]
Hmm, you are not using Spigot, right?

**Comment by MsDemonicRaven** [comment]
Nope. I have craftbukkit.

**Comment by Staartvin** [comment]
Could you try [this](http://178.62.255.148:8080/job/Statz/30/) build for Statz and [this one](http://178.62.255.148:8080/job/PluginLibrary/13/) for PluginLibrary?

**Comment by MsDemonicRaven** [comment]
statz is still giving me the (is it up to date?) error

https://pastebin.com/KNU7c5qc

**Comment by Staartvin** [comment]
Hmm. I'll need some time to fix this, as it requires me to overhaul the message module.

**Comment by MsDemonicRaven** [comment]
OK no problem. I'll be waiting ^^
