### ISSUE TITLE
Issue with /ar complete #

### ISSUE THREAD

**Issue by Gunnthorian** [Staartvin/Autorank-2#603]
I have my rankup system to rankup based on money and I have auto ranking dissabled.

when ever a user tries to type /ar complete 1 (theres only one requirement) the server spits back:

You do not meet requirements for #1:
Have at least 15000.0 Dollars
Current: 16255.4/15000.0 Dollars

**Comment by Staartvin** [comment]
What happens if you temporarily enable auto ranking? Will the requirement then pass?

**Comment by Gunnthorian** [comment]
Just tested it and changing:
```
requirements:
    money:
      value: 15000
      options:
        auto complete: false
```

to:
```
requirements:
    money:
      value: 15000
      options:
        auto complete: true
```

did the trick but I can't have the auto ranking system taking someone's money if they don't want to rank up. 

That was the only auto checking setting/option I found across both the Settings.yml and the Paths.yml 

typing /ar check didn't rank the user up but after changing that setting the user was able to type /ar check and rank up but sadly would also automatically rank up the user.

**Comment by Staartvin** [comment]
So, to be clear. You tested the _auto complete: true_ **and** _auto complete: false_, both with _automatic ranking: false_ (in Settings.yml) and it didn't work in both scenarios?

**Comment by Gunnthorian** [comment]
Am I missing something, I can't seem to find anything about ```automatic ranking: false``` as an option in `settings.yml`, there's `disable automatic path checking: false` but that will still auto rank players when they log in.

**Comment by Gunnthorian** [comment]
@Staartvin where was this other setting located? I'm really trying to get player ranking automated

**Comment by Staartvin** [comment]
Wait, can you give me your Settings.yml config?

**Comment by Gunnthorian** [comment]
```# 
#                                                                           #
#                   Autorank Settings                                       #
#                                                                           #
#   This config is used to configure Autorank. The other configs provide    #
#   a way to configure the rank system. This config is for configuring the  #
#   the options Autorank has to offer you                                   #
#                                                                           #
afk integration: true
use partial completion: true
interval check: 5
use time of: Autorank
leaderboard layout: '&6&r | &b&p - &7&d %day%, &h %hour% and &m %minute%.'
leaderboard length: 5
check command layout: '&p has played for &time and is on path ''''&path''''. Requirements
  to be ranked up: &reqs'
sql:
  enabled: false
  hostname: localhost:3306
  username: root
  password: ''
  database: minecraft
  table: autorank
auto-updater:
  check-for-new-versions: false
advanced dependency output: false
show help command based on permission: true
use debug: true
show warnings: true
use primary group for vault: true
broadcast resetting of data files: true
use global time in leaderboard: false
disable automatic path checking: false
automatically archive old data: true
```
