### ISSUE TITLE
Issue with /ar convert advancedconfig.

### ISSUE THREAD

**Issue by TheIntelloBox** [Staartvin/Autorank-2#606]
Hey,

I converted this : https://pastebin.com/NPA56kf8 
And it gave me this : https://pastebin.com/2Gv78BWY

But when I connect, it says : https://image.noelshack.com/fichiers/2018/10/3/1520448478-bug.jpg

**Comment by TheIntelloBox** [comment]
@Staartvin

**Comment by TheIntelloBox** [comment]
Please omg.

**Comment by TheIntelloBox** [comment]
1 month and still no answer.

**Comment by TheIntelloBox** [comment]
Hey,

Paths.yml : https://pastebin.com/Gr0XL0cJ

But the rank of my players doesn't change.

**Comment by Staartvin** [comment]
Is this the converted paths.yml file? This is not in the format of the paths.yml file. See for example https://github.com/Staartvin/Autorank-2/blob/master/Paths.yml

**Comment by Staartvin** [comment]
The paths seem to be correct. Is there a certain path that is not working correctly?

**Comment by TheIntelloBox** [comment]
All : the players have the time required but they don't have the next rank. And there is twice the path "Citoyen" and "Vicomte".

**Comment by Staartvin** [comment]
Could you give me your Autorank folder?

**Comment by TheIntelloBox** [comment]
Have you got Skype or Discord that's faster ?

**Comment by Staartvin** [comment]
Yeah, sure. https://discord.gg/QjYHBfA. Note that I'll be away for two hours and will be back after that.
