### ISSUE TITLE
Could not find /data/Daily_time.yml, so didn't back up

### ISSUE THREAD

**Issue by iWessa** [Staartvin/Autorank-2#607]
Hi I'm using this plugin and I REALLY love it, no joke!
Since today i'm getting a warning about not backing up.
[Warning pastebin](https://pastebin.com/sdkYLpW2)

I'm using the latest version of this plugin and using 1.12.2 mcserver.

I hope you can help me <3

Kind regards,

iWessa

**Comment by Staartvin** [comment]
This issue sometimes pops up, but there is no error. Don't worry about it ;-)
