### ISSUE TITLE
Generated an exception while executing task 86

### ISSUE THREAD

**Issue by iWessa** [Staartvin/Autorank-2#608]
Hi,
I freaking love this plugin but it gives a warning:
[pastebin](https://pastebin.com/R1LXVUTL)

If you need to know anything, just ask :)

Regards,

iWessa

**Comment by iWessa** [comment]
Hi again,

This is also an warning I receive in my CLI when joining:
[pastebin2](https://pastebin.com/620FGQJ6)

Please respond! <3

**Comment by Staartvin** [comment]
Can you show me your paths file (and update to Autorank 4.2.2)?
