### ISSUE TITLE
When i do /ar check i dont wish To view the next rank but the actual rank

### ISSUE THREAD

**Issue by ClearRelic24** [Staartvin/Autorank-2#610]
How to modify this?
I am i the rank Ancien and the next rank is Legend but the Autorank Write
Actualy, The text is: 

> ClearRelic24 has played for 25 jours, 14 hours, 20 minutes and 13 seconds and is on path ''Legend''. Requirements to be ranked up: 
>  ------------ 
> 1. Play for at least 50 day

But what i want is: 

> ClearRelic24 has played for 25 jours, 14 hours, 20 minutes and 13 seconds and is on path ''Ancien''. Requirements to be ranked up: 
>  ------------ 
> 1. Play for at least 50 day
> 

Can you help me Please

**Comment by Staartvin** [comment]
Can you show me your paths file (of Autorank) and your permissions file?

**Comment by Staartvin** [comment]
Closed due to inactivity.
