### ISSUE TITLE
combine math / "total" option

### ISSUE THREAD

**Issue by CaszGamerMD** [Staartvin/Autorank-2#611]
Give us the ability to add up all the different statz per world as well as in general
Blocks broken in world (adds up all blocks from world)
Stone blocks (Adds all stone from all worlds)

command wise it could look like this
/statz wlist PLAYER STAT WORLD
/statz tlist PLAYER STAT ID:DATA

**Comment by Staartvin** [comment]
That's a good suggestion. I'll work on that!
