### ISSUE TITLE
math in requirements

### ISSUE THREAD

**Issue by CaszGamerMD** [Staartvin/Autorank-2#614]
is it possible to have a requirement be 1000 spiders set up like
(CAVE_SPIDER+SPIDER=1000) ?

**Comment by Staartvin** [comment]
As of now, that is not possible.

**Comment by CaszGamerMD** [comment]
what if you made a section in config for COMBINED STATZ, and there we could name a variable "SpiderTotal" and its children "Spider" + "Cave Spider" then it would make a variable where it takes
KILLS_MOBS_SPIDER and KILLS_MOBS_CAVE_SPIDER and returns the total to given variable's name
example:


`SpiderTotal:
  mobs killed:
    value: SPIDER
  mobs killed2:
    value: CAVE_SPIDER`
