### ISSUE TITLE
Add additional requirements based on Statz data.

### ISSUE THREAD

**Issue by CaszGamerMD** [Staartvin/Autorank-2#615]
idk how hard it is, but it would be awesome if more of the Statz info can be used as Reqs.

**Comment by Staartvin** [comment]
What requirements would you want to see?

**Comment by CaszGamerMD** [comment]
I want to use eggs thrown and trades, but I think you may as well expand to
add much of statz as you can.

By doing so, auto rank can even be used as a challenge plugin
