### ISSUE TITLE
BattleLevels requirements not recognized

### ISSUE THREAD

**Issue by coletam** [Staartvin/Autorank-2#616]
AutoRank doesn't seem to be recognizing BattleLevels and/or the requirements needed. 

Using...
- AutoRank v4.1
- PluginLibrary v1.1
- Statz v1.4.5
- BattleLevels v8.2.2
- PaperSpigot #1380 (MC 1.12.2)

**Example of the paths.yml setting:**
```
RANK_NAME_2:
  prerequisites:
    in group: RANK_NAME_1
  requirements:
    time: 12h
    money: 12500
    battlelevels kills: 5
  results:
    command: pex promote &p normal
  options:
    display name: RANK_NAME_2
    auto choose: true
```

However, when using "battlelevels kills", the following is alerted in console: 

> 09.04 15:31:17 [Server] INFO [Autorank] Found Statz plugin: Statz (by Staartvin)
> 09.04 15:31:17 [Server] INFO [Autorank] Hooked into Statz (by Staartvin)
> 09.04 15:31:17 [Server] INFO [Autorank] Loaded libraries and dependencies
> 09.04 15:31:17 [Server] WARN [Autorank] Autorank has some warnings for you: 
> 09.04 15:31:17 [Server] WARN [Autorank] (Priority 10) 'You are using a 'battlelevels kills' requirement in path 'RANK_NAME_2', but that requirement doesn't exist!'

I've tried different variations of the requirement ID (battlelevel kills, battlelevels_kills, battle_levels kills, etc) but none seems to work. 

Any help would be appreciated. Thank you!

**Comment by Staartvin** [comment]
Hmm, that's an odd bug. I'll check it out.

**Comment by Staartvin** [comment]
Upon further inspection, it seems you are using a version of Autorank that does not have 'battelevels' requirements yet, as can be seen from the error message: _You are using a 'battlelevels kills' requirement in path 'RANK_NAME_2', but **that requirement doesn't exist**!_

**Comment by coletam** [comment]
Ah, I see. I wasn't aware that BattleLevels was added after the latest version on Spigot. I'll try the dev build, thanks!

**Comment by Staartvin** [comment]
Issue fixed.
