### ISSUE TITLE
Import playtime from the player statistics

### ISSUE THREAD

**Issue by MAH1987** [Staartvin/Autorank-2#618]
Hy, 

is there a way to store the playtime from the player statistics to autorank?
Our server is many years online and we want now use autorank.
But we have to import the playtime on each server from the player statistics.

Any help would be appreciated. Thank you!

**Comment by Staartvin** [comment]
Hmm, I think this is not possible yet, but I can work on this!

**Comment by Staartvin** [comment]
This has now been added in Autorank v4.2.2!
