### ISSUE TITLE
PlayerPoints Support

### ISSUE THREAD

**Issue by TigerTBN** [Staartvin/Autorank-2#621]
Hello, amazing developers,

I want to suggest this and this one thing only.
PlayerPoints is a great plugin to be supportive with AutoRank. So much server owners can do if it was.

Is it possible for PlayerPoints to be supported? I tried alot of ways and tricks but didn't work out so I'm now trying to contact the developers.

Thank you for the amazing work.

**Comment by Staartvin** [comment]
Thanks! Can you link the Player Points website, because there are multiple. Also, what would you like to see supported of Player Points?

**Comment by TigerTBN** [comment]
Hello,

This is the main plugin and everything about it.
https://dev.bukkit.org/projects/playerpoints

Also, I would like for the Points to be supported.
With points, I mean the points gained from the plugin itself.
The plugin is based on giving points to players when they do something (Anything)
So when a player reaches that amount of points he will rank up.
It is like an economy plugin but it's not using {$}.

- For example:
`memberplus:
  prerequisites:
    in group: member
  requirements:
    player points: 1000
  results:
    command: broadcast &3&p &bhas been promoted to [Memberplus]! Now they can do /back and
      even more. Good luck!
    command1: pex user &p group add member+
    command2: msg &p You are now a Member+! Congrats
  options:
    display name: memberplus`

Thanks for the fast reply.
Thanks for everything.

**Comment by Staartvin** [comment]
Introduced in Autorank v4.2!
