### ISSUE TITLE
autorank murdered itself and cant rollback

### ISSUE THREAD

**Issue by Kbryst** [Staartvin/Autorank-2#625]
I tried the latest autorank and statz (with plugin library). Autorank has quite a few errors. Players cant do /ar check anymore and their stats on /ar track keep rolling backwards. 

I tried every ar version down to 1.4 and I can no longer get ANY auto rank version to work for me. Yes when I rolled down I rolled down to the correct statz. 

It says theres no mcmmo installed and then at 1.4.3 and below it will start saying no statz installed. 

I even reset the files, I did everything I could, it won't work correctly anymore.

Paper spigot 1.12.2

All the errors for v4.2.1:

https://pastebin.com/1AWvrAiz

Also another note, I noticed when I ran the 4.2.1 with latest stats/pluginlib the GB useage on the server was going up to 60%, where normally it would never go past 15% with three times as many people on. about 32gb allocated, shouldn't ever go that high. I don't have more info besides what saw for a little bit.

**Comment by Staartvin** [comment]
Can you provide me your paths file?

**Comment by Staartvin** [comment]
BTW, I like the name of this issue ;)

**Comment by Kbryst** [comment]
I was actually able to get it working again. I'm not sure how I did it... it just... fixed itself lol. I redid the statz versions a few times. 

Do you still need the path file?

**Comment by Staartvin** [comment]
If all is well and you don't need any help, then I can close the issue and I don't need your path file haha ;)
