### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by PortGasMC** [Staartvin/Autorank-2#626]
updated:
autorank
plugin library
statz

updated all to the latest build
using spigot 1.12.2

https://pastebin.com/gRPqRK83

**Comment by Staartvin** [comment]
Please provide your paths file and your permissions groups file.

**Comment by Staartvin** [comment]
You are using Vault and PEX?

**Comment by PortGasMC** [comment]
yes both of them

**Comment by Staartvin** [comment]
Okay, very well, let me investigate.

**Comment by PortGasMC** [comment]
thanks

**Comment by Staartvin** [comment]
Can you try this version: http://178.62.255.148:8080/job/Autorank/48/

**Comment by PortGasMC** [comment]
its working thanks a lot
