### ISSUE TITLE
Path per world won't work.

### ISSUE THREAD

**Issue by jariojose** [Staartvin/Autorank-2#629]
Path.yml

https://pastebin.com/Dpq2RkXC

I am Builder.

If I am at spawn (world test) and break 25 grass block (2;25), its works fine. But, If I am at spawn, prereqs OK, auto choose OK. 

So, I go to other world (world1), and break 25 grass block, I earn the promotion.... Its a Bug with a query or a conditional clause.

I am using GroupManager, Statz and Autorank-2 both with MySQL.

**Comment by jariojose** [comment]
Why Autorank not work with Stats? Only Statz ?

**Comment by Staartvin** [comment]
Thanks for pointing out the issue, I'll add it to my to do list.

I'm slowly phasing out support for Stats as it is not being updated anymore and is becoming increasingly buggy.

**Comment by jariojose** [comment]
nice! I am waiting for you fix! :+1:

**Comment by jariojose** [comment]
One more question: Is possible work with Statz being used by Autorank and a ScoreBoard that I am developing? Because when I run both into plugin folders, or Scoreboard or Autorank works...


Is the Wiki Statz is recent?

**Comment by Staartvin** [comment]
Autorank should work with any other plugin simultaneously.

**Comment by Staartvin** [comment]
The Statz wiki is relatively recent, but I'll update it tonight.

**Comment by jariojose** [comment]
@Staartvin Do you have any prediction about when you will fix it? 

Sorry to question you. I know that you have a lot of work to do.
Thank you, man!

**Comment by Staartvin** [comment]
Hmm. I ran into an issue. You want me to update the Statz wiki, but with what?

**Comment by jariojose** [comment]
No. Statz Wiki is fine! But, I need that you fix the Path mission per world. Because when I started the mission in a specific world, World_1, and go to another world, World_2, I can continue the mission. For example, break 100 grass blocks in World_1. But If a break in World_2, the mission is completed.

**Comment by Staartvin** [comment]
Ah, this should be fixed in the latest version (if you want to try it).

**Comment by jariojose** [comment]
Sure! 

What do I do to try? Clone the project and build here?

**Comment by Staartvin** [comment]
No, there is a development server they allows you to download the latest file.

**Comment by Staartvin** [comment]
Yes, that dev build is the latest one

**Comment by jariojose** [comment]
Thank you, @Staartvin !

But It continues happening. I check the path, choose it:

- Break 25 grass blocks at spawn.

So, I went to test_world and broke 25 grass blocks and I received the Rank. But It couldn't happen :(

Continues bugged.

**Comment by Staartvin** [comment]
Hmm, I guess I have to do some more work.

**Comment by jariojose** [comment]
If you check 'statz_blocks_broken', only check if the broken blocks are in what world.

**Comment by jariojose** [comment]
Path Example:

`Admin Rank:
  prerequisites:
    in group: 
      value: Builder
      options:
        world: spawn
  requirements:
    blocks broken:
      value: 2;25
      options:
        world: spawn
        auto complete: true
  results:
    command: 
      value: manuadd &p Admin spawn
    command2:
      value: 'say &p just got a promotion; broadcast &p has just been promoted to Admin!'
    message: 
      value: 'Congratulations, you are now a Admin.'`

**Comment by jariojose** [comment]
@Staartvin Could I code it? Where do you check it?
