### ISSUE TITLE
Update reminder to old

### ISSUE THREAD

**Issue by derPiepmatz** [Staartvin/Autorank-2#630]
I updated to your newest version of autorank but now it keeps telling me to update it to an older version.

> Autorank v4.1 is now available for download!
Available at: http://servermods.cursecdn.com/files/2497/963/Autorank-4.1.jar

**Comment by jariojose** [comment]
I think that it happened because 4.1 version is beta and high versions are releases.

**Comment by Staartvin** [comment]
I'll look into this. For now, you may ignore the message or disable it.
