### ISSUE TITLE
/ar convert advancedconfig Invalid abstractResult

### ISSUE THREAD

**Issue by SpaicyGaming** [Staartvin/Autorank-2#631]
I converted an advanced config from v3 to a Path.yml for v4 using the command:
`
/ar convert advancedconfig
`

AdvancedConfig.yml example: https://pastebin.com/MBNspy7U
Path.yml result: https://pastebin.com/fbQW3GDf

The result "rank change" doesn't exist and on startup I get these warnings:
`[Autorank] (Priority 10) You are using a "rank change" abstractResult in path "circe", but that abstractResult doesn t exist!`

**Comment by Staartvin** [comment]
The rank change requirement has been deprecated and you should change it to a 'command' result that sets the permission group of a player.

**Comment by SpaicyGaming** [comment]
Thank you, I already did it. I suggest you to specify this in the [wiki section](https://github.com/Staartvin/Autorank-2/wiki/Convert-SimpleConfig.yml-to-Paths.yml)

**Comment by Staartvin** [comment]
Great work. I'll put it up on the wiki! Have fun using Autorank.
