### ISSUE TITLE
Manual Rankup not working

### ISSUE THREAD

**Issue by Fordy436** [Staartvin/Autorank-2#632]
I'm using a config pretty much identical to the one in the image below. (Also shown here: https://pastebin.com/tkwRLpEg)

Main Issue: So when it automatically assigns them to the "Group2" path, it works fine... until they reach the requirements and then go /ar check. It carries out the commands fine... but they are assigned back to the Group2 Path instead of the Group3 Path. They don't even meet the prerequisites anymore because as you can see the first command takes them out of group1... yet they're still being assigned to that path. I don't know much about coding, but I think it's looking for the prerequisites for the next path before those commands are executed... so no progress was made.

Secondary Issue: The reason I'm doing the permission unset/set commands is because when I use switchprimarygroup, each path still registers them in old groups... so sometimes it'll put them on the Group3 path, sometimes back to the Group2 path... Is there any way to prioritize paths? 

![capture](https://user-images.githubusercontent.com/12618108/39948515-3db7169c-556e-11e8-83b0-2292c3082efb.PNG)

**Comment by Staartvin** [comment]
Hmm, could you download the latest dev version and report back if you are still having the same issues? I've rewritten the paths code and this might solve these issues exactly.

**Comment by Fordy436** [comment]
I'm sorry, where do I find the latest dev build?

**Comment by Fordy436** [comment]
I don't know what that Dev Build entails exactly, but it's far from being a release build. It's even worse now, I do /ar check and it's listing all of the Paths I've completed, but saying that the progress is 0% for all of them. All /ar check is showing is how long I've played for, but even though I have the requirements it's not doing anything.

**Comment by Fordy436** [comment]
![image](https://user-images.githubusercontent.com/12618108/39957941-45ec90fa-55f3-11e8-9796-2ea9449eddc4.png)
****

**Comment by Staartvin** [comment]
There are definitely still issues with it, I didn't test everything. When you do /ar check it does not show anything besides the 'has played for' part?

**Comment by Staartvin** [comment]
What if you do /ar check Traveller (or Settler, Cottager)?

**Comment by Fordy436** [comment]
But I've already completed those paths as you can see at the top of the ss I attached. I shouldn't need to do /ar check Rank for it to say I've completed it, it should be automatic right?

When I do /ar check at the moment it shows the last 4 lines that are shown in the screenshot I attached.

**Comment by Staartvin** [comment]
Hmm, so that is odd. It is reporting that you are on a path, while you have completed it already. Did you turn on infinite pathing for that path?

**Comment by Staartvin** [comment]
Also, could you provide your complete paths file?

**Comment by Fordy436** [comment]
When I log in, the Plugin detects I've completed the path I'm on and continues to promote me once or twice but then goes back to doing nothing. 

https://gist.github.com/Fordy436/d872674d06a6a1f58ae85814de7ed828

**Comment by Staartvin** [comment]
Ah, but you have infinite pathing set to true. Therefore, when a player completes a path, he is allowed to retake that path again. Since all your paths are automatically being assigned to players, Autorank will automatically re-assign the path to a player. You should remove the infinite pathing option from each path.

**Comment by Fordy436** [comment]
The reason I have it set to true is because if I were to do any testing or demoting on these ranks, then Autorank wouldn't let them rank up again because it shows that they already completed that path... so taking players back ranks or anything like that becomes a hassle. And you say the paths are automatically being assigned to players but only if they have a certain `group.groupname` permission as a prerequisite... so why should Autorank RE-assign a path that no longer fits the prerequisites anymore?

Besides, the progress is still wrong, it should show them as completed, not as 0.00% shouldn't it?
