### ISSUE TITLE
New players already have time requirement for first path completed

### ISSUE THREAD

**Issue by ironik42** [Staartvin/Autorank-2#635]
Spigot version 1.12.2
Autorank version 4.2.3

The setup: When any new player logs on for the first time, they are automatically put on the first path. Once on that path, there is a time requirement of 8h set to complete that pat(along with some gathering requirements. 
The issue: When any new player logs on, the time requirement is already completed. All the gathering requirements seem to work fine. I've tried everything I could think of... I deleted the Autorank folder and jar and re-installed it, I've deleted my Statz folder(I had it looking there for data), and I've tried having it look at just Autorank for stats. Nothing is working. I've tried resetting player progress, but it won't undo the time requirement part. Please Help!!! I've attached my .yml files...

[YML Files.zip](https://github.com/Staartvin/Autorank-2/files/2038185/YML.Files.zip)

**Comment by ironik42** [comment]
OK, so new problem related to the issue... Time requirements are automatically completed regardless of actual played time and it doesn't matter what path it is... The only other thing I can think of is to set the time requirement as a prereq for the next path instead of as an actual path requirement. Trying that now...

**Comment by Staartvin** [comment]
I don't understand the issue exactly. What path do you have trouble with?

You don't need prerequisites per se, you can also leave them out. None of the requirements are necessary, although a path without any requirements would seem rather pointless to me.

**Comment by ironik42** [comment]
It's not any one path that's affected... it's all of them. If i set a time requirement that is NOT a prereq but a rankup requirement it automatically completes that time requirement regardless of actual time played. The only workaround I've found is to set the time as a prereq for the next path instead of an actual requirement for the current path. I don't know any other way to explain it. This is the only way I have been able to successfully include a time requirement. Unless I'm blind and I'm missing something...

**Comment by Staartvin** [comment]
Hmm, can you use the requirement 'time' instead of 'total time'? Also, what does **/ar times** show?

**Comment by ironik42** [comment]
I will try using 'time' instead of 'total time'. /ar times shows 0's for everything after I reset everything. Before, it showed actual time played, i.e. 50 minutes, but would still show 8h 'time with server' and complete that requirement. Past bedtime... I'll try your suggestion next chance I get. Thanks for your attention and patience.

**Comment by Staartvin** [comment]
Good luck! Let me know if it works.

**Comment by ironik42** [comment]
Nothing is working right with the time requirements. I was advised on the Discord channel to revert to version 4.1. I was using 4.2.3.


Sent from my Sprint Samsung Galaxy S7.
-------- Original message --------From: Vincent Bolta <notifications@github.com> Date: 5/25/18  5:32 AM  (GMT-08:00) To: Staartvin/Autorank-2 <Autorank-2@noreply.github.com> Cc: ironik42 <rwilson4267@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Staartvin/Autorank-2] New players already have time requirement
  for first path completed (#635) 
Good luck! Let me know if it works.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/Staartvin/Autorank-2/issues/635#issuecomment-392043701","url":"https://github.com/Staartvin/Autorank-2/issues/635#issuecomment-392043701","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Staartvin/Autorank-2","title":"Staartvin/Autorank-2","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Staartvin/Autorank-2"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Staartvin in #635: Good luck! Let me know if it works."}],"action":{"name":"View Issue","url":"https://github.com/Staartvin/Autorank-2/issues/635#issuecomment-392043701"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [Staartvin/Autorank-2] New players already have time requirement for first path completed (#635)",
"sections": [
{
"text": "",
"activityTitle": "**Vincent Bolta**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Staartvin",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Staartvin/Autorank-2\",\n\"issueId\": 635,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Staartvin/Autorank-2\",\n\"issueId\": 635\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Staartvin/Autorank-2/issues/635#issuecomment-392043701"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 339063826\n}"
}
],
"themeColor": "26292E"
}
