### ISSUE TITLE
Problems with configuration and need some help.

### ISSUE THREAD

**Issue by MineWarsGaming** [Staartvin/Autorank-2#636]
I am having a configuration issue with my current setup. I have followed along with the wiki and I am unsure why my configuration isn't working. Maybe someone here can help me out.

First off, let me say what is my plan for my server ranking is.

When users first join my server, they are set to rank "New". Then they click through a few signs to agree to our rules and privacy policy (thanks GDPR). After they agree, they are set to rank "Guest". Here is where I would like Autorank to pickup.

(Please see my configs below)

I would like Guest's to automatically be assigned to the path: "Guest to Member"

Next, after they have played on the server for two hours and have at least $500. they should complete the path and receive the rewards. One of the rewards will run the command: "pex user &p group set Member". The Guest, is now promoted to the rank Member and their Guest rank is removed.

I would like Guests to only see the path: "Becoming a Member"

Now, as a Member I would like them automatically assigned to "Member to Regular"
Next, after they have played on the server for 24 hours and they have at least $2,000 they complete the rank and are set to rank "Regular".

I would like Members to only see the path: "Becoming a Regular"

From here I would go through a few more ranks but I am not going to worry about that for now, I am just getting these two paths working for now.

I do not think I have discovered any bugs, I think I am just making a configuration mistake. I have ran the code through a few YML checkers and all seems fine. I am pretty sure I have just missed some config option in the Paths.yml file. In the past, I used the simple config option which worked fine with my setup. I would love to learn this new system to explore more capabilities with my server. Just takes a little bit of learning and some trial and error, and sometimes help from the community.

Below I have included some information about my server. If I need to provide more, please let me know.

Thank you in advance for the help,
Croft3r
MineWars Gaming Network

Please note, I am modifying my files and restarting the server instead of using /ar reload. I recall seeing another post of that not always working 100%.

Paths.yml: https://pastebin.com/KkQeavUS
Settings.yml (with sql info removed): https://pastebin.com/kJdCrqfF
DefaultBehavior.yml: https://pastebin.com/pR4ux7u1

Pex Permissions: https://pastebin.com/4KGLrvGV

Plugins: https://pastebin.com/imG5MXKy

**Comment by MineWarsGaming** [comment]
So it started working randomly so I decided to add my final two ranks and it seemed to stop again. I am really at a loss for what is going on. After running it by a few people they belive I am following the correct formatting. Could it be something with my permissions?

Updated Paths.yml: https://pastebin.com/pH0FuJY2

Everything else is the same, I have just updated the Paths.yml.

**Comment by leejosepho** [comment]
First: Here is where I began with AutoRank just a few hours ago:
----------------------
Nomad-to-Miner:
  prerequisites:
    in group:
      value: nomad
  requirements:
    blocks broken:
      value: 1500
  results:
    command:
      value: broadcast &p has achieved 'Nomad-to-Miner'!
    command2:
      value: pex user &p group set miner
  options:
    display name: Nomad-to-Miner
Miner-to-Member:
  prerequisites:
    in group:
      value: miner
  requirements:
    blocks broken:
      value: 5000
  results:
    command:
      value: broadcast &p has achieved 'Miner-to-Member'!
    command2:
      value: pex user &p group set member
  options:
    display name: Miner-to-Member
----------------------

Nothing fancy there, but it takes new players from nomad to miner to member.

Second: Try a full server restart.  I do not have the option of trying '/reload' for my server, but I do know '/ar reload' was not enough for me.

**Comment by Staartvin** [comment]
Note that reloading a plugin generally doesn't suffice as not all data can and will be reloaded.
