### ISSUE TITLE
AutoRankup does NOT work on skyblock server...

### ISSUE THREAD

**Issue by SilverHuskey** [Staartvin/Autorank-2#638]
Hands down this plugin is amazing.. works VERY well... But on one of my servers (Skyblock) it just wont launch... at all we cant get the plugin to run at all... 

https://imgur.com/a/ARNsva4

There is no console error as far as i can see

**Comment by Staartvin** [comment]
Can you provide me your startup log?

**Comment by SilverHuskey** [comment]
https://pastebin.com/QtQXFxhR

**Comment by Staartvin** [comment]
You should download PluginLibrary. It's a required dependency of Autorank.

**Comment by SilverHuskey** [comment]
Thanks! I appreciate that! I didn't see that on the plugin overview... Maybe make that a bit more obvious if you could...
