### ISSUE TITLE
Auto Rank with Twitch?

### ISSUE THREAD

**Issue by itsjusttriz** [Staartvin/Autorank-2#640]
Is there any possible way to set it where people have to connect their Twitch account to gain access to a rank? I manage a server for a friend and she bases her ranks from her Twitch Subs.
Rank / Sub tier:
silver / Tier 1
gold / Tier 2
Diamond / Tier 3

It would save us a lot of time having to log on just to manually set peoples ranks!

**Comment by TheIntelloBox** [comment]
I think that it would be very difficult. :D

**Comment by CaszGamerMD** [comment]
i think there used to be a twitch API that could be used with minecraft
what it sounds like they need is a listener for twitch to a certain twitchAccountHost channel that looks to see if player with twitchAccountPlayer is a sub
then from there checks if twitchAccountPlayer has certain subTier to give them rank from that...

idk if autorank would be the right fit for that form of per giving though. but would be a cool feature that servers could use

(extra thought) -- could do something for YT as well, just minus the tier part
