### ISSUE TITLE
Allow players to have multiple paths at the same time

### ISSUE THREAD

**Issue by CaszGamerMD** [Staartvin/Autorank-2#641]
kinda a piggy back off my GUI idea

if you get the GUI working, you should see if you can add support for multiple paths at once,
i have 2 sets of paths i want my players to interact with, the goal would be they can be working towards either path at the same time.

with the current set up it can be tough to read 2 paths at the same time in chat, but with the GUI it can show Completed Paths, Available Paths, Current Paths, and would be nice to have a Statz button in it too that would connect to the Statz GUI.

if this is all possible then players would have an easier to use/read pathing system and can see what is required for them to rank up.

**Comment by Staartvin** [comment]
I'm already working on having multiple paths. It's close to being finished. The latest dev builds allow a player to have any number of paths and allow you to set whether the path's progress is stored when the player temporarily disables the path.

**Comment by CaszGamerMD** [comment]
Right off the bat:
1. any way to prevent the path spam? second i loaded in with dev build#59 it spams player with all the paths they've yet "joined" even if they are not matching prereq. *so i have time/ money based paths and Statz based paths, all of which are prereq-ing the path before it, when i load in ALL the paths got added regardless of my current rank. ---wait i may have been op possibly dumb atm---

2 /ar check (player) (path) errors out 
3*enhancement* - still think now with multi-path "working" a gui would be ideal to make it easier for players to see/ understand the "paths" they are assigned
  -  in that if we could edit the phrasing for said GUI so it could be quests or ranks or ect however servers choose to use 

ref issue 613 which i note is on todolist
