### ISSUE TITLE
Autorank mob kill requirement not working?

### ISSUE THREAD

**Issue by Espinete87** [Staartvin/Autorank-2#643]
Hello guys, i have a problem with the mob killer requeriment, lets see if you can help me.

http://es.tinypic.com/r/2mhbnzn/9

When i dont have the Statz plugin working, i can see properly the 2 requeriments with /ar check, but obviusly the requeriment mob kill is not working.

Then i put the statz mod and then its show that problem, and is not working. Any help please? ( i used last version of Statz v1.5.1 Apr 28, 2018)

Autorank Advanced config:

ranks:
forasteros:
requirements:
time:
value: 2m
results:
rank change: forasteros;habitantes
command: 'say &p just got a promotion; broadcast &p has just been promoted to habitantes!'
message: 'Congratulations, you are now a habitante.'
habitantes:
requirements:
time:
value: 3m
mobs killed:
value: 1;pig
results:
rank change: habitantes;veteranos
command: 'say &p has just been promoted to veteranos!; give &p 6 2; tell &p You have just earned 100 stone!'
message: 'Congratulations, you are now a veterano.'

Console log:
https://pastebin.com/Xsr61RXB

Statz Config:
track stats: true
show database save message: false
mysql:
enabled: false
hostname: localhost:3306
username: root
password: ''
database: Statz
periodic save time: 10
refresh player cache time: 60
disabled statistics:
- DISABLED_STAT_NAME_HERE
- OTHER_DISABLED_STAT_NAME
ignore creative: false
enable debug output: true
latest patch mysql version: 0
latest patch sqlite version: 3
use custom statz list: false
custom statz list:
- JOINS
- FOOD_EATEN
- KILLS_PLAYERS
use statz gui: false

Please some support, i would like to fix this, otherwhise my server would looks quite basic. 
Thanks

**Comment by Staartvin** [comment]
You should update your version of Statz to the latest version!

**Comment by Espinete87** [comment]
Hello Staartvin, thanks for reply but... the Statz is already in the last version!
Statz-1.5.1.jar is what i have
And here is the lastest versions of the plugin
https://www.spigotmc.org/resources/statz.25969/history

so...

**Comment by Staartvin** [comment]
What version of Autorank are you running?

**Comment by Espinete87** [comment]
Maybe we have here the problem. Is v3.8.5.1
Why? As you know many comments are not very positive about set up the plugin to make it works.
I just want a simple requeriments, so your last version is very easy, and i thought could works whithout problems! If you think your older versions doesnt works then... maybe i will choose another plugin.
Anyway i value your job, is awesome and i admire people like you.

**Comment by Staartvin** [comment]
That version of Autorank does not work with the latest version of Statz. You should either upgrade Autorank (which I highly recommend) or downgrade Statz (which is discourage to do). If you have any problems with Autorank on the newer version, you can just post it on the github issue tracker (here)!

**Comment by Espinete87** [comment]
Okay thanks, i want to do a quick try, could you tell me wich version of Statz i should choose for downgrade? Becouse i dont have any guide about wich version should match with that version Autorank
https://www.spigotmc.org/resources/statz.25969/history
If i would have to guess, i would get a version updated around your dates, 



downgrade? Becouse i dont have any guide about wich version should match with that version Autorank
https://www.spigotmc.org/resources/statz.25969/history
If i would have to guess, i would get a version updated around your dates, v3.8.5.1 | Nov 12, 2016
so maybe Statz v1.4 | Nov 11, 2016 ?

Thank you Staartvin, nice support

**Comment by Staartvin** [comment]
Yes, I would assume Statz v1.4. Note that if you downgrade, I can't give you any support on bugs, as they might have been fixed in next version. Consider moving to the most recent version of both Autorank and Statz and report bugs that you find in there.

**Comment by Espinete87** [comment]
Yes okay i completly understand.
I would like to use last versions and be part of the progress and get support if i have a problem. But i remember to struggling a bit with the last version of autorank so maybe it will be quickest way.
Thank you very much for your help Staartvin
