### ISSUE TITLE
Error Via Console

### ISSUE THREAD

**Issue by mscake** [Staartvin/Autorank-2#645]
Hello there, I keep getting this issue through console and Autorank is no longer adding player time to their data. Autorank has also stopped promoting players once they received the requirements. This issue started occurring once I added Leaderheads as a plugin.

`WARN [Autorank] Task #63 for Autorank v3.4 generated an exception
17.07 19:09:58 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
17.07 19:09:58 [Server] INFO at me.armar.plugins.autorank.warningmanager.WarningNoticeTask.run(WarningNoticeTask.java:21) ~[?:?]
17.07 19:09:58 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-3fb9445-6e3cec8]
17.07 19:09:58 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [server.jar:git-Spigot-3fb9445-6e3cec8]
17.07 19:09:58 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [server.jar:git-Spigot-3fb9445-6e3cec8]
17.07 19:09:58 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [server.jar:git-Spigot-3fb9445-6e3cec8]
17.07 19:09:58 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-3fb9445-6e3cec8]
17.07 19:09:58 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-3fb9445-6e3cec8]
17.07 19:09:58 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]`

**Comment by Staartvin** [comment]
What version of Minecraft are you running? Moreover, why are you running a very outdated version of Autorank? You should update.

**Comment by Staartvin** [comment]
Autorank 4 introduced a new format for ranks (now called paths). You should use the /ar convert command when you convert to Autorank 4. Everything should work after that (restart of server is required).

**Comment by mscake** [comment]
When I previously tried to update to version 4, everything was correctly done and there were no error messages in console. In-game the data does not show and it says everyone has 0 minutes and has not chosen a path.

When using the /ar convert command this error message appears "This command is not used anymore and will be deprecated."

**Comment by Staartvin** [comment]
Ah, that's right. The convert has been deprecated as you should've switched over a while ago. Anyway, try to download a less recent version (e.g. [this one](https://www.spigotmc.org/resources/autorank.3239/update?update=164228)). Use the /ar convert command. Then, switch over to the most recent version and everything should work fine.

**Comment by mscake** [comment]
Everytime when I try to update to a new Autorank version the data doesn't convert over and when the command /ar check is run, it doesn't correctly display the player's data. I have done /ar import but it is still not properly showing up. I have imported the data from a recent backup, and still, not working.

**Comment by mscake** [comment]
Sadly I am **still** having this problem.

**Comment by kiwifrogg** [comment]
I have the same issue with the data, the stat3 to statz migrate does not work. I can migrate the times and data but only for people who have logged the server. It is like the plugin checks the player folder in the world save and only allows those players to be on the list.  I get around this by removing the backup folder and replacing total_times file, after the regulars have all logged. This still leaves the longterm players to update manually when they return.
