### ISSUE TITLE
Disabling auto check on login

### ISSUE THREAD

**Issue by ElnanMillstone** [Staartvin/Autorank-2#646]
Hello, the title pretty much says it all.  How can I disable Autorank from checking a player's requirements on login (So they have to type /ar check [path]) to be promoted?  These are my current settings:

auto-updater:
  check-for-new-versions: true
advanced dependency output: false
show help command based on permission: false
use debug: false
show warnings: true
use primary group for vault: true
broadcast resetting of data files: true
use global time in leaderboard: false
disable automatic path checking: true
automatically archive old data: true
primary storage provider: flatfile

**Comment by madolebr** [comment]
i believe that has to do with ur paths, not with the settings. make sure to add in the option to all of them auto choose: false and auto complete: false
