### ISSUE TITLE
Invalid command hint

### ISSUE THREAD

**Issue by bert-w** [Staartvin/Autorank-2#647]
https://github.com/Staartvin/Autorank-2/blob/master/src/me/armar/plugins/autorank/commands/CheckCommand.java#L74

This should hint to the command `/ar check <player> <path>`

**Comment by Staartvin** [comment]
If you try /ar check <path>, Autorank will assume your name as the target player. I'm not sure if that should be changed, though.

**Comment by bert-w** [comment]
hm it caused a permissions error i believe `autorank.checkothers`

**Comment by madolebr** [comment]
yeah, because u need that permission to check other players
