### ISSUE TITLE
Support for Stats5

### ISSUE THREAD

**Issue by FrozenBeard** [Staartvin/Autorank-2#651]
Lolmewn released an alpha for Stats 5, can you please support his API's for this, I cant convert Stats3 to Statz as you load all data into memory of the plugin first instead of having raw SQL we can use, so it crashes. my Database is 1.4GB.
https://www.spigotmc.org/resources/stats.3638/

**Comment by Staartvin** [comment]
I can, but I'm not sure if I should do that now. Api is bound to change and you can't convert to Stats 5 yet.

**Comment by FrozenBeard** [comment]
Definitely, I'm just posting early! Stats3 has Sooo many bugs I need to move from it asap, especially with 1.13, I really do need to try it again with Statz as I need to update autorank for the multi rank rankups, I've been wanting that for years and you added it but im stuck with my stats3 so I cant update it!

**Comment by Staartvin** [comment]
I can look into reading the raw sql data from Stats 3 database into Statz next week. Perhaps you're able to switch to Statz ;)

**Comment by FrozenBeard** [comment]
That would be bloody awesome if you could, I'm just stuck at present.
Just a SQL statement to copy the Stats3 into Statz data format without the need of a plugin, it would be so much faster too.
Im off on holiday for a week so would be brilliant to come back too, and I will convert!

**Comment by Staartvin** [comment]
It seems I cannot get Stats 3 to create a table. It's complaining about SSL connections that cannot be made to my local test database. I'll first have to fix this before I can do any work on the conversion MySQL.

**Comment by FrozenBeard** [comment]
Ok

**Comment by Staartvin** [comment]
Stats 5 is not updated anymore, so I won't be supporting it any longer. It doesn't seem like its current version is stable.

**Comment by FrozenBeard** [comment]
I posted this in 2018, I would much prefer to use the built in Minecraft stats now.
