### ISSUE TITLE
Duplicated result descriptions with /ar view

### ISSUE THREAD

**Issue by thenameisKO** [Staartvin/Autorank-2#653]
There's a possibility that I just missed something in the wiki (though I combed through it several times before giving up), but there seems to be a bug when you have descriptions set for each result in Paths.yml and use /ar view to view a path.  The first description ends up being used for each result in the command output rather than each result maintaining its own description.  Here's a snippet of Paths.yml that I'm using:

> results:
    command:
      value: broadcast &p has just ranked up to Explorer!
      options:
        description: Announcement of your rankup!
    command2:
      value: eco give &p 10000
      options:
        description: Receive 10000 munnies!
    command3:
      value: acb &p 5000
      options:
        description: Receive 5000 claim blocks!
    command4:
      value: pex user &p group set Explorer
      options:
        description: Receive the Explorer title!
    message:
      value: Congratulations, you now have the Explorer rank!

Here is a screenshot of the results given by /ar view for that path: [http://prntscr.com/khu5pl](url) (this was tested with each path created).  This was tested on Spigot 1.12.2 with Autorank version 4.2.5 and 1.13-R0.1-SNAPSHOT with Autorank version 4.2.6.  Thanks in advance, let me know if you need more information.

**Comment by Staartvin** [comment]
Thanks for reporting! I'll look into the issue.
