### ISSUE TITLE
Rankup command not working with Group manager

### ISSUE THREAD

**Issue by BruceFradgLee** [Staartvin/Autorank-2#660]
Hi.
I'm having an issue in the paths.yml where i've set the command value (on path completion) to 'manuadd &p [Rank]'
When testing it shows all the completion messages however doesn't actually change the rank.

I'm running all required plugins up to date.

Any help on this would be appreciated,
Thanks.

**Comment by BijuuKrunos** [comment]
Okey just to be sure: DON'T USE GROUP MANANGER!!!!!

take something better like Pex or if you want one of the best take LuckPerms!!!
