### ISSUE TITLE
[Help] A more dynamic Ranking system.

### ISSUE THREAD

**Issue by MoeMilord** [Staartvin/Autorank-2#665]
So I'm using KingdomsCraft as a way for new players when joining for the first time will have a default Rank called, Outcast (Here Autorank should be disabled). then After exploring spawn, they can Choose to either take one faction or another using an NPC. (NOTE: there are only two Kingdoms). After that, comes the ranks for each Kingdom's ranks which is applicable with KingdomsCraft. however, if I wanna Integrate AutoRank to perform the auto ranking for each hierarchy and have the OutCast rank unrankable unless it changes to a faction's Initial rank? How can I do so?

Thank you so much in regards!

**Comment by BijuuKrunos** [comment]
Just don't tell Autorank that the OutCast rank even exist.

for example:

You have as first Kingdom rank (after you selected one) the Scarce. and the next rank is the knight.

than you have to write the path from scarce to knight:

knight:
  prerequisites:
    in group:
      value: scarce
  requirements:
    time:
      value: 10h
  results:
    command:
      value: /lp user &p promote kingdomA

I hope this will help you. Let me know

Greetz 
Krunos
