### ISSUE TITLE
Autorank Error

### ISSUE THREAD

**Issue by whiteshark445** [Staartvin/Autorank-2#666]
I'm trying to load autorank on my 1.6.4 tekkit server, but I keep getting this error in the server log. 
![server log](https://user-images.githubusercontent.com/46824148/51444742-25cd7b00-1cc1-11e9-9c1d-37624ffefacf.png)

![simpleconfig yml](https://user-images.githubusercontent.com/46824148/51444695-b3f53180-1cc0-11e9-8c4e-66047267ed20.png)

Currently I have 5 pex groups setup. member, T-mod, mod-, admin, and owner

**Comment by Staartvin** [comment]
That's a very old version I can't really support anymore unfortunately.
