### ISSUE TITLE
Enhancement - Add categories of mobs

### ISSUE THREAD

**Issue by mldickey** [Staartvin/Autorank-2#671]
It would be excellent if you could track mob kills in "collections" or "groups." Similar to Issue #642, where they asked for Spiders and Cave Spiders to be considered as one thing.

One valuable collection would be "Undead" which should include zombies and skeletons obviously, but everything listed at https://minecraft.gamepedia.com/Undead .

Similarly, "Peaceful" mobs might be everything listed at https://minecraft.gamepedia.com/Mob#Passive_mobs .

The idea being, that we could set requirements for "Kill 100 Undead Mobs" or "Kill 100 Peaceful Mobs" and the player could choose which mob(s) they prefer to hunt down for those two requirements.

**Comment by Staartvin** [comment]
You can already cluster requirements together so that they become or requirements.
Think of a requirement to kill mobs but used the 'or' conditions to let the player kill 5 zombies OR 5 skeletons OR 5 spiders, etc.
