### ISSUE TITLE
Auto rank wont add times for players

### ISSUE THREAD

**Issue by Nikothesiko** [Staartvin/Autorank-2#672]
I have no idea why players times have stopped going up! could you please advise

https://pastebin.com/MwDjaEZc

**Comment by Nikothesiko** [comment]
Not sure how I done it, synced stats and restarted the server seemed to repair what ever was causing the problem

**Comment by Staartvin** [comment]
Could you try to upgrade to the latest version and see if it works again? Let me know if it doesn't.

**Comment by TNTUP** [comment]
Sorry by hijacking this closed issue, on all servers global time for a particuliar/all players are not in sync. Some has -/+ minutes/hours difference. Seems to solve at reboot but its quite disappointing for global rankups^^

Also the /ar gcheck works only if the player has connected for the first time on X server. Would be nice if we can gcheck's a player across all servers on the bungee network (MYSQL mode ofc)

**Comment by Staartvin** [comment]
Yeah, it would be nice to create a new issue. They way I can focus your issue on the specifically and we can pinpoint the issue.

**Comment by TNTUP** [comment]
> Yeah, it would be nice to create a new issue. They way I can focus your issue on the specifically and we can pinpoint the issue.

Will do!
