### ISSUE TITLE
Autorank stopped adding times correctly

### ISSUE THREAD

**Issue by AltJawga** [Staartvin/Autorank-2#674]
**Issue:** Autorank is not adding times consistently on the latest version of Paper. It seems to update at random/on restart.
**Expected Behavior:** Time refreshing on the set interval in the config.
**Debug:** https://pastebin.com/U71x0TLx
**Time Started:** First reported on 3/9/2019

**Comment by Ironic8b498** [comment]
Staartvin helped AltJawga and a few others with same issue, most on paper. This seems to be a bug, it seems to work on Spigot  but I have not used a stop watch to make sure it updates on time
