### ISSUE TITLE
/ar check <rank> Internal Error

### ISSUE THREAD

**Issue by joshkal9876** [Staartvin/Autorank-2#676]
I installed Auto Rank, my server is 1.12.2. Everything seemed to work fine, I configured the rank I needed and did /ar reload. /ar check worked completely fine but when I do /ar check <rank name> I get an internal error.

Console: https://pastebin.com/99nwynGX

Paths.yml: https://pastebin.com/4CRiHJs7

Its a fresh install only thing I changed was paths.yml

**Comment by Staartvin** [comment]
You'll need to update Autorank, PluginLibrary and Statz to the latest versions.
