### ISSUE TITLE
Autorank displaying 0 ar time in 1.14.1, also not allowing me to put playerdata backups into the playerdata or data folders

### ISSUE THREAD

**Issue by Issemir** [Staartvin/Autorank-2#678]
Hi,

The first issue occurs to every player on the server. They login, play for a significant amount of time and yet autorank still displays their ar time as 0. I can manually set their time to 5 minutes and it'll display 5 minutes, but it still won't add time on itself as they play. A section from my paths.yml is visible at https://pastebin.com/6gRJAVZ0

As for the second issue, essentially I reset my world file a couple weeks ago. Doing this seemed to wipe all of the Autorank data (setting everyone's time to 0). At first I figured Autorank may store playerdata with the world files somewhere and thought this may be why it wiped.

However when I was digging around to solve the issue above, I found that Autorank seems to store player data in 2 locations, the 'playerdata' folder and the 'data' folder. Fortunately, I took a local backup of my server plugins folder and this included the old data from autorank. I copied all files within the 'data' and 'playerdata' folders to the server and started it up. It seemed to wipe the data completely and just delete it all. Is there a way around this where I can bring my old data back to the new world?

Thanks in advance,
Iss

**Comment by Issemir** [comment]
Server thread/ERROR Could not pass event PlayerJoinEvent to Autorank v4.2.6
This is an error I get when people join which may be related

**Comment by Staartvin** [comment]
Could you upgrade to the latest version of Autorank and check again?
