### ISSUE TITLE
Time not updating 1.14.2

### ISSUE THREAD

**Issue by Flopprd** [Staartvin/Autorank-2#681]
I am not really sure if Autorank should be working on 1.14.2, but at the moment it does not update the time of players when they are online. Online if I do it manually with the /ar add or /ar set command it changes. But then it won't update anymore.
Again, I am not sure if the plugin works for 1.14. Please let me know.

Flop

**Comment by Staartvin** [comment]
Could you try to upgrade to the latest version and see if it works again? Let me know if it doesn't.
