### ISSUE TITLE
Requesting To Be New Autorank Maintainer

### ISSUE THREAD

**Issue by ethsmith** [Staartvin/Autorank-2#683]
Hello Staartvin,

I am a java programmer and I noticed you haven't updated your autorank plugin in a year so I was wondering if you were willing to allow someone else to maintain it that may have more free time to do so.

Thanks,

Ethan

**Comment by Staartvin** [comment]
I'm currently preparing for the Bridgestone World Solar Challenge with Solar Team Eindhoven, so that's why I haven't had the time to update it. Feel free to create pull requests and I'll review them as best as possible. Thanks in advance!

**Comment by sillentkil** [comment]
> Hello Staartvin,
> 
> I am a java programmer and I noticed you haven't updated your autorank plugin in a year so I was wondering if you were willing to allow someone else to maintain it that may have more free time to do so.
> 
> Thanks,
> 
> Ethan

Hi,
Ethan do you have any plans on working on a 1.14 update for this plugin?
We recently update a server to 1.14 and would like to keep using this plugin. So, we are looking at modifying this plugin or find another one.

**Comment by Staartvin** [comment]
I'll be updating this plugin once I'm back from my trip to Australia. That'll be around the end of this month.

**Comment by sillentkil** [comment]
Sounds good, thanks for the reply.

And more  importantly good luck in the race, as a Dutch its awesome to see you guys win 😊

**Comment by Staartvin** [comment]
Thanks! We definitely hope to win a fourth time!
