### ISSUE TITLE
Only 3 requirements are shown? Urgent please help.

### ISSUE THREAD

**Issue by rurouni22** [Staartvin/Autorank-2#687]
Hello i added like 8 or 10 requirements and checked all of them if they are wrong and tried to put them seperately and it worked. But only 3 of them are shown on the /ar check path list. Please tell how can i list all the requirements? Thanks.

**Comment by Staartvin** [comment]
Did you make sure all requirements have different names? Can you show me your paths file?

**Comment by rurouni22** [comment]
Oh how fool i am :D I put has item: value more than 1 time with different blocks. Tried with has item2: value: and it works.

**Comment by Staartvin** [comment]
Yes, that is exactly what you should be doing :)

**Comment by Staartvin** [comment]
You can check out the wiki for more detailed info if you need it.
