### ISSUE TITLE
Enhance import functionality

### ISSUE THREAD

**Issue by Staartvin** [Staartvin/Autorank-2#690]
The import method should be able to do the following separately:

- [x] Import time from a separate folder 'import' from different files. Be able to import a file by name.
- [x] Import time to your local database
- [x] Import time to the global database
- [x] Import time **only** to your global database
- [x] Add warning when no imported files could be found.

New arguments that have been added:
- [x] _--db_: Update the global database with imported values
- [x] _--db-only_: Update only the global database with imported values (so local database is not updated)
- [x] _--overwrite-all_: Overwrite both the local and global database with imported values
- [x] _--overwrite-db_: Overwrite only the global database with imported values (but not the local database)
- [x] _--overwrite-flatfile_: Overwrite only the local database with imported values (but not the global database).

**Comment by DarkObscurity** [comment]
Add an option to the general config "serverName:" where people can define a server name. This could be used to save the flatfile named <serverName>-autorank.sql or something. Then you can put flatfiles in a folder called "import".

You can use the command "/ar importflatfile" and then autorank will import all flatfiles in which are currently in the "import" folder.

Then there are 5 paramters:
--database will add the time which is being imported to the current flatfile but also to the database.
--database-only will only import the time and add it to the database
--overwrite will overwrite all data in the flatfile and database
--overwrite-flatfile will overwrite all data in the flatfile
--overwrite-db will overwrite all data in the database

It would be awesome if the parameters could be used together, so then --database --overwrite-flatfile will import the data and overwrite the flatfile, but will "add" the value's  to the database and not overwrite the current value's in the database.
