### ISSUE TITLE
Autorank v4.2.8 generated an exception

### ISSUE THREAD

**Issue by 7SINS7** [Staartvin/Autorank-2#700]
07.12 00:28:12 [Server] Server thread/WARN [Autorank] Task #168 for Autorank v4.2.8 generated an exception
07.12 00:28:12 [Server] INFO java.lang.NullPointerException: null
07.12 00:28:12 [Server] INFO at me.armar.plugins.autorank.config.PathsConfig.getResults(PathsConfig.java:229) ~[Autorank-4.2.8.jar:?]
07.12 00:28:12 [Server] INFO at me.armar.plugins.autorank.pathbuilder.builders.PathBuilder.getResults(PathBuilder.java:166) ~[Autorank-4.2.8.jar:?]
07.12 00:28:12 [Server] INFO at me.armar.plugins.autorank.pathbuilder.builders.PathBuilder.initialisePaths(PathBuilder.java:44) ~[Autorank-4.2.8.jar:?]
07.12 00:28:12 [Server] INFO at me.armar.plugins.autorank.pathbuilder.PathManager.initialiseFromConfigs(PathManager.java:312) ~[Autorank-4.2.8.jar:?]

**Comment by 7SINS7** [comment]
[Paths.txt](https://github.com/Staartvin/Autorank-2/files/3934881/Paths.txt)

**Comment by Staartvin** [comment]
Make sure to check if every path has at least one result. Also, why is there a path with no requirements?

**Comment by 7SINS7** [comment]
This is why I was asking for help lol, I'll go over it again once I wake up.

**Comment by 7SINS7** [comment]
[Pathstext1.txt](https://github.com/Staartvin/Autorank-2/files/3935803/Pathstext1.txt)

I still dont see what we are doing wrong

**Comment by Staartvin** [comment]
Are you still having this issue on Autorank 4.3?
