### ISSUE TITLE
[ERROR] Could not pass event PlayerJoinEvent to Autorank v4.3.1

### ISSUE THREAD

**Issue by Dani479** [Staartvin/Autorank-2#705]
Could you help me solve this error? This causes one of my friends to be promoted each time he logs in, so I'd like to solve this problem as soon as posible. This is the log:
https://pastebin.com/Lcd5Ckzb 
Thanks!

**Comment by Staartvin** [comment]
Could you provide me with the paths file? I want to investigate a firework result you have set up.

**Comment by Dani479** [comment]
Of course: https://pastebin.com/8Bs91dD3

**Comment by Staartvin** [comment]
I've investigated this issue and it seems to be fixed in this version: http://staartvin.com:8080/job/Autorank/41/ Could you try and see if it works?

**Comment by Dani479** [comment]
Ok, I'll try to get my friend to log in. I'll tell you in a moment.

**Comment by Dani479** [comment]
Perfect, the issue is fixed. Thank you very much for your quick help!
