### ISSUE TITLE
"An internal error occurred while attempting to tab-complete [/ar choose]"

### ISSUE THREAD

**Issue by flu147** [Staartvin/Autorank-2#706]
I am trying to set up AutoRank for the first time, and I can't seem to get any paths to work. I am constantly getting this error in game while doing /ar choose and can't find a solution with my normal tinkering. Any help?

Paths.yml:
https://pastebin.com/mkam21s9

Debug:
https://pastebin.com/dixwfC2k

latest.log:
https://pastebin.com/BHJfPfyp

**Comment by Staartvin** [comment]
It seems that Autorank has issues with hooking into Luckperms. Are you running Luckperms v5 of v4?

**Comment by Staartvin** [comment]
If you're running LuckPerms v4, you'll need to upgrade to v5.

**Comment by flu147** [comment]
Yep, I'm running v4. Updating fixed it. Thanks!!
