### ISSUE TITLE
weeklytime and dailytime Requirements

### ISSUE THREAD

**Issue by Master0r0** [Staartvin/Autorank-2#707]
Would it be possible to support weeklytime and dailytime for requirements so that players can be given rewards based on there time played that week

**Comment by Staartvin** [comment]
This is already implemented in the latest dev build. See http://staartvin.com:8080/job/Autorank/52/. You can use 'daily time', 'weekly time' and 'monthly time'.

**Comment by Master0r0** [comment]
Ah okay thank you
