### ISSUE TITLE
Reset player data

### ISSUE THREAD

**Issue by gmwatson** [Staartvin/Autorank-2#724]
Is there a way to reset the "playdata.yml"?  Currently we have a couple of users that have "exempt from leaderboard and exempt from time addition, set to true.  No matter what we do we cant get it to fall back to false.  See attached for paths and playerdata output. 

We have tried deleting and re-adding the plugin as well as deleting player data from essentials and factions

[PlayerData.txt](https://github.com/Staartvin/Autorank-2/files/4513007/PlayerData.txt)

[Paths.txt](https://github.com/Staartvin/Autorank-2/files/4512964/Paths.txt)

**Comment by Staartvin** [comment]
Yes that's possible with the /ar reset command. If you want to manually adjust in the file, make sure to stop your server, edit the files and start it again. That also works.
