### ISSUE TITLE
use time of seems to not work

### ISSUE THREAD

**Issue by Ectabro** [Staartvin/Autorank-2#725]
Hello, 

I'm using AR 4.3.3 with papermc 1.15.2.

When i set use time of : Statz, times used are always AR times.
If i do a /Statz list i have 49d and with /ar times i have only 1hour and 32minutes...

Any idea ??

**Comment by Staartvin** [comment]
What does the startup log of Autorank say? Can you post it?

**Comment by Ectabro** [comment]
![artime](https://user-images.githubusercontent.com/20256156/80276896-cd6b0180-86eb-11ea-9a48-0be0edf37700.PNG)
![statztime](https://user-images.githubusercontent.com/20256156/80276897-ce039800-86eb-11ea-87fd-0e5c9903305f.PNG)
![arstartup](https://user-images.githubusercontent.com/20256156/80276898-ce9c2e80-86eb-11ea-8d92-027856753ada.PNG)

Tell me if you need more information !

**Comment by Staartvin** [comment]
Can you enable Autoranks debug and start your server? Then send the startup log.

**Comment by Ectabro** [comment]
Yes here it is https://pastebin.com/5xPe7Mbs

**Comment by Ectabro** [comment]
And also ar check doesn't use Statz time of course

**Comment by Ectabro** [comment]
So ?

**Comment by Staartvin** [comment]
Ah, I'm sorry. The use of parameter has been removed from Autorank 4.3.3. Instead, you should migrate data from Statz to Autorank and start using it.

**Comment by Staartvin** [comment]
I've added a small explanation and an error in the latest version of Autorank telling you that this option has been removed from the config. See https://github.com/Staartvin/Autorank-2/wiki/How-to-configure-the-Settings.yml%3F#use-time-of
