### ISSUE TITLE
Add MCRPG Support

### ISSUE THREAD

**Issue by dexasz** [Staartvin/Autorank-2#729]
Would be cool, if you could track MCRPG levels, and make it into a rankup requirement. :)
https://www.spigotmc.org/resources/mcrpg.63020/

**Comment by Staartvin** [comment]
I can add that, yeah!

**Comment by dexasz** [comment]
Cool, I joined the discord yesterday, gonna wait for the updates! :)

**Comment by dexasz** [comment]
![letmeknow](https://user-images.githubusercontent.com/37642364/80864874-535bef00-8c8e-11ea-92bf-c385f628ac1c.PNG)

MCRPG Dev said he'll help you, IF you'll need any help. :)

**Comment by Staartvin** [comment]
That's great. How do I come into contact with him?

**Comment by dexasz** [comment]
мм§DiamondDagger590#0321 <-- His discord. :)

**Comment by Staartvin** [comment]
I've added McRPG support (but I can't test it). Would you mind testing it for me: http://staartvin.com:8080/job/Autorank/88/ The wiki is updated to reflect the changes: https://github.com/Staartvin/Autorank-2/wiki/Requirements-&-Results#mcrpg-requirements
