### ISSUE TITLE
Ar progress bar not working

### ISSUE THREAD

**Issue by lakiron** [Staartvin/Autorank-2#731]
I run a 1.13.2 server on spigot. For some reason AR refused to count time with afk integration enabled. Now that I disabled it, AR mostly works except for the progress bar as seen on the screenshot. I would really like to fix this if possible, because overall I really enojy AR and its functionality.
Thanks in advance <3
![2020-04-16_18 58 47](https://user-images.githubusercontent.com/36330602/80716748-b3248f80-8b00-11ea-9f91-e9f7fbae85fc.png)

**Comment by Staartvin** [comment]
The progress bar in Autorank works a bit wonky right now: it only counts completed requirements of a path. 

Let's say you have 3 requirements in a path:
- If you have completed 2 of the 3, it will show 66% complete.
- If you have none completed yet, it will show 0% complete.

I'm working on a fix, but for now that's how it works!

**Comment by lakiron** [comment]
Thanks for the explanation. I'll be waiting for future updates :p
