### ISSUE TITLE
/ar migrate not migrating all players

### ISSUE THREAD

**Issue by SalihbasicM** [Staartvin/Autorank-2#737]
After recently installing Autorank, I tried to migrate players' vanilla playtime through `/ar migrate vanilla`. I don't use any plugins for statistics collection. While some players did have their data migrated, majority did not. 

Even after running the command multiple times over the course of several hours (which was a bad idea, since players get their vanilla playtime added on top of their playtime in Autorank's database with each migration, but hey, I might as well go all in), the number of (new, anyway) players whose data was migrated only went up a tiny bit. The rest are the same players who were already migrated.

The server has hundreds of registered players, but it seems that the plugin migrates only the data of those players who have joined the server after Autorank was added.

Here is the Setting.yml: https://pastebin.com/P6X33yKf
Here are the results of running `/ar debug`: https://pastebin.com/ni00HmgW

First relevant log (without debug on): https://pastebin.com/4AbtUNBt
Second relevant log (with debug on): https://pastebin.com/SF2ZHduZ

**Comment by Staartvin** [comment]
Hmm, interesting. Can you contact me on Discord (tag me in the Autorank discord server)?

**Comment by Staartvin** [comment]
We solved this by using a newer version. For anyone having issues, try this build: http://staartvin.com:8080/job/Autorank/82/
