### ISSUE TITLE
AutoRank votes requirement not working

### ISSUE THREAD

**Issue by lakiron** [Staartvin/Autorank-2#739]
heyo, it's me again with a new problem at hand :D
I have statz 1.5.3 (the latest version compatible with 1.13.2) installed and working, Ar 4.3.3
For some reason the second I add the votes requirement AR refuses to load paths.yml and do /ar reload
That's pretty much it. I can't find any reason for that. Below are my paths.yml and debugger log for AR
P.S AR hooks shows Statz, Statz hooks show Votifier
P.P.S Ow and while we're at it, for some reason AR performs commands twice (screenshot of console logs of this occuring in the wild xd)
[debug-20200510083035.txt](https://github.com/Staartvin/Autorank-2/files/4605256/debug-20200510083035.txt)

Paths.yml:
player:
  prerequisites:
    in group: 
      value: default
  requirements:
    time: 
      value: 5h
  results:
    command:
      value: lp user &p parent add player
    command2:
      value: eco give &p 2500
    message:
      value: Поздравляем, вы стали Игроком!
  options:
    auto choose: true
    priority: 1

old:
  prerequisites:
    in group: 
      value: player
  requirements:
    time: 
      value: 20h
  results:
    command:
      value: lp user &p parent add old
    command2:
      value: eco give &p 7500
    message:
      value: Поздравляем, вы стали Пожилым!
  options:
    auto choose: true
    priority: 2

elder: (it breaks because of this)
  prerequisites:
    in group: 
      value: old
  requirements:
    time:
      value: 30h
    votes: 
      value: 5
  results:
    command:
      value: lp user &p parent add elder
    command2:
      value: eco give &p 10000
    message:
      value: Поздравляем, вы стали Уважаемым!
  options:
    auto choose: true
    priority: 3
![console](https://user-images.githubusercontent.com/36330602/81492674-6a0fd080-92a2-11ea-9904-97eec0417351.png)

**Comment by Staartvin** [comment]
Could you post your paths file in a pastebin and link it here? I can't read it here.
