### ISSUE TITLE
MySQL throws SSL connection errors

### ISSUE THREAD

**Issue by mcdaddytalk** [Staartvin/Autorank-2#740]
MySQL storage (mysql 5.5.45+, 5.6.26+, 5.7.6+) useSSL must be explicitly enabled/disabled

Either add an option to set it in the settings or turn it off

jdbc:mysql://<host>:<port>/<db>?autoReconnect=true&useSSL=<false|true>

**Comment by Staartvin** [comment]
This is solved in the latest dev builds.
