### ISSUE TITLE
Update Spigot

### ISSUE THREAD

**Issue by PeggyDaPenguin** [Staartvin/Autorank-2#742]
Hello,

Your spigot pages for autorank and plugin library are quite outdated now. Could you please update them?

thank you,
Peggy_Penguin

**Comment by Staartvin** [comment]
In what sense are they outdated?

**Comment by PeggyDaPenguin** [comment]
it says they were updated in january, but I know you've added a lot more stuff since then.

**Comment by Staartvin** [comment]
I'll look into that. I've been working on Autorank and Statz, but not all of it is stable, that's why I didn't update yet.

**Comment by PeggyDaPenguin** [comment]
Could you possibly put your newest versions on the github pages and label them as unstable?

**Comment by Staartvin** [comment]
You can find them here: http://staartvin.com:8080/job/Autorank/
