### ISSUE TITLE
Help Me!

### ISSUE THREAD

**Issue by H4rryPotter1215** [Staartvin/Autorank-2#744]
**Help!**
    I am new to pretty much everything as far as servers are concerned and downloaded autorank a while back and have been slowly figuring it out through the help of the wiki. But I have ran into a problem that I cannot solve nor does the wiki cover it or at least I have not found yet. I am using luckperms and have created a track called rankups. On this track you start out in the group default, then move up to farmhand; farmer; townsperson; towncouncil; mayor; and so on. And I have my path configured to where you start out in the default group labeled [Peasant]. The requirements are:
requirements:
```
      money: 
         value: 200
      time:
         value: 12h
      exp:
         value: 20
      blocks moved:
         value: 5000;0
      blocks broken:
         value: 5000
      blocks placed:
         value: 5000
```
But I recently had a player meet all the requirements. Autorank said that the player had completed the path of farmhadn but wasnt ranked up. And was not moved to the next group along the luckperms track rankups. Have I done something wrong?

**Here is my paths.yml file:**
```
# Paths file - This file will contain all paths that a player is allowed to take. Previously known as 'AdvancedConfig.yml'.
# This file contains (by default) a Test group that shows the basic syntax of this file. 
# For more information, go to https://github.com/Armarr/Autorank-2/wiki/How-to-configure-the-Paths.yml-file%3F.
Farmhand:
   prerequisites:
      in group:
         value: default

   upon choosing:
      message: 
         value: "The mighty oak tree was once a nut!"
   requirments:
      money: 
         value: 200
      time:
         value: 12h
      exp:
         value: 20
      blocks moved:
         value: 5000;0
      blocks broken:
         value: 5000
      blocks placed:
         value: 5000
   options:
      infinite pathing: false
      auto choose: true
Farmer:
   prerequisites:
      in group:
         value: farmer

   upon choosing:
      message: 
         value: "Put your back into it!"
   requirements:
      money: 
         value: 300
      time:
         value: 1d
      exp:
         value: 30
      blocks moved:
         value: 10000;0
      blocks broken:
         value: 10000
      blocks placed:
         value: 10000
      fish caught:
         value: 200
   options:
      infinite pathing: false
      auto choose: true
Townsperson:
   prerequisites:
      in group:
         value: farmer

   upon choosing:
      message: 
         value: "Your getting there!"
   requirements:
      money: 
         value: 500
      time:
         value: 3d
      exp:
         value: 50
      blocks moved:
         value: 30000;0
      blocks broken:
         value: 20000
      blocks placed:
         value: 20000
   options:
      infinite pathing: false
      auto choose: true
Towncouncil:
   prerequisites:
      in group:
         value: townsperson

   upon choosing:
      message: 
         value: "Your getting there!"
   requirements:
      money: 
         value: 1000
      time:
         value: 6d
      exp:
         value: 80
      blocks moved:
         value: 50000;0
      blocks broken:
         value: 25000
      blocks placed:
         value: 25000
      grief prevention remaining blocks:
         value: 1500
   options:
      infinite pathing: false
      auto choose: true
Mayor:
   prerequisites:
      in group:
         value: towncouncil

   upon choosing:
      message: 
         value: "As mayor I will fully support my town!"
   requirements:
      money: 
         value: 1500
      time:
         value: 10d
      exp:
         value: 120
      blocks moved:
         value: 100000;0
      blocks broken:
         value: 35000
      blocks placed:
         value: 35000
      grief prevention remaining blocks:
         value: 2000
   options:
      infinite pathing: false
      auto choose: true
```

Can you please help me?

**Comment by Staartvin** [comment]
Nice patching system! I think you almost got it figured out. Your paths do not have any results so when a player completes all requirements, nothing will be performed. What you probably want is to add a command result that promotes the player up along the Luckperms track you set up.

**Comment by H4rryPotter1215** [comment]
Thanks for replying so fast Staartvin, I love your plugin first off. But that is what I figured but I so I tried this:
```
Farmhand:
   prerequisites:
      in group:
         value: default

   upon choosing:
      message: 
         value: "The mighty oak tree was once a nut!"
   requirments:
      money: 
         value: 200
      time:
         value: 12h
      exp:
         value: 20
      blocks moved:
         value: 5000;0
      blocks broken:
         value: 5000
      blocks placed:
         value: 5000
   Results:
      in group:
         value: farmhand
   options:
   infinite pathing: false
      auto choose: true


```
But autorank sent me this error message:
![Minecraft 1 15 2 5_30_2020 9_53_28 AM](https://user-images.githubusercontent.com/66152750/83330282-fab34e00-a25b-11ea-9b33-8aab00b55697.png)
But in luckperms I have the group farmhand:
![Editor _ LuckPerms and 1 more page - Personal - Microsoft​ Edge 5_30_2020 9_54_30 AM](https://user-images.githubusercontent.com/66152750/83330345-3fd78000-a25c-11ea-893a-8dd680e16818.png)
So am I using the wrong command to promote someone?

**Comment by H4rryPotter1215** [comment]
Hey, I finally figured it out thanks! But I have one more question before I close this thread, is it possible to change the command instead of /ar rank or /ar check to change it to a simpler command like /check or /rank. Thanks!

**Comment by Staartvin** [comment]
Great to hear you solved it! You can add aliases using Bukkit/Spigot's file. You can use that to add an alias so /ar rank becomes /ar check.

**Comment by H4rryPotter1215** [comment]
Hey I thought about creating a new thread but, the players now are ranking up properly but the permissions were working perfectly before I completed the auto-ranking pathing system, but now the permissions are in shambles... Has this ever happened before? Both of my test subjects ranked up and are the same rank but only some of there permissions that worked, and was different for each player. Auto-rank was the only thing that I could think of because maybe auto-ranks permission system is interfering? So please help!

**Comment by H4rryPotter1215** [comment]
Hey never mind, I made a stupid mistake I will go ahead and close the thread. Again Like I said still new when it comes to these kinds of things 😄. Just wanted to thank you for the swift support! And finally = just wanted to thank you again for creating such an amazing plugin!
