### ISSUE TITLE
Autorank not hooking into PAPI

### ISSUE THREAD

**Issue by Christofmeg** [Staartvin/Autorank-2#748]
[PlaceholderAPI] Loaded class me.armar.plugins.autorank.Autorank from Autorank v4.4-SNAPSHOT-108 which is not a depend, softdepend or loadbefore of this plugin.

[PlaceholderAPI] autorank is attempting to register placeholders via a PlaceholderHook class which is no longer supported!

Ran this on paper 1.16.1 with autorank 4.4 snapshot 108

**Comment by Staartvin** [comment]
This has been fixed in later dev builds. If you want to try it, you can use this [build](http://staartvin.com:8080/job/Autorank/123/).

**Comment by Staartvin** [comment]
Make sure to remove your old Autorank PAPI expansion, because it does not work anymore.
