### ISSUE TITLE
@p not working as a PermissionsEx command nor a LuckPerms command

### ISSUE THREAD

**Issue by EnslavedOrphan** [Staartvin/Autorank-2#752]
okay so im having problems with using @p in the command value, ive set up this rank as i wanted so far and once i complete the path for it, its supposed to run the command. Normally, it does, ive tested it using ordinary commands like'/time set day' or '/broadcast ' and they do for sure work when i rank up, but when it comes to using @p with permission plugins the term '@p' isnt recognized properly, using this config below it doesnt actually move me to the next group in permissions ex, idk if its pex thats not hooked or im not typing this right. please help! :)

my file vvv

traveler:
  prerequisites:
    in group:
      value: wilder
  requirements:
    time:
      value: 2h
    blocks moved:
      value: 5000;0
    blocks broken:
      value: IRON_ORE;16
  options:
      auto choose: true
  results:
    money:
      value: 1000
    command:
      value: pex user @p group set traveler
    message:
      value: CONGRATULATIONS YOU HAVE BEEN PROMOTED TO &a&lTraveler&3!

**Comment by jstan425** [comment]
So i personally use &p instead of @p and it works flawlessly. I am using LuckPerms, if you are curious.
