### ISSUE TITLE
Disable Logging

### ISSUE THREAD

**Issue by ASMRyan** [Staartvin/Autorank-2#758]
Build: 119

The plugin is leaving .txt log files in ~/Autorank/logging that are upwards of 750MB each every single day. During troubleshooting I was informed that AR is not supposed to make log files unless set to in Settings.yml. I would also like to note that no such line exists in Settings.yml. Was told by Ironic_8b49 to report the issue here.

**Comment by Staartvin** [comment]
I've fixed the feature in build [123](http://staartvin.com:8080/job/Autorank/123/).
