### ISSUE TITLE
Getting error when generating javadocs

### ISSUE THREAD

**Issue by Enn3Developer** [Staartvin/Autorank-2#771]
Hi, I issued the following command at the project's root: `mvn site`; but [this is the result](https://pastebin.com/UejHndNn)
```
enn3@enn3devpc ~/Autorank-2 $ mvn -v
Apache Maven 3.6.3 (NON-CANONICAL_2020-06-13T21:25:59Z_root)
Maven home: /usr/share/apache-maven
Java version: 11.0.9.1, vendor: Oracle Corporation, runtime: /usr/lib64/openjdk-11
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.10.7-168.current", arch: "amd64", family: "unix"
```

**Comment by Staartvin** [comment]
Hmm, I've never used this command so I never checked it. What are you trying to do?

**Comment by Enn3Developer** [comment]
This command should generate javadocs using Maven

**Comment by Staartvin** [comment]
You can use `mvn javadoc:aggregate` or `mvn javadoc:javadoc` for that.

**Comment by Staartvin** [comment]
You can also see this: http://staartvin.com:8080/job/Autorank/javadoc/overview-summary.html

**Comment by Enn3Developer** [comment]
Oh, thanks
I thought that the javadocs hosted from you was unreachable (the link in the wiki, the gitbook one)

**Comment by Staartvin** [comment]
You were right, it was. I was just working on fixing that and it seems I managed.
