### ISSUE TITLE
Can't use votes requirement

### ISSUE THREAD

**Issue by austin652** [Staartvin/Autorank-2#772]
I am using Autorank v.4.5.1 and Statz 1.6.1 and the voting requirement no longer works. I receive this error
"Requirement 'votes' relies on 'Statz' being installed, but that plugin is not installed!". The problem is that I do have Statz installed, I have the latest (v1.6.1) installed but It doesn't load, below is my startup log
https://pastebin.com/1ACv88vB

**Comment by Staartvin** [comment]
So it seems that Statz is not loading properly. Let me check if I can reproduce this issue.

**Comment by austin652** [comment]
Great thanks

**Comment by Staartvin** [comment]
Okay, I've found the issue and have a new build ready for you. Can you try this build and see if it works for you? http://staartvin.com:8080/job/Statz/39/

**Comment by austin652** [comment]
It works. Thanks for the quick fix
